// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: moego/business/setting/v1/service.proto

package settingpb

import (
	money "google.golang.org/genproto/googleapis/type/money"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ItemType categorizes the primary type of service being offered.
// This helps organize services in the system and determines applicable business rules.
type Service_ItemType int32

const (
	// Unknown or unspecified service type
	// Should not be used when creating new services
	Service_SERVICE_ITEM_TYPE_UNSPECIFIED Service_ItemType = 0
	// Pet grooming services
	// Includes bathing, haircuts, nail trimming, etc.
	Service_GROOMING Service_ItemType = 1
	// Pet boarding services
	// Overnight or extended stay care
	Service_BOARDING Service_ItemType = 2
	// Daytime pet care services
	// Supervised play and care during business hours
	Service_DAYCARE Service_ItemType = 3
	// Pet evaluation services
	// Behavior assessment and service compatibility check
	Service_EVALUATION Service_ItemType = 4
	// Pet training services
	// Individual or group training sessions
	Service_TRAINING Service_ItemType = 5
)

// Enum value maps for Service_ItemType.
var (
	Service_ItemType_name = map[int32]string{
		0: "SERVICE_ITEM_TYPE_UNSPECIFIED",
		1: "GROOMING",
		2: "BOARDING",
		3: "DAYCARE",
		4: "EVALUATION",
		5: "TRAINING",
	}
	Service_ItemType_value = map[string]int32{
		"SERVICE_ITEM_TYPE_UNSPECIFIED": 0,
		"GROOMING":                      1,
		"BOARDING":                      2,
		"DAYCARE":                       3,
		"EVALUATION":                    4,
		"TRAINING":                      5,
	}
)

func (x Service_ItemType) Enum() *Service_ItemType {
	p := new(Service_ItemType)
	*p = x
	return p
}

func (x Service_ItemType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Service_ItemType) Descriptor() protoreflect.EnumDescriptor {
	return file_moego_business_setting_v1_service_proto_enumTypes[0].Descriptor()
}

func (Service_ItemType) Type() protoreflect.EnumType {
	return &file_moego_business_setting_v1_service_proto_enumTypes[0]
}

func (x Service_ItemType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Service_ItemType.Descriptor instead.
func (Service_ItemType) EnumDescriptor() ([]byte, []int) {
	return file_moego_business_setting_v1_service_proto_rawDescGZIP(), []int{0, 0}
}

// Type indicates whether this is a standalone service or an add-on
// that can be combined with other services.
type Service_Type int32

const (
	// Unknown or unspecified type
	// Should not be used when creating new services
	Service_SERVICE_TYPE_UNSPECIFIED Service_Type = 0
	// Primary standalone service
	// Can be booked independently
	Service_SERVICE Service_Type = 1
	// Additional service that complements primary services
	// Must be booked with a primary service
	Service_ADDON Service_Type = 2
)

// Enum value maps for Service_Type.
var (
	Service_Type_name = map[int32]string{
		0: "SERVICE_TYPE_UNSPECIFIED",
		1: "SERVICE",
		2: "ADDON",
	}
	Service_Type_value = map[string]int32{
		"SERVICE_TYPE_UNSPECIFIED": 0,
		"SERVICE":                  1,
		"ADDON":                    2,
	}
)

func (x Service_Type) Enum() *Service_Type {
	p := new(Service_Type)
	*p = x
	return p
}

func (x Service_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Service_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_moego_business_setting_v1_service_proto_enumTypes[1].Descriptor()
}

func (Service_Type) Type() protoreflect.EnumType {
	return &file_moego_business_setting_v1_service_proto_enumTypes[1]
}

func (x Service_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Service_Type.Descriptor instead.
func (Service_Type) EnumDescriptor() ([]byte, []int) {
	return file_moego_business_setting_v1_service_proto_rawDescGZIP(), []int{0, 1}
}

// Service represents a specific service or add-on that can be provided to pets.
// Services are the core offerings of your business and can be customized based on
// location, staff availability, and service type. Each service has its own pricing,
// duration, and availability settings.
type Service struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique identifier for the service
	// Format: "srv_" followed by random characters
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Display name of the service
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Primary category of the service
	// Determines applicable business rules and pricing structure
	ServiceItemType Service_ItemType `protobuf:"varint,3,opt,name=service_item_type,json=serviceItemType,proto3,enum=moego.business.setting.v1.Service_ItemType" json:"service_item_type,omitempty"`
	// Subcategory for further service classification
	// Example: "Basic Grooming", "Premium Training"
	Category string `protobuf:"bytes,4,opt,name=category,proto3" json:"category,omitempty"`
	// Base price for the service
	// Can be adjusted based on pet size, breed, or add-ons
	Price *money.Money `protobuf:"bytes,5,opt,name=price,proto3" json:"price,omitempty"`
	// Whether this is a primary service or an add-on
	// Affects how the service can be booked
	ServiceType Service_Type `protobuf:"varint,6,opt,name=service_type,json=serviceType,proto3,enum=moego.business.setting.v1.Service_Type" json:"service_type,omitempty"`
	// Duration of the service in minutes
	// Used for scheduling and resource allocation
	ServiceTime int32 `protobuf:"varint,7,opt,name=service_time,json=serviceTime,proto3" json:"service_time,omitempty"`
	// Whether this service is available at all business locations
	// If false, check available_business_ids for specific locations
	AvailableAllBusiness bool `protobuf:"varint,8,opt,name=available_all_business,json=availableAllBusiness,proto3" json:"available_all_business,omitempty"`
	// List of business locations where this service is available
	// Only used when available_all_business is false
	AvailableBusinessIds []string `protobuf:"bytes,9,rep,name=available_business_ids,json=availableBusinessIds,proto3" json:"available_business_ids,omitempty"`
	// Whether this service can be performed by all staff members
	// If false, check available_staff_ids for specific staff
	AvailableAllStaff bool `protobuf:"varint,10,opt,name=available_all_staff,json=availableAllStaff,proto3" json:"available_all_staff,omitempty"`
	// List of staff members who can perform this service
	// Only used when available_all_staff is false
	AvailableStaffIds []string `protobuf:"bytes,11,rep,name=available_staff_ids,json=availableStaffIds,proto3" json:"available_staff_ids,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Service) Reset() {
	*x = Service{}
	mi := &file_moego_business_setting_v1_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Service) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Service) ProtoMessage() {}

func (x *Service) ProtoReflect() protoreflect.Message {
	mi := &file_moego_business_setting_v1_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Service.ProtoReflect.Descriptor instead.
func (*Service) Descriptor() ([]byte, []int) {
	return file_moego_business_setting_v1_service_proto_rawDescGZIP(), []int{0}
}

func (x *Service) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Service) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Service) GetServiceItemType() Service_ItemType {
	if x != nil {
		return x.ServiceItemType
	}
	return Service_SERVICE_ITEM_TYPE_UNSPECIFIED
}

func (x *Service) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *Service) GetPrice() *money.Money {
	if x != nil {
		return x.Price
	}
	return nil
}

func (x *Service) GetServiceType() Service_Type {
	if x != nil {
		return x.ServiceType
	}
	return Service_SERVICE_TYPE_UNSPECIFIED
}

func (x *Service) GetServiceTime() int32 {
	if x != nil {
		return x.ServiceTime
	}
	return 0
}

func (x *Service) GetAvailableAllBusiness() bool {
	if x != nil {
		return x.AvailableAllBusiness
	}
	return false
}

func (x *Service) GetAvailableBusinessIds() []string {
	if x != nil {
		return x.AvailableBusinessIds
	}
	return nil
}

func (x *Service) GetAvailableAllStaff() bool {
	if x != nil {
		return x.AvailableAllStaff
	}
	return false
}

func (x *Service) GetAvailableStaffIds() []string {
	if x != nil {
		return x.AvailableStaffIds
	}
	return nil
}

var File_moego_business_setting_v1_service_proto protoreflect.FileDescriptor

const file_moego_business_setting_v1_service_proto_rawDesc = "" +
	"\n" +
	"'moego/business/setting/v1/service.proto\x12\x19moego.business.setting.v1\x1a\x17google/type/money.proto\"\xbb\x05\n" +
	"\aService\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12W\n" +
	"\x11service_item_type\x18\x03 \x01(\x0e2+.moego.business.setting.v1.Service.ItemTypeR\x0fserviceItemType\x12\x1a\n" +
	"\bcategory\x18\x04 \x01(\tR\bcategory\x12(\n" +
	"\x05price\x18\x05 \x01(\v2\x12.google.type.MoneyR\x05price\x12J\n" +
	"\fservice_type\x18\x06 \x01(\x0e2'.moego.business.setting.v1.Service.TypeR\vserviceType\x12!\n" +
	"\fservice_time\x18\a \x01(\x05R\vserviceTime\x124\n" +
	"\x16available_all_business\x18\b \x01(\bR\x14availableAllBusiness\x124\n" +
	"\x16available_business_ids\x18\t \x03(\tR\x14availableBusinessIds\x12.\n" +
	"\x13available_all_staff\x18\n" +
	" \x01(\bR\x11availableAllStaff\x12.\n" +
	"\x13available_staff_ids\x18\v \x03(\tR\x11availableStaffIds\"t\n" +
	"\bItemType\x12!\n" +
	"\x1dSERVICE_ITEM_TYPE_UNSPECIFIED\x10\x00\x12\f\n" +
	"\bGROOMING\x10\x01\x12\f\n" +
	"\bBOARDING\x10\x02\x12\v\n" +
	"\aDAYCARE\x10\x03\x12\x0e\n" +
	"\n" +
	"EVALUATION\x10\x04\x12\f\n" +
	"\bTRAINING\x10\x05\"<\n" +
	"\x04Type\x12\x1c\n" +
	"\x18SERVICE_TYPE_UNSPECIFIED\x10\x00\x12\v\n" +
	"\aSERVICE\x10\x01\x12\t\n" +
	"\x05ADDON\x10\x02B\x8a\x01\n" +
	"!com.moego.api.business.setting.v1B\fSettingProtoP\x01ZUgithub.com/MoeGolibrary/moegoapis/genproto/go/business/setting/v1/settingpb;settingpbb\x06proto3"

var (
	file_moego_business_setting_v1_service_proto_rawDescOnce sync.Once
	file_moego_business_setting_v1_service_proto_rawDescData []byte
)

func file_moego_business_setting_v1_service_proto_rawDescGZIP() []byte {
	file_moego_business_setting_v1_service_proto_rawDescOnce.Do(func() {
		file_moego_business_setting_v1_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_moego_business_setting_v1_service_proto_rawDesc), len(file_moego_business_setting_v1_service_proto_rawDesc)))
	})
	return file_moego_business_setting_v1_service_proto_rawDescData
}

var file_moego_business_setting_v1_service_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_moego_business_setting_v1_service_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_moego_business_setting_v1_service_proto_goTypes = []any{
	(Service_ItemType)(0), // 0: moego.business.setting.v1.Service.ItemType
	(Service_Type)(0),     // 1: moego.business.setting.v1.Service.Type
	(*Service)(nil),       // 2: moego.business.setting.v1.Service
	(*money.Money)(nil),   // 3: google.type.Money
}
var file_moego_business_setting_v1_service_proto_depIdxs = []int32{
	0, // 0: moego.business.setting.v1.Service.service_item_type:type_name -> moego.business.setting.v1.Service.ItemType
	3, // 1: moego.business.setting.v1.Service.price:type_name -> google.type.Money
	1, // 2: moego.business.setting.v1.Service.service_type:type_name -> moego.business.setting.v1.Service.Type
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_moego_business_setting_v1_service_proto_init() }
func file_moego_business_setting_v1_service_proto_init() {
	if File_moego_business_setting_v1_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_moego_business_setting_v1_service_proto_rawDesc), len(file_moego_business_setting_v1_service_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_moego_business_setting_v1_service_proto_goTypes,
		DependencyIndexes: file_moego_business_setting_v1_service_proto_depIdxs,
		EnumInfos:         file_moego_business_setting_v1_service_proto_enumTypes,
		MessageInfos:      file_moego_business_setting_v1_service_proto_msgTypes,
	}.Build()
	File_moego_business_setting_v1_service_proto = out.File
	file_moego_business_setting_v1_service_proto_goTypes = nil
	file_moego_business_setting_v1_service_proto_depIdxs = nil
}
