// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: moego/business/setting/v1/setting_service.proto

package settingpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SettingService_ListPetCodes_FullMethodName     = "/moego.business.setting.v1.SettingService/ListPetCodes"
	SettingService_ListCustomerTags_FullMethodName = "/moego.business.setting.v1.SettingService/ListCustomerTags"
	SettingService_GetService_FullMethodName       = "/moego.business.setting.v1.SettingService/GetService"
	SettingService_ListServices_FullMethodName     = "/moego.business.setting.v1.SettingService/ListServices"
	SettingService_CreateService_FullMethodName    = "/moego.business.setting.v1.SettingService/CreateService"
	SettingService_UpdateService_FullMethodName    = "/moego.business.setting.v1.SettingService/UpdateService"
	SettingService_ListLodgings_FullMethodName     = "/moego.business.setting.v1.SettingService/ListLodgings"
)

// SettingServiceClient is the client API for SettingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// SettingService provides methods for managing business configuration settings.
// This includes pet codes, customer tags, and service definitions that are used
// throughout the system. These settings help standardize data entry and ensure
// consistent service delivery across all business locations.
type SettingServiceClient interface {
	// Lists all available pet codes for a company.
	//
	// Pet codes are used to flag special handling requirements or medical conditions
	// that staff need to be aware of when providing services. These codes are
	// displayed prominently in pet profiles and during service delivery.
	//
	// Returns all active codes for the specified company.
	// Returns PERMISSION_DENIED if the caller lacks access rights.
	ListPetCodes(ctx context.Context, in *ListPetCodeRequest, opts ...grpc.CallOption) (*ListPetCodeResponse, error)
	// Lists all available customer tags for a company.
	//
	// Customer tags help categorize clients and can be used for marketing,
	// reporting, and service customization. Tags can indicate preferences,
	// loyalty status, or special handling requirements.
	//
	// Returns all active tags for the specified company.
	// Returns PERMISSION_DENIED if the caller lacks access rights.
	ListCustomerTags(ctx context.Context, in *ListCustomerTagRequest, opts ...grpc.CallOption) (*ListCustomerTagResponse, error)
	// Gets the details of a specific service.
	//
	// Retrieves detailed information about a service identified by its ID.
	// Returns PERMISSION_DENIED if the caller lacks access rights.
	// Returns NOT_FOUND if the service does not exist.
	GetService(ctx context.Context, in *GetServiceRequest, opts ...grpc.CallOption) (*Service, error)
	// Lists available services based on specified criteria.
	//
	// Services can be filtered by business location and service type.
	// Results are paginated and can be used for service menu display,
	// appointment booking, and pricing calculations.
	//
	// Returns services matching the filter criteria.
	// Returns PERMISSION_DENIED if the caller lacks access rights.
	ListServices(ctx context.Context, in *ListServicesRequest, opts ...grpc.CallOption) (*ListServicesResponse, error)
	// Creates a new service.
	//
	// Adds a new service definition to the system. The service must be associated with
	// a specific company and can optionally belong to one or more business locations.
	//
	// Returns the created service with assigned ID.
	// Returns PERMISSION_DENIED if the caller lacks access rights.
	// Returns ALREADY_EXISTS if a service with the same ID already exists.
	CreateService(ctx context.Context, in *CreateServiceRequest, opts ...grpc.CallOption) (*Service, error)
	// Updates an existing service.
	//
	// Modifies the details of an existing service. The update may affect all business
	// locations where this service is used.
	//
	// Returns the updated service.
	// Returns PERMISSION_DENIED if the caller lacks access rights.
	// Returns NOT_FOUND if the service does not exist.
	UpdateService(ctx context.Context, in *UpdateServiceRequest, opts ...grpc.CallOption) (*Service, error)
	// List lodgings
	//
	// Returns a list of lodgings.
	// Returns PERMISSION_DENIED if the caller lacks access rights.
	// Returns INVALID_ARGUMENT if the request is malformed.
	// Returns NOT_FOUND if the company does not exist.
	ListLodgings(ctx context.Context, in *ListLodgingsRequest, opts ...grpc.CallOption) (*ListLodgingsResponse, error)
}

type settingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSettingServiceClient(cc grpc.ClientConnInterface) SettingServiceClient {
	return &settingServiceClient{cc}
}

func (c *settingServiceClient) ListPetCodes(ctx context.Context, in *ListPetCodeRequest, opts ...grpc.CallOption) (*ListPetCodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPetCodeResponse)
	err := c.cc.Invoke(ctx, SettingService_ListPetCodes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *settingServiceClient) ListCustomerTags(ctx context.Context, in *ListCustomerTagRequest, opts ...grpc.CallOption) (*ListCustomerTagResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListCustomerTagResponse)
	err := c.cc.Invoke(ctx, SettingService_ListCustomerTags_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *settingServiceClient) GetService(ctx context.Context, in *GetServiceRequest, opts ...grpc.CallOption) (*Service, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Service)
	err := c.cc.Invoke(ctx, SettingService_GetService_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *settingServiceClient) ListServices(ctx context.Context, in *ListServicesRequest, opts ...grpc.CallOption) (*ListServicesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListServicesResponse)
	err := c.cc.Invoke(ctx, SettingService_ListServices_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *settingServiceClient) CreateService(ctx context.Context, in *CreateServiceRequest, opts ...grpc.CallOption) (*Service, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Service)
	err := c.cc.Invoke(ctx, SettingService_CreateService_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *settingServiceClient) UpdateService(ctx context.Context, in *UpdateServiceRequest, opts ...grpc.CallOption) (*Service, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Service)
	err := c.cc.Invoke(ctx, SettingService_UpdateService_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *settingServiceClient) ListLodgings(ctx context.Context, in *ListLodgingsRequest, opts ...grpc.CallOption) (*ListLodgingsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListLodgingsResponse)
	err := c.cc.Invoke(ctx, SettingService_ListLodgings_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SettingServiceServer is the server API for SettingService service.
// All implementations must embed UnimplementedSettingServiceServer
// for forward compatibility.
//
// SettingService provides methods for managing business configuration settings.
// This includes pet codes, customer tags, and service definitions that are used
// throughout the system. These settings help standardize data entry and ensure
// consistent service delivery across all business locations.
type SettingServiceServer interface {
	// Lists all available pet codes for a company.
	//
	// Pet codes are used to flag special handling requirements or medical conditions
	// that staff need to be aware of when providing services. These codes are
	// displayed prominently in pet profiles and during service delivery.
	//
	// Returns all active codes for the specified company.
	// Returns PERMISSION_DENIED if the caller lacks access rights.
	ListPetCodes(context.Context, *ListPetCodeRequest) (*ListPetCodeResponse, error)
	// Lists all available customer tags for a company.
	//
	// Customer tags help categorize clients and can be used for marketing,
	// reporting, and service customization. Tags can indicate preferences,
	// loyalty status, or special handling requirements.
	//
	// Returns all active tags for the specified company.
	// Returns PERMISSION_DENIED if the caller lacks access rights.
	ListCustomerTags(context.Context, *ListCustomerTagRequest) (*ListCustomerTagResponse, error)
	// Gets the details of a specific service.
	//
	// Retrieves detailed information about a service identified by its ID.
	// Returns PERMISSION_DENIED if the caller lacks access rights.
	// Returns NOT_FOUND if the service does not exist.
	GetService(context.Context, *GetServiceRequest) (*Service, error)
	// Lists available services based on specified criteria.
	//
	// Services can be filtered by business location and service type.
	// Results are paginated and can be used for service menu display,
	// appointment booking, and pricing calculations.
	//
	// Returns services matching the filter criteria.
	// Returns PERMISSION_DENIED if the caller lacks access rights.
	ListServices(context.Context, *ListServicesRequest) (*ListServicesResponse, error)
	// Creates a new service.
	//
	// Adds a new service definition to the system. The service must be associated with
	// a specific company and can optionally belong to one or more business locations.
	//
	// Returns the created service with assigned ID.
	// Returns PERMISSION_DENIED if the caller lacks access rights.
	// Returns ALREADY_EXISTS if a service with the same ID already exists.
	CreateService(context.Context, *CreateServiceRequest) (*Service, error)
	// Updates an existing service.
	//
	// Modifies the details of an existing service. The update may affect all business
	// locations where this service is used.
	//
	// Returns the updated service.
	// Returns PERMISSION_DENIED if the caller lacks access rights.
	// Returns NOT_FOUND if the service does not exist.
	UpdateService(context.Context, *UpdateServiceRequest) (*Service, error)
	// List lodgings
	//
	// Returns a list of lodgings.
	// Returns PERMISSION_DENIED if the caller lacks access rights.
	// Returns INVALID_ARGUMENT if the request is malformed.
	// Returns NOT_FOUND if the company does not exist.
	ListLodgings(context.Context, *ListLodgingsRequest) (*ListLodgingsResponse, error)
	mustEmbedUnimplementedSettingServiceServer()
}

// UnimplementedSettingServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSettingServiceServer struct{}

func (UnimplementedSettingServiceServer) ListPetCodes(context.Context, *ListPetCodeRequest) (*ListPetCodeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListPetCodes not implemented")
}
func (UnimplementedSettingServiceServer) ListCustomerTags(context.Context, *ListCustomerTagRequest) (*ListCustomerTagResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListCustomerTags not implemented")
}
func (UnimplementedSettingServiceServer) GetService(context.Context, *GetServiceRequest) (*Service, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetService not implemented")
}
func (UnimplementedSettingServiceServer) ListServices(context.Context, *ListServicesRequest) (*ListServicesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListServices not implemented")
}
func (UnimplementedSettingServiceServer) CreateService(context.Context, *CreateServiceRequest) (*Service, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateService not implemented")
}
func (UnimplementedSettingServiceServer) UpdateService(context.Context, *UpdateServiceRequest) (*Service, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateService not implemented")
}
func (UnimplementedSettingServiceServer) ListLodgings(context.Context, *ListLodgingsRequest) (*ListLodgingsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListLodgings not implemented")
}
func (UnimplementedSettingServiceServer) mustEmbedUnimplementedSettingServiceServer() {}
func (UnimplementedSettingServiceServer) testEmbeddedByValue()                        {}

// UnsafeSettingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SettingServiceServer will
// result in compilation errors.
type UnsafeSettingServiceServer interface {
	mustEmbedUnimplementedSettingServiceServer()
}

func RegisterSettingServiceServer(s grpc.ServiceRegistrar, srv SettingServiceServer) {
	// If the following call pancis, it indicates UnimplementedSettingServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SettingService_ServiceDesc, srv)
}

func _SettingService_ListPetCodes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPetCodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SettingServiceServer).ListPetCodes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SettingService_ListPetCodes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SettingServiceServer).ListPetCodes(ctx, req.(*ListPetCodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SettingService_ListCustomerTags_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCustomerTagRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SettingServiceServer).ListCustomerTags(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SettingService_ListCustomerTags_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SettingServiceServer).ListCustomerTags(ctx, req.(*ListCustomerTagRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SettingService_GetService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SettingServiceServer).GetService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SettingService_GetService_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SettingServiceServer).GetService(ctx, req.(*GetServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SettingService_ListServices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListServicesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SettingServiceServer).ListServices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SettingService_ListServices_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SettingServiceServer).ListServices(ctx, req.(*ListServicesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SettingService_CreateService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SettingServiceServer).CreateService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SettingService_CreateService_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SettingServiceServer).CreateService(ctx, req.(*CreateServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SettingService_UpdateService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SettingServiceServer).UpdateService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SettingService_UpdateService_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SettingServiceServer).UpdateService(ctx, req.(*UpdateServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SettingService_ListLodgings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListLodgingsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SettingServiceServer).ListLodgings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SettingService_ListLodgings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SettingServiceServer).ListLodgings(ctx, req.(*ListLodgingsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SettingService_ServiceDesc is the grpc.ServiceDesc for SettingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SettingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "moego.business.setting.v1.SettingService",
	HandlerType: (*SettingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListPetCodes",
			Handler:    _SettingService_ListPetCodes_Handler,
		},
		{
			MethodName: "ListCustomerTags",
			Handler:    _SettingService_ListCustomerTags_Handler,
		},
		{
			MethodName: "GetService",
			Handler:    _SettingService_GetService_Handler,
		},
		{
			MethodName: "ListServices",
			Handler:    _SettingService_ListServices_Handler,
		},
		{
			MethodName: "CreateService",
			Handler:    _SettingService_CreateService_Handler,
		},
		{
			MethodName: "UpdateService",
			Handler:    _SettingService_UpdateService_Handler,
		},
		{
			MethodName: "ListLodgings",
			Handler:    _SettingService_ListLodgings_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "moego/business/setting/v1/setting_service.proto",
}
