// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: moego/business/setting/v1/setting_service.proto

package settingpb

import (
	commonpb "github.com/MoeGolibrary/moegoapis/genproto/go/common/v1/commonpb"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	money "google.golang.org/genproto/googleapis/type/money"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request message for listing pet codes.
type ListPetCodesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID of the company to list pet codes for
	// Required. Must be a valid company ID
	CompanyId     string `protobuf:"bytes,1,opt,name=company_id,json=companyId,proto3" json:"company_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPetCodesRequest) Reset() {
	*x = ListPetCodesRequest{}
	mi := &file_moego_business_setting_v1_setting_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPetCodesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPetCodesRequest) ProtoMessage() {}

func (x *ListPetCodesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_moego_business_setting_v1_setting_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPetCodesRequest.ProtoReflect.Descriptor instead.
func (*ListPetCodesRequest) Descriptor() ([]byte, []int) {
	return file_moego_business_setting_v1_setting_service_proto_rawDescGZIP(), []int{0}
}

func (x *ListPetCodesRequest) GetCompanyId() string {
	if x != nil {
		return x.CompanyId
	}
	return ""
}

// Response message for listing pet codes.
type ListPetCodesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// List of available pet codes
	// May be empty if no codes are defined
	Codes         []*PetCode `protobuf:"bytes,1,rep,name=codes,proto3" json:"codes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPetCodesResponse) Reset() {
	*x = ListPetCodesResponse{}
	mi := &file_moego_business_setting_v1_setting_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPetCodesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPetCodesResponse) ProtoMessage() {}

func (x *ListPetCodesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_moego_business_setting_v1_setting_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPetCodesResponse.ProtoReflect.Descriptor instead.
func (*ListPetCodesResponse) Descriptor() ([]byte, []int) {
	return file_moego_business_setting_v1_setting_service_proto_rawDescGZIP(), []int{1}
}

func (x *ListPetCodesResponse) GetCodes() []*PetCode {
	if x != nil {
		return x.Codes
	}
	return nil
}

// Request message for listing customer tags.
type ListCustomerTagsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID of the company to list customer tags for
	// Required. Must be a valid company ID
	CompanyId     string `protobuf:"bytes,1,opt,name=company_id,json=companyId,proto3" json:"company_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCustomerTagsRequest) Reset() {
	*x = ListCustomerTagsRequest{}
	mi := &file_moego_business_setting_v1_setting_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCustomerTagsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCustomerTagsRequest) ProtoMessage() {}

func (x *ListCustomerTagsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_moego_business_setting_v1_setting_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCustomerTagsRequest.ProtoReflect.Descriptor instead.
func (*ListCustomerTagsRequest) Descriptor() ([]byte, []int) {
	return file_moego_business_setting_v1_setting_service_proto_rawDescGZIP(), []int{2}
}

func (x *ListCustomerTagsRequest) GetCompanyId() string {
	if x != nil {
		return x.CompanyId
	}
	return ""
}

// Response message for listing customer tags.
type ListCustomerTagsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// List of available customer tags
	// May be empty if no tags are defined
	Tags          []*CustomerTag `protobuf:"bytes,1,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCustomerTagsResponse) Reset() {
	*x = ListCustomerTagsResponse{}
	mi := &file_moego_business_setting_v1_setting_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCustomerTagsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCustomerTagsResponse) ProtoMessage() {}

func (x *ListCustomerTagsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_moego_business_setting_v1_setting_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCustomerTagsResponse.ProtoReflect.Descriptor instead.
func (*ListCustomerTagsResponse) Descriptor() ([]byte, []int) {
	return file_moego_business_setting_v1_setting_service_proto_rawDescGZIP(), []int{3}
}

func (x *ListCustomerTagsResponse) GetTags() []*CustomerTag {
	if x != nil {
		return x.Tags
	}
	return nil
}

// Request message for listing customer referral sources.
type ListCustomerReferralSourcesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID of the company to list referral sources for
	// Required. Must be a valid company ID
	CompanyId     string `protobuf:"bytes,1,opt,name=company_id,json=companyId,proto3" json:"company_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCustomerReferralSourcesRequest) Reset() {
	*x = ListCustomerReferralSourcesRequest{}
	mi := &file_moego_business_setting_v1_setting_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCustomerReferralSourcesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCustomerReferralSourcesRequest) ProtoMessage() {}

func (x *ListCustomerReferralSourcesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_moego_business_setting_v1_setting_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCustomerReferralSourcesRequest.ProtoReflect.Descriptor instead.
func (*ListCustomerReferralSourcesRequest) Descriptor() ([]byte, []int) {
	return file_moego_business_setting_v1_setting_service_proto_rawDescGZIP(), []int{4}
}

func (x *ListCustomerReferralSourcesRequest) GetCompanyId() string {
	if x != nil {
		return x.CompanyId
	}
	return ""
}

// Response message for listing customer referral sources.
type ListCustomerReferralSourcesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// List of available referral sources
	// May be empty if no sources are defined
	ReferralSources []*ReferralSource `protobuf:"bytes,1,rep,name=referral_sources,json=referralSources,proto3" json:"referral_sources,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ListCustomerReferralSourcesResponse) Reset() {
	*x = ListCustomerReferralSourcesResponse{}
	mi := &file_moego_business_setting_v1_setting_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCustomerReferralSourcesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCustomerReferralSourcesResponse) ProtoMessage() {}

func (x *ListCustomerReferralSourcesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_moego_business_setting_v1_setting_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCustomerReferralSourcesResponse.ProtoReflect.Descriptor instead.
func (*ListCustomerReferralSourcesResponse) Descriptor() ([]byte, []int) {
	return file_moego_business_setting_v1_setting_service_proto_rawDescGZIP(), []int{5}
}

func (x *ListCustomerReferralSourcesResponse) GetReferralSources() []*ReferralSource {
	if x != nil {
		return x.ReferralSources
	}
	return nil
}

// Request message for listing services.
type ListServicesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID of the company to list services for
	// Required. Must be a valid company ID
	CompanyId string `protobuf:"bytes,1,opt,name=company_id,json=companyId,proto3" json:"company_id,omitempty"`
	// Pagination parameters for the request
	// Required. Defines page size and token for continuation
	Pagination *commonpb.Pagination `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	// List of business locations to filter services by
	// Optional. If empty, returns services from all locations
	BusinessIds []string `protobuf:"bytes,3,rep,name=business_ids,json=businessIds,proto3" json:"business_ids,omitempty"`
	// Optional filters to apply to the service list
	Filter        *ListServicesRequest_Filter `protobuf:"bytes,4,opt,name=filter,proto3" json:"filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListServicesRequest) Reset() {
	*x = ListServicesRequest{}
	mi := &file_moego_business_setting_v1_setting_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListServicesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListServicesRequest) ProtoMessage() {}

func (x *ListServicesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_moego_business_setting_v1_setting_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListServicesRequest.ProtoReflect.Descriptor instead.
func (*ListServicesRequest) Descriptor() ([]byte, []int) {
	return file_moego_business_setting_v1_setting_service_proto_rawDescGZIP(), []int{6}
}

func (x *ListServicesRequest) GetCompanyId() string {
	if x != nil {
		return x.CompanyId
	}
	return ""
}

func (x *ListServicesRequest) GetPagination() *commonpb.Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *ListServicesRequest) GetBusinessIds() []string {
	if x != nil {
		return x.BusinessIds
	}
	return nil
}

func (x *ListServicesRequest) GetFilter() *ListServicesRequest_Filter {
	if x != nil {
		return x.Filter
	}
	return nil
}

// Response message for listing services.
type ListServicesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Token for retrieving the next page of results
	// Empty if there are no more results
	NextPageToken string `protobuf:"bytes,1,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	// List of services matching the request criteria
	// May be empty if no services match
	Services      []*Service `protobuf:"bytes,2,rep,name=services,proto3" json:"services,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListServicesResponse) Reset() {
	*x = ListServicesResponse{}
	mi := &file_moego_business_setting_v1_setting_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListServicesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListServicesResponse) ProtoMessage() {}

func (x *ListServicesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_moego_business_setting_v1_setting_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListServicesResponse.ProtoReflect.Descriptor instead.
func (*ListServicesResponse) Descriptor() ([]byte, []int) {
	return file_moego_business_setting_v1_setting_service_proto_rawDescGZIP(), []int{7}
}

func (x *ListServicesResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

func (x *ListServicesResponse) GetServices() []*Service {
	if x != nil {
		return x.Services
	}
	return nil
}

// Request message for getting a service.
type GetServiceRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID of the company that owns the service
	// Required. Must be a valid company ID
	CompanyId string `protobuf:"bytes,1,opt,name=company_id,json=companyId,proto3" json:"company_id,omitempty"`
	// ID of the service to retrieve
	// Required. Must be a valid service ID
	Id            string `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetServiceRequest) Reset() {
	*x = GetServiceRequest{}
	mi := &file_moego_business_setting_v1_setting_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetServiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetServiceRequest) ProtoMessage() {}

func (x *GetServiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_moego_business_setting_v1_setting_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetServiceRequest.ProtoReflect.Descriptor instead.
func (*GetServiceRequest) Descriptor() ([]byte, []int) {
	return file_moego_business_setting_v1_setting_service_proto_rawDescGZIP(), []int{8}
}

func (x *GetServiceRequest) GetCompanyId() string {
	if x != nil {
		return x.CompanyId
	}
	return ""
}

func (x *GetServiceRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// Request message for creating a service.
type CreateServiceRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID of the company to create the service under
	// Required. Must be a valid company ID
	CompanyId string `protobuf:"bytes,1,opt,name=company_id,json=companyId,proto3" json:"company_id,omitempty"`
	// Name of the service (e.g., "Grooming", "Boarding")
	// Required. Should be human-readable and unique within the company
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// List of business locations where this service is available
	// Optional. If empty, service is available at all locations
	BusinessIds []string `protobuf:"bytes,3,rep,name=business_ids,json=businessIds,proto3" json:"business_ids,omitempty"`
	// Type of service (e.g., grooming, boarding, daycare)
	// Required. Used for categorization and filtering
	ServiceItemType Service_ItemType `protobuf:"varint,4,opt,name=service_item_type,json=serviceItemType,proto3,enum=moego.business.setting.v1.Service_ItemType" json:"service_item_type,omitempty"`
	// Base price for the service
	// Can be adjusted based on pet size, breed, or add-ons
	Price *money.Money `protobuf:"bytes,5,opt,name=price,proto3" json:"price,omitempty"`
	// Whether this is a primary service or an add-on
	// Affects how the service can be booked
	ServiceType Service_Type `protobuf:"varint,6,opt,name=service_type,json=serviceType,proto3,enum=moego.business.setting.v1.Service_Type" json:"service_type,omitempty"`
	// Duration of the service in minutes
	// Used for scheduling and resource allocation
	ServiceTime int32 `protobuf:"varint,7,opt,name=service_time,json=serviceTime,proto3" json:"service_time,omitempty"`
	// Whether this service is available at all business locations
	// If false, check available_business_ids for specific locations
	AvailableAllBusiness bool `protobuf:"varint,8,opt,name=available_all_business,json=availableAllBusiness,proto3" json:"available_all_business,omitempty"`
	// List of business locations where this service is available
	// Only used when available_all_business is false
	AvailableBusinessIds []string `protobuf:"bytes,9,rep,name=available_business_ids,json=availableBusinessIds,proto3" json:"available_business_ids,omitempty"`
	// Whether this service can be performed by all staff members
	// If false, check available_staff_ids for specific staff
	AvailableAllStaff bool `protobuf:"varint,10,opt,name=available_all_staff,json=availableAllStaff,proto3" json:"available_all_staff,omitempty"`
	// List of staff members who can perform this service
	// Only used when available_all_staff is false
	AvailableStaffIds []string `protobuf:"bytes,11,rep,name=available_staff_ids,json=availableStaffIds,proto3" json:"available_staff_ids,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CreateServiceRequest) Reset() {
	*x = CreateServiceRequest{}
	mi := &file_moego_business_setting_v1_setting_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateServiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateServiceRequest) ProtoMessage() {}

func (x *CreateServiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_moego_business_setting_v1_setting_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateServiceRequest.ProtoReflect.Descriptor instead.
func (*CreateServiceRequest) Descriptor() ([]byte, []int) {
	return file_moego_business_setting_v1_setting_service_proto_rawDescGZIP(), []int{9}
}

func (x *CreateServiceRequest) GetCompanyId() string {
	if x != nil {
		return x.CompanyId
	}
	return ""
}

func (x *CreateServiceRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateServiceRequest) GetBusinessIds() []string {
	if x != nil {
		return x.BusinessIds
	}
	return nil
}

func (x *CreateServiceRequest) GetServiceItemType() Service_ItemType {
	if x != nil {
		return x.ServiceItemType
	}
	return Service_SERVICE_ITEM_TYPE_UNSPECIFIED
}

func (x *CreateServiceRequest) GetPrice() *money.Money {
	if x != nil {
		return x.Price
	}
	return nil
}

func (x *CreateServiceRequest) GetServiceType() Service_Type {
	if x != nil {
		return x.ServiceType
	}
	return Service_SERVICE_TYPE_UNSPECIFIED
}

func (x *CreateServiceRequest) GetServiceTime() int32 {
	if x != nil {
		return x.ServiceTime
	}
	return 0
}

func (x *CreateServiceRequest) GetAvailableAllBusiness() bool {
	if x != nil {
		return x.AvailableAllBusiness
	}
	return false
}

func (x *CreateServiceRequest) GetAvailableBusinessIds() []string {
	if x != nil {
		return x.AvailableBusinessIds
	}
	return nil
}

func (x *CreateServiceRequest) GetAvailableAllStaff() bool {
	if x != nil {
		return x.AvailableAllStaff
	}
	return false
}

func (x *CreateServiceRequest) GetAvailableStaffIds() []string {
	if x != nil {
		return x.AvailableStaffIds
	}
	return nil
}

// Request message for updating a service.
type UpdateServiceRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID of the company that owns the service
	// Required. Must be a valid company ID
	CompanyId string `protobuf:"bytes,1,opt,name=company_id,json=companyId,proto3" json:"company_id,omitempty"`
	// Unique identifier of the service to update
	// Required. Must be a valid service ID
	Id string `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	// Name of the service (e.g., "Grooming", "Boarding")
	// Required. Should be human-readable and unique within the company
	Name string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	// List of business locations where this service is available
	// Optional. If empty, service is available at all locations
	BusinessIds []string `protobuf:"bytes,4,rep,name=business_ids,json=businessIds,proto3" json:"business_ids,omitempty"`
	// Base price for the service
	// Can be adjusted based on pet size, breed, or add-ons
	Price *money.Money `protobuf:"bytes,5,opt,name=price,proto3" json:"price,omitempty"`
	// Duration of the service in minutes
	// Used for scheduling and resource allocation
	ServiceTime int32 `protobuf:"varint,6,opt,name=service_time,json=serviceTime,proto3" json:"service_time,omitempty"`
	// Whether this service is available at all business locations
	// If false, check available_business_ids for specific locations
	AvailableAllBusiness bool `protobuf:"varint,7,opt,name=available_all_business,json=availableAllBusiness,proto3" json:"available_all_business,omitempty"`
	// List of business locations where this service is available
	// Only used when available_all_business is false
	AvailableBusinessIds []string `protobuf:"bytes,8,rep,name=available_business_ids,json=availableBusinessIds,proto3" json:"available_business_ids,omitempty"`
	// Whether this service can be performed by all staff members
	// If false, check available_staff_ids for specific staff
	AvailableAllStaff bool `protobuf:"varint,9,opt,name=available_all_staff,json=availableAllStaff,proto3" json:"available_all_staff,omitempty"`
	// List of staff members who can perform this service
	// Only used when available_all_staff is false
	AvailableStaffIds []string `protobuf:"bytes,10,rep,name=available_staff_ids,json=availableStaffIds,proto3" json:"available_staff_ids,omitempty"`
	// Whether this service is inactive
	Inactive      bool `protobuf:"varint,11,opt,name=inactive,proto3" json:"inactive,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateServiceRequest) Reset() {
	*x = UpdateServiceRequest{}
	mi := &file_moego_business_setting_v1_setting_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateServiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateServiceRequest) ProtoMessage() {}

func (x *UpdateServiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_moego_business_setting_v1_setting_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateServiceRequest.ProtoReflect.Descriptor instead.
func (*UpdateServiceRequest) Descriptor() ([]byte, []int) {
	return file_moego_business_setting_v1_setting_service_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateServiceRequest) GetCompanyId() string {
	if x != nil {
		return x.CompanyId
	}
	return ""
}

func (x *UpdateServiceRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateServiceRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateServiceRequest) GetBusinessIds() []string {
	if x != nil {
		return x.BusinessIds
	}
	return nil
}

func (x *UpdateServiceRequest) GetPrice() *money.Money {
	if x != nil {
		return x.Price
	}
	return nil
}

func (x *UpdateServiceRequest) GetServiceTime() int32 {
	if x != nil {
		return x.ServiceTime
	}
	return 0
}

func (x *UpdateServiceRequest) GetAvailableAllBusiness() bool {
	if x != nil {
		return x.AvailableAllBusiness
	}
	return false
}

func (x *UpdateServiceRequest) GetAvailableBusinessIds() []string {
	if x != nil {
		return x.AvailableBusinessIds
	}
	return nil
}

func (x *UpdateServiceRequest) GetAvailableAllStaff() bool {
	if x != nil {
		return x.AvailableAllStaff
	}
	return false
}

func (x *UpdateServiceRequest) GetAvailableStaffIds() []string {
	if x != nil {
		return x.AvailableStaffIds
	}
	return nil
}

func (x *UpdateServiceRequest) GetInactive() bool {
	if x != nil {
		return x.Inactive
	}
	return false
}

// Request message for listing lodgings.
type ListLodgingsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID of the company to list lodgings for
	// Required. Must be a valid company ID
	CompanyId     string `protobuf:"bytes,1,opt,name=company_id,json=companyId,proto3" json:"company_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLodgingsRequest) Reset() {
	*x = ListLodgingsRequest{}
	mi := &file_moego_business_setting_v1_setting_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLodgingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLodgingsRequest) ProtoMessage() {}

func (x *ListLodgingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_moego_business_setting_v1_setting_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLodgingsRequest.ProtoReflect.Descriptor instead.
func (*ListLodgingsRequest) Descriptor() ([]byte, []int) {
	return file_moego_business_setting_v1_setting_service_proto_rawDescGZIP(), []int{11}
}

func (x *ListLodgingsRequest) GetCompanyId() string {
	if x != nil {
		return x.CompanyId
	}
	return ""
}

// Response message for listing lodgings.
type ListLodgingsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// List of available lodgings
	// May be empty if no lodgings are defined
	Lodgings      []*Lodging `protobuf:"bytes,1,rep,name=lodgings,proto3" json:"lodgings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLodgingsResponse) Reset() {
	*x = ListLodgingsResponse{}
	mi := &file_moego_business_setting_v1_setting_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLodgingsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLodgingsResponse) ProtoMessage() {}

func (x *ListLodgingsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_moego_business_setting_v1_setting_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLodgingsResponse.ProtoReflect.Descriptor instead.
func (*ListLodgingsResponse) Descriptor() ([]byte, []int) {
	return file_moego_business_setting_v1_setting_service_proto_rawDescGZIP(), []int{12}
}

func (x *ListLodgingsResponse) GetLodgings() []*Lodging {
	if x != nil {
		return x.Lodgings
	}
	return nil
}

// Request message for listing lead lifecycle stages.
type ListLeadsLifeCyclesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID of the company to list lead lifecycle stages for
	// Required. Must be a valid company ID
	CompanyId     string `protobuf:"bytes,1,opt,name=company_id,json=companyId,proto3" json:"company_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLeadsLifeCyclesRequest) Reset() {
	*x = ListLeadsLifeCyclesRequest{}
	mi := &file_moego_business_setting_v1_setting_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLeadsLifeCyclesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLeadsLifeCyclesRequest) ProtoMessage() {}

func (x *ListLeadsLifeCyclesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_moego_business_setting_v1_setting_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLeadsLifeCyclesRequest.ProtoReflect.Descriptor instead.
func (*ListLeadsLifeCyclesRequest) Descriptor() ([]byte, []int) {
	return file_moego_business_setting_v1_setting_service_proto_rawDescGZIP(), []int{13}
}

func (x *ListLeadsLifeCyclesRequest) GetCompanyId() string {
	if x != nil {
		return x.CompanyId
	}
	return ""
}

// Response message for listing lead lifecycle stages.
type ListLeadsLifeCyclesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// List of available lead lifecycle stages
	// May be empty if no lifecycle stages are defined
	LifeCycles    []*LifeCycle `protobuf:"bytes,1,rep,name=life_cycles,json=lifeCycles,proto3" json:"life_cycles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLeadsLifeCyclesResponse) Reset() {
	*x = ListLeadsLifeCyclesResponse{}
	mi := &file_moego_business_setting_v1_setting_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLeadsLifeCyclesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLeadsLifeCyclesResponse) ProtoMessage() {}

func (x *ListLeadsLifeCyclesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_moego_business_setting_v1_setting_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLeadsLifeCyclesResponse.ProtoReflect.Descriptor instead.
func (*ListLeadsLifeCyclesResponse) Descriptor() ([]byte, []int) {
	return file_moego_business_setting_v1_setting_service_proto_rawDescGZIP(), []int{14}
}

func (x *ListLeadsLifeCyclesResponse) GetLifeCycles() []*LifeCycle {
	if x != nil {
		return x.LifeCycles
	}
	return nil
}

// Request message for listing lead action statuses.
type ListLeadsActionStatusRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID of the company to list lead action statuses for
	// Required. Must be a valid company ID
	CompanyId     string `protobuf:"bytes,1,opt,name=company_id,json=companyId,proto3" json:"company_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLeadsActionStatusRequest) Reset() {
	*x = ListLeadsActionStatusRequest{}
	mi := &file_moego_business_setting_v1_setting_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLeadsActionStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLeadsActionStatusRequest) ProtoMessage() {}

func (x *ListLeadsActionStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_moego_business_setting_v1_setting_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLeadsActionStatusRequest.ProtoReflect.Descriptor instead.
func (*ListLeadsActionStatusRequest) Descriptor() ([]byte, []int) {
	return file_moego_business_setting_v1_setting_service_proto_rawDescGZIP(), []int{15}
}

func (x *ListLeadsActionStatusRequest) GetCompanyId() string {
	if x != nil {
		return x.CompanyId
	}
	return ""
}

// Response message for listing lead action statuses.
type ListLeadsActionStatusResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// List of available lead action statuses
	// May be empty if no action statuses are defined
	ActionStatuses []*ActionStatus `protobuf:"bytes,1,rep,name=action_statuses,json=actionStatuses,proto3" json:"action_statuses,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ListLeadsActionStatusResponse) Reset() {
	*x = ListLeadsActionStatusResponse{}
	mi := &file_moego_business_setting_v1_setting_service_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLeadsActionStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLeadsActionStatusResponse) ProtoMessage() {}

func (x *ListLeadsActionStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_moego_business_setting_v1_setting_service_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLeadsActionStatusResponse.ProtoReflect.Descriptor instead.
func (*ListLeadsActionStatusResponse) Descriptor() ([]byte, []int) {
	return file_moego_business_setting_v1_setting_service_proto_rawDescGZIP(), []int{16}
}

func (x *ListLeadsActionStatusResponse) GetActionStatuses() []*ActionStatus {
	if x != nil {
		return x.ActionStatuses
	}
	return nil
}

// Filter parameters for the service list
type ListServicesRequest_Filter struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types of services to include in the results
	// Optional. If empty, returns all service types
	ItemTypes     []Service_ItemType `protobuf:"varint,1,rep,packed,name=item_types,json=itemTypes,proto3,enum=moego.business.setting.v1.Service_ItemType" json:"item_types,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListServicesRequest_Filter) Reset() {
	*x = ListServicesRequest_Filter{}
	mi := &file_moego_business_setting_v1_setting_service_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListServicesRequest_Filter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListServicesRequest_Filter) ProtoMessage() {}

func (x *ListServicesRequest_Filter) ProtoReflect() protoreflect.Message {
	mi := &file_moego_business_setting_v1_setting_service_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListServicesRequest_Filter.ProtoReflect.Descriptor instead.
func (*ListServicesRequest_Filter) Descriptor() ([]byte, []int) {
	return file_moego_business_setting_v1_setting_service_proto_rawDescGZIP(), []int{6, 0}
}

func (x *ListServicesRequest_Filter) GetItemTypes() []Service_ItemType {
	if x != nil {
		return x.ItemTypes
	}
	return nil
}

var File_moego_business_setting_v1_setting_service_proto protoreflect.FileDescriptor

const file_moego_business_setting_v1_setting_service_proto_rawDesc = "" +
	"\n" +
	"/moego/business/setting/v1/setting_service.proto\x12\x19moego.business.setting.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a(moego/business/setting/v1/customer.proto\x1a#moego/business/setting/v1/pet.proto\x1a'moego/business/setting/v1/lodging.proto\x1a'moego/business/setting/v1/service.proto\x1a moego/common/v1/pagination.proto\x1a\x17google/type/money.proto\"9\n" +
	"\x13ListPetCodesRequest\x12\"\n" +
	"\n" +
	"company_id\x18\x01 \x01(\tB\x03\xe0A\x02R\tcompanyId\"P\n" +
	"\x14ListPetCodesResponse\x128\n" +
	"\x05codes\x18\x01 \x03(\v2\".moego.business.setting.v1.PetCodeR\x05codes\"=\n" +
	"\x17ListCustomerTagsRequest\x12\"\n" +
	"\n" +
	"company_id\x18\x01 \x01(\tB\x03\xe0A\x02R\tcompanyId\"V\n" +
	"\x18ListCustomerTagsResponse\x12:\n" +
	"\x04tags\x18\x01 \x03(\v2&.moego.business.setting.v1.CustomerTagR\x04tags\"H\n" +
	"\"ListCustomerReferralSourcesRequest\x12\"\n" +
	"\n" +
	"company_id\x18\x01 \x01(\tB\x03\xe0A\x02R\tcompanyId\"{\n" +
	"#ListCustomerReferralSourcesResponse\x12T\n" +
	"\x10referral_sources\x18\x01 \x03(\v2).moego.business.setting.v1.ReferralSourceR\x0freferralSources\"\xc8\x02\n" +
	"\x13ListServicesRequest\x12\"\n" +
	"\n" +
	"company_id\x18\x01 \x01(\tB\x03\xe0A\x02R\tcompanyId\x12@\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x1b.moego.common.v1.PaginationB\x03\xe0A\x02R\n" +
	"pagination\x12!\n" +
	"\fbusiness_ids\x18\x03 \x03(\tR\vbusinessIds\x12M\n" +
	"\x06filter\x18\x04 \x01(\v25.moego.business.setting.v1.ListServicesRequest.FilterR\x06filter\x1aY\n" +
	"\x06Filter\x12O\n" +
	"\n" +
	"item_types\x18\x01 \x03(\x0e2+.moego.business.setting.v1.Service.ItemTypeB\x03\xe0A\x01R\titemTypes\"~\n" +
	"\x14ListServicesResponse\x12&\n" +
	"\x0fnext_page_token\x18\x01 \x01(\tR\rnextPageToken\x12>\n" +
	"\bservices\x18\x02 \x03(\v2\".moego.business.setting.v1.ServiceR\bservices\"L\n" +
	"\x11GetServiceRequest\x12\"\n" +
	"\n" +
	"company_id\x18\x01 \x01(\tB\x03\xe0A\x02R\tcompanyId\x12\x13\n" +
	"\x02id\x18\x02 \x01(\tB\x03\xe0A\x02R\x02id\"\xc3\x04\n" +
	"\x14CreateServiceRequest\x12\"\n" +
	"\n" +
	"company_id\x18\x01 \x01(\tB\x03\xe0A\x02R\tcompanyId\x12\x17\n" +
	"\x04name\x18\x02 \x01(\tB\x03\xe0A\x02R\x04name\x12!\n" +
	"\fbusiness_ids\x18\x03 \x03(\tR\vbusinessIds\x12\\\n" +
	"\x11service_item_type\x18\x04 \x01(\x0e2+.moego.business.setting.v1.Service.ItemTypeB\x03\xe0A\x02R\x0fserviceItemType\x12-\n" +
	"\x05price\x18\x05 \x01(\v2\x12.google.type.MoneyB\x03\xe0A\x02R\x05price\x12O\n" +
	"\fservice_type\x18\x06 \x01(\x0e2'.moego.business.setting.v1.Service.TypeB\x03\xe0A\x02R\vserviceType\x12!\n" +
	"\fservice_time\x18\a \x01(\x05R\vserviceTime\x124\n" +
	"\x16available_all_business\x18\b \x01(\bR\x14availableAllBusiness\x124\n" +
	"\x16available_business_ids\x18\t \x03(\tR\x14availableBusinessIds\x12.\n" +
	"\x13available_all_staff\x18\n" +
	" \x01(\bR\x11availableAllStaff\x12.\n" +
	"\x13available_staff_ids\x18\v \x03(\tR\x11availableStaffIds\"\xc5\x03\n" +
	"\x14UpdateServiceRequest\x12\"\n" +
	"\n" +
	"company_id\x18\x01 \x01(\tB\x03\xe0A\x02R\tcompanyId\x12\x13\n" +
	"\x02id\x18\x02 \x01(\tB\x03\xe0A\x02R\x02id\x12\x17\n" +
	"\x04name\x18\x03 \x01(\tB\x03\xe0A\x02R\x04name\x12!\n" +
	"\fbusiness_ids\x18\x04 \x03(\tR\vbusinessIds\x12-\n" +
	"\x05price\x18\x05 \x01(\v2\x12.google.type.MoneyB\x03\xe0A\x02R\x05price\x12!\n" +
	"\fservice_time\x18\x06 \x01(\x05R\vserviceTime\x124\n" +
	"\x16available_all_business\x18\a \x01(\bR\x14availableAllBusiness\x124\n" +
	"\x16available_business_ids\x18\b \x03(\tR\x14availableBusinessIds\x12.\n" +
	"\x13available_all_staff\x18\t \x01(\bR\x11availableAllStaff\x12.\n" +
	"\x13available_staff_ids\x18\n" +
	" \x03(\tR\x11availableStaffIds\x12\x1a\n" +
	"\binactive\x18\v \x01(\bR\binactive\"9\n" +
	"\x13ListLodgingsRequest\x12\"\n" +
	"\n" +
	"company_id\x18\x01 \x01(\tB\x03\xe0A\x02R\tcompanyId\"V\n" +
	"\x14ListLodgingsResponse\x12>\n" +
	"\blodgings\x18\x01 \x03(\v2\".moego.business.setting.v1.LodgingR\blodgings\"@\n" +
	"\x1aListLeadsLifeCyclesRequest\x12\"\n" +
	"\n" +
	"company_id\x18\x01 \x01(\tB\x03\xe0A\x02R\tcompanyId\"d\n" +
	"\x1bListLeadsLifeCyclesResponse\x12E\n" +
	"\vlife_cycles\x18\x01 \x03(\v2$.moego.business.setting.v1.LifeCycleR\n" +
	"lifeCycles\"B\n" +
	"\x1cListLeadsActionStatusRequest\x12\"\n" +
	"\n" +
	"company_id\x18\x01 \x01(\tB\x03\xe0A\x02R\tcompanyId\"q\n" +
	"\x1dListLeadsActionStatusResponse\x12P\n" +
	"\x0faction_statuses\x18\x01 \x03(\v2'.moego.business.setting.v1.ActionStatusR\x0eactionStatuses2\xb3\x0e\n" +
	"\x0eSettingService\x12\xad\x01\n" +
	"\fListPetCodes\x12..moego.business.setting.v1.ListPetCodesRequest\x1a/.moego.business.setting.v1.ListPetCodesResponse\"<\x82\xd3\xe4\x93\x026:\x01*\"1/v1/setting/companies/{company_id}/pet/codes:list\x12\xbd\x01\n" +
	"\x10ListCustomerTags\x122.moego.business.setting.v1.ListCustomerTagsRequest\x1a3.moego.business.setting.v1.ListCustomerTagsResponse\"@\x82\xd3\xe4\x93\x02::\x01*\"5/v1/setting/companies/{company_id}/customer/tags:list\x12\xea\x01\n" +
	"\x1bListCustomerReferralSources\x12=.moego.business.setting.v1.ListCustomerReferralSourcesRequest\x1a>.moego.business.setting.v1.ListCustomerReferralSourcesResponse\"L\x82\xd3\xe4\x93\x02F:\x01*\"A/v1/setting/companies/{company_id}/customer/referral_sources:list\x12\xc2\x01\n" +
	"\x13ListLeadsLifeCycles\x125.moego.business.setting.v1.ListLeadsLifeCyclesRequest\x1a6.moego.business.setting.v1.ListLeadsLifeCyclesResponse\"<\x82\xd3\xe4\x93\x026\x124/v1/setting/companies/{company_id}/leads/life_cycles\x12\xca\x01\n" +
	"\x15ListLeadsActionStatus\x127.moego.business.setting.v1.ListLeadsActionStatusRequest\x1a8.moego.business.setting.v1.ListLeadsActionStatusResponse\">\x82\xd3\xe4\x93\x028\x126/v1/setting/companies/{company_id}/leads/action_status\x12\x98\x01\n" +
	"\n" +
	"GetService\x12,.moego.business.setting.v1.GetServiceRequest\x1a\".moego.business.setting.v1.Service\"8\x82\xd3\xe4\x93\x022\x120/v1/setting/companies/{company_id}/services/{id}\x12\xac\x01\n" +
	"\fListServices\x12..moego.business.setting.v1.ListServicesRequest\x1a/.moego.business.setting.v1.ListServicesResponse\";\x82\xd3\xe4\x93\x025:\x01*\"0/v1/setting/companies/{company_id}/services:list\x12\x9c\x01\n" +
	"\rCreateService\x12/.moego.business.setting.v1.CreateServiceRequest\x1a\".moego.business.setting.v1.Service\"6\x82\xd3\xe4\x93\x020:\x01*\"+/v1/setting/companies/{company_id}/services\x12\xa1\x01\n" +
	"\rUpdateService\x12/.moego.business.setting.v1.UpdateServiceRequest\x1a\".moego.business.setting.v1.Service\";\x82\xd3\xe4\x93\x025:\x01*\x1a0/v1/setting/companies/{company_id}/services/{id}\x12\xa4\x01\n" +
	"\fListLodgings\x12..moego.business.setting.v1.ListLodgingsRequest\x1a/.moego.business.setting.v1.ListLodgingsResponse\"3\x82\xd3\xe4\x93\x02-\x12+/v1/setting/companies/{company_id}/lodgingsB\x8a\x01\n" +
	"!com.moego.api.business.setting.v1B\fSettingProtoP\x01ZUgithub.com/MoeGolibrary/moegoapis/genproto/go/business/setting/v1/settingpb;settingpbb\x06proto3"

var (
	file_moego_business_setting_v1_setting_service_proto_rawDescOnce sync.Once
	file_moego_business_setting_v1_setting_service_proto_rawDescData []byte
)

func file_moego_business_setting_v1_setting_service_proto_rawDescGZIP() []byte {
	file_moego_business_setting_v1_setting_service_proto_rawDescOnce.Do(func() {
		file_moego_business_setting_v1_setting_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_moego_business_setting_v1_setting_service_proto_rawDesc), len(file_moego_business_setting_v1_setting_service_proto_rawDesc)))
	})
	return file_moego_business_setting_v1_setting_service_proto_rawDescData
}

var file_moego_business_setting_v1_setting_service_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_moego_business_setting_v1_setting_service_proto_goTypes = []any{
	(*ListPetCodesRequest)(nil),                 // 0: moego.business.setting.v1.ListPetCodesRequest
	(*ListPetCodesResponse)(nil),                // 1: moego.business.setting.v1.ListPetCodesResponse
	(*ListCustomerTagsRequest)(nil),             // 2: moego.business.setting.v1.ListCustomerTagsRequest
	(*ListCustomerTagsResponse)(nil),            // 3: moego.business.setting.v1.ListCustomerTagsResponse
	(*ListCustomerReferralSourcesRequest)(nil),  // 4: moego.business.setting.v1.ListCustomerReferralSourcesRequest
	(*ListCustomerReferralSourcesResponse)(nil), // 5: moego.business.setting.v1.ListCustomerReferralSourcesResponse
	(*ListServicesRequest)(nil),                 // 6: moego.business.setting.v1.ListServicesRequest
	(*ListServicesResponse)(nil),                // 7: moego.business.setting.v1.ListServicesResponse
	(*GetServiceRequest)(nil),                   // 8: moego.business.setting.v1.GetServiceRequest
	(*CreateServiceRequest)(nil),                // 9: moego.business.setting.v1.CreateServiceRequest
	(*UpdateServiceRequest)(nil),                // 10: moego.business.setting.v1.UpdateServiceRequest
	(*ListLodgingsRequest)(nil),                 // 11: moego.business.setting.v1.ListLodgingsRequest
	(*ListLodgingsResponse)(nil),                // 12: moego.business.setting.v1.ListLodgingsResponse
	(*ListLeadsLifeCyclesRequest)(nil),          // 13: moego.business.setting.v1.ListLeadsLifeCyclesRequest
	(*ListLeadsLifeCyclesResponse)(nil),         // 14: moego.business.setting.v1.ListLeadsLifeCyclesResponse
	(*ListLeadsActionStatusRequest)(nil),        // 15: moego.business.setting.v1.ListLeadsActionStatusRequest
	(*ListLeadsActionStatusResponse)(nil),       // 16: moego.business.setting.v1.ListLeadsActionStatusResponse
	(*ListServicesRequest_Filter)(nil),          // 17: moego.business.setting.v1.ListServicesRequest.Filter
	(*PetCode)(nil),                             // 18: moego.business.setting.v1.PetCode
	(*CustomerTag)(nil),                         // 19: moego.business.setting.v1.CustomerTag
	(*ReferralSource)(nil),                      // 20: moego.business.setting.v1.ReferralSource
	(*commonpb.Pagination)(nil),                 // 21: moego.common.v1.Pagination
	(*Service)(nil),                             // 22: moego.business.setting.v1.Service
	(Service_ItemType)(0),                       // 23: moego.business.setting.v1.Service.ItemType
	(*money.Money)(nil),                         // 24: google.type.Money
	(Service_Type)(0),                           // 25: moego.business.setting.v1.Service.Type
	(*Lodging)(nil),                             // 26: moego.business.setting.v1.Lodging
	(*LifeCycle)(nil),                           // 27: moego.business.setting.v1.LifeCycle
	(*ActionStatus)(nil),                        // 28: moego.business.setting.v1.ActionStatus
}
var file_moego_business_setting_v1_setting_service_proto_depIdxs = []int32{
	18, // 0: moego.business.setting.v1.ListPetCodesResponse.codes:type_name -> moego.business.setting.v1.PetCode
	19, // 1: moego.business.setting.v1.ListCustomerTagsResponse.tags:type_name -> moego.business.setting.v1.CustomerTag
	20, // 2: moego.business.setting.v1.ListCustomerReferralSourcesResponse.referral_sources:type_name -> moego.business.setting.v1.ReferralSource
	21, // 3: moego.business.setting.v1.ListServicesRequest.pagination:type_name -> moego.common.v1.Pagination
	17, // 4: moego.business.setting.v1.ListServicesRequest.filter:type_name -> moego.business.setting.v1.ListServicesRequest.Filter
	22, // 5: moego.business.setting.v1.ListServicesResponse.services:type_name -> moego.business.setting.v1.Service
	23, // 6: moego.business.setting.v1.CreateServiceRequest.service_item_type:type_name -> moego.business.setting.v1.Service.ItemType
	24, // 7: moego.business.setting.v1.CreateServiceRequest.price:type_name -> google.type.Money
	25, // 8: moego.business.setting.v1.CreateServiceRequest.service_type:type_name -> moego.business.setting.v1.Service.Type
	24, // 9: moego.business.setting.v1.UpdateServiceRequest.price:type_name -> google.type.Money
	26, // 10: moego.business.setting.v1.ListLodgingsResponse.lodgings:type_name -> moego.business.setting.v1.Lodging
	27, // 11: moego.business.setting.v1.ListLeadsLifeCyclesResponse.life_cycles:type_name -> moego.business.setting.v1.LifeCycle
	28, // 12: moego.business.setting.v1.ListLeadsActionStatusResponse.action_statuses:type_name -> moego.business.setting.v1.ActionStatus
	23, // 13: moego.business.setting.v1.ListServicesRequest.Filter.item_types:type_name -> moego.business.setting.v1.Service.ItemType
	0,  // 14: moego.business.setting.v1.SettingService.ListPetCodes:input_type -> moego.business.setting.v1.ListPetCodesRequest
	2,  // 15: moego.business.setting.v1.SettingService.ListCustomerTags:input_type -> moego.business.setting.v1.ListCustomerTagsRequest
	4,  // 16: moego.business.setting.v1.SettingService.ListCustomerReferralSources:input_type -> moego.business.setting.v1.ListCustomerReferralSourcesRequest
	13, // 17: moego.business.setting.v1.SettingService.ListLeadsLifeCycles:input_type -> moego.business.setting.v1.ListLeadsLifeCyclesRequest
	15, // 18: moego.business.setting.v1.SettingService.ListLeadsActionStatus:input_type -> moego.business.setting.v1.ListLeadsActionStatusRequest
	8,  // 19: moego.business.setting.v1.SettingService.GetService:input_type -> moego.business.setting.v1.GetServiceRequest
	6,  // 20: moego.business.setting.v1.SettingService.ListServices:input_type -> moego.business.setting.v1.ListServicesRequest
	9,  // 21: moego.business.setting.v1.SettingService.CreateService:input_type -> moego.business.setting.v1.CreateServiceRequest
	10, // 22: moego.business.setting.v1.SettingService.UpdateService:input_type -> moego.business.setting.v1.UpdateServiceRequest
	11, // 23: moego.business.setting.v1.SettingService.ListLodgings:input_type -> moego.business.setting.v1.ListLodgingsRequest
	1,  // 24: moego.business.setting.v1.SettingService.ListPetCodes:output_type -> moego.business.setting.v1.ListPetCodesResponse
	3,  // 25: moego.business.setting.v1.SettingService.ListCustomerTags:output_type -> moego.business.setting.v1.ListCustomerTagsResponse
	5,  // 26: moego.business.setting.v1.SettingService.ListCustomerReferralSources:output_type -> moego.business.setting.v1.ListCustomerReferralSourcesResponse
	14, // 27: moego.business.setting.v1.SettingService.ListLeadsLifeCycles:output_type -> moego.business.setting.v1.ListLeadsLifeCyclesResponse
	16, // 28: moego.business.setting.v1.SettingService.ListLeadsActionStatus:output_type -> moego.business.setting.v1.ListLeadsActionStatusResponse
	22, // 29: moego.business.setting.v1.SettingService.GetService:output_type -> moego.business.setting.v1.Service
	7,  // 30: moego.business.setting.v1.SettingService.ListServices:output_type -> moego.business.setting.v1.ListServicesResponse
	22, // 31: moego.business.setting.v1.SettingService.CreateService:output_type -> moego.business.setting.v1.Service
	22, // 32: moego.business.setting.v1.SettingService.UpdateService:output_type -> moego.business.setting.v1.Service
	12, // 33: moego.business.setting.v1.SettingService.ListLodgings:output_type -> moego.business.setting.v1.ListLodgingsResponse
	24, // [24:34] is the sub-list for method output_type
	14, // [14:24] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_moego_business_setting_v1_setting_service_proto_init() }
func file_moego_business_setting_v1_setting_service_proto_init() {
	if File_moego_business_setting_v1_setting_service_proto != nil {
		return
	}
	file_moego_business_setting_v1_customer_proto_init()
	file_moego_business_setting_v1_pet_proto_init()
	file_moego_business_setting_v1_lodging_proto_init()
	file_moego_business_setting_v1_service_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_moego_business_setting_v1_setting_service_proto_rawDesc), len(file_moego_business_setting_v1_setting_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_moego_business_setting_v1_setting_service_proto_goTypes,
		DependencyIndexes: file_moego_business_setting_v1_setting_service_proto_depIdxs,
		MessageInfos:      file_moego_business_setting_v1_setting_service_proto_msgTypes,
	}.Build()
	File_moego_business_setting_v1_setting_service_proto = out.File
	file_moego_business_setting_v1_setting_service_proto_goTypes = nil
	file_moego_business_setting_v1_setting_service_proto_depIdxs = nil
}
