// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: moego/business/order/v1/order_service.proto

package orderpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	OrderService_GetOrder_FullMethodName                = "/moego.business.order.v1.OrderService/GetOrder"
	OrderService_ListOrders_FullMethodName              = "/moego.business.order.v1.OrderService/ListOrders"
	OrderService_ListOrderLineItems_FullMethodName      = "/moego.business.order.v1.OrderService/ListOrderLineItems"
	OrderService_ListOrderDiscounts_FullMethodName      = "/moego.business.order.v1.OrderService/ListOrderDiscounts"
	OrderService_ListOrderRedeemPackages_FullMethodName = "/moego.business.order.v1.OrderService/ListOrderRedeemPackages"
)

// OrderServiceClient is the client API for OrderService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// OrderService provides methods for managing orders and their line items.
// This service handles the creation, retrieval, and listing of orders and
// their associated items. It supports filtering and pagination for efficient
// data access and reporting.
type OrderServiceClient interface {
	// Retrieves detailed information about a specific order.
	//
	// Returns the complete order object including status, amounts, and timestamps.
	// This information is used for order processing, financial reporting, and
	// customer service inquiries.
	//
	// Returns NOT_FOUND if the order ID doesn't exist.
	// Returns PERMISSION_DENIED if the caller lacks access rights.
	GetOrder(ctx context.Context, in *GetOrderRequest, opts ...grpc.CallOption) (*Order, error)
	// Lists orders matching the specified criteria.
	//
	// Results are paginated and can be filtered by business location, status,
	// and update time. This method is typically used for order management,
	// financial reporting, and reconciliation.
	//
	// Returns an empty list if no orders match the criteria.
	// Returns PERMISSION_DENIED if the caller lacks access rights.
	ListOrders(ctx context.Context, in *ListOrdersRequest, opts ...grpc.CallOption) (*ListOrdersResponse, error)
	// Lists line items matching the specified criteria.
	//
	// Retrieves detailed information about individual items within orders.
	// This method is useful for itemized reporting and revenue analysis.
	//
	// Returns an empty list if no line items match the criteria.
	// Returns PERMISSION_DENIED if the caller lacks access rights.
	ListOrderLineItems(ctx context.Context, in *ListOrderLineItemsRequest, opts ...grpc.CallOption) (*ListOrderLineItemsResponse, error)
	// Lists discounts matching the specified criteria.
	//
	// Retrieves detailed information about discounts applied to orders or order line items.
	// This method is useful for discount reporting and analysis.
	//
	// Returns an empty list if no discounts match the criteria.
	// Returns PERMISSION_DENIED if the caller lacks access rights.
	ListOrderDiscounts(ctx context.Context, in *ListOrderDiscountsRequest, opts ...grpc.CallOption) (*ListOrderDiscountsResponse, error)
	// Lists redeemed packages that have been applied to orders.
	//
	// Retrieves detailed information about packages that have been redeemed and applied
	// to specific orders. This method is useful for tracking package usage and reporting.
	//
	// Returns an empty list if no redeemed packages match the criteria.
	// Returns PERMISSION_DENIED if the caller lacks access rights.
	ListOrderRedeemPackages(ctx context.Context, in *ListOrderRedeemPackagesRequest, opts ...grpc.CallOption) (*ListOrderRedeemPackagesResponse, error)
}

type orderServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewOrderServiceClient(cc grpc.ClientConnInterface) OrderServiceClient {
	return &orderServiceClient{cc}
}

func (c *orderServiceClient) GetOrder(ctx context.Context, in *GetOrderRequest, opts ...grpc.CallOption) (*Order, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Order)
	err := c.cc.Invoke(ctx, OrderService_GetOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderServiceClient) ListOrders(ctx context.Context, in *ListOrdersRequest, opts ...grpc.CallOption) (*ListOrdersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListOrdersResponse)
	err := c.cc.Invoke(ctx, OrderService_ListOrders_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderServiceClient) ListOrderLineItems(ctx context.Context, in *ListOrderLineItemsRequest, opts ...grpc.CallOption) (*ListOrderLineItemsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListOrderLineItemsResponse)
	err := c.cc.Invoke(ctx, OrderService_ListOrderLineItems_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderServiceClient) ListOrderDiscounts(ctx context.Context, in *ListOrderDiscountsRequest, opts ...grpc.CallOption) (*ListOrderDiscountsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListOrderDiscountsResponse)
	err := c.cc.Invoke(ctx, OrderService_ListOrderDiscounts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderServiceClient) ListOrderRedeemPackages(ctx context.Context, in *ListOrderRedeemPackagesRequest, opts ...grpc.CallOption) (*ListOrderRedeemPackagesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListOrderRedeemPackagesResponse)
	err := c.cc.Invoke(ctx, OrderService_ListOrderRedeemPackages_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OrderServiceServer is the server API for OrderService service.
// All implementations must embed UnimplementedOrderServiceServer
// for forward compatibility.
//
// OrderService provides methods for managing orders and their line items.
// This service handles the creation, retrieval, and listing of orders and
// their associated items. It supports filtering and pagination for efficient
// data access and reporting.
type OrderServiceServer interface {
	// Retrieves detailed information about a specific order.
	//
	// Returns the complete order object including status, amounts, and timestamps.
	// This information is used for order processing, financial reporting, and
	// customer service inquiries.
	//
	// Returns NOT_FOUND if the order ID doesn't exist.
	// Returns PERMISSION_DENIED if the caller lacks access rights.
	GetOrder(context.Context, *GetOrderRequest) (*Order, error)
	// Lists orders matching the specified criteria.
	//
	// Results are paginated and can be filtered by business location, status,
	// and update time. This method is typically used for order management,
	// financial reporting, and reconciliation.
	//
	// Returns an empty list if no orders match the criteria.
	// Returns PERMISSION_DENIED if the caller lacks access rights.
	ListOrders(context.Context, *ListOrdersRequest) (*ListOrdersResponse, error)
	// Lists line items matching the specified criteria.
	//
	// Retrieves detailed information about individual items within orders.
	// This method is useful for itemized reporting and revenue analysis.
	//
	// Returns an empty list if no line items match the criteria.
	// Returns PERMISSION_DENIED if the caller lacks access rights.
	ListOrderLineItems(context.Context, *ListOrderLineItemsRequest) (*ListOrderLineItemsResponse, error)
	// Lists discounts matching the specified criteria.
	//
	// Retrieves detailed information about discounts applied to orders or order line items.
	// This method is useful for discount reporting and analysis.
	//
	// Returns an empty list if no discounts match the criteria.
	// Returns PERMISSION_DENIED if the caller lacks access rights.
	ListOrderDiscounts(context.Context, *ListOrderDiscountsRequest) (*ListOrderDiscountsResponse, error)
	// Lists redeemed packages that have been applied to orders.
	//
	// Retrieves detailed information about packages that have been redeemed and applied
	// to specific orders. This method is useful for tracking package usage and reporting.
	//
	// Returns an empty list if no redeemed packages match the criteria.
	// Returns PERMISSION_DENIED if the caller lacks access rights.
	ListOrderRedeemPackages(context.Context, *ListOrderRedeemPackagesRequest) (*ListOrderRedeemPackagesResponse, error)
	mustEmbedUnimplementedOrderServiceServer()
}

// UnimplementedOrderServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOrderServiceServer struct{}

func (UnimplementedOrderServiceServer) GetOrder(context.Context, *GetOrderRequest) (*Order, error) {
	return nil, status.Error(codes.Unimplemented, "method GetOrder not implemented")
}
func (UnimplementedOrderServiceServer) ListOrders(context.Context, *ListOrdersRequest) (*ListOrdersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListOrders not implemented")
}
func (UnimplementedOrderServiceServer) ListOrderLineItems(context.Context, *ListOrderLineItemsRequest) (*ListOrderLineItemsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListOrderLineItems not implemented")
}
func (UnimplementedOrderServiceServer) ListOrderDiscounts(context.Context, *ListOrderDiscountsRequest) (*ListOrderDiscountsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListOrderDiscounts not implemented")
}
func (UnimplementedOrderServiceServer) ListOrderRedeemPackages(context.Context, *ListOrderRedeemPackagesRequest) (*ListOrderRedeemPackagesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListOrderRedeemPackages not implemented")
}
func (UnimplementedOrderServiceServer) mustEmbedUnimplementedOrderServiceServer() {}
func (UnimplementedOrderServiceServer) testEmbeddedByValue()                      {}

// UnsafeOrderServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OrderServiceServer will
// result in compilation errors.
type UnsafeOrderServiceServer interface {
	mustEmbedUnimplementedOrderServiceServer()
}

func RegisterOrderServiceServer(s grpc.ServiceRegistrar, srv OrderServiceServer) {
	// If the following call panics, it indicates UnimplementedOrderServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&OrderService_ServiceDesc, srv)
}

func _OrderService_GetOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServiceServer).GetOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderService_GetOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServiceServer).GetOrder(ctx, req.(*GetOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderService_ListOrders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListOrdersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServiceServer).ListOrders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderService_ListOrders_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServiceServer).ListOrders(ctx, req.(*ListOrdersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderService_ListOrderLineItems_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListOrderLineItemsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServiceServer).ListOrderLineItems(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderService_ListOrderLineItems_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServiceServer).ListOrderLineItems(ctx, req.(*ListOrderLineItemsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderService_ListOrderDiscounts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListOrderDiscountsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServiceServer).ListOrderDiscounts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderService_ListOrderDiscounts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServiceServer).ListOrderDiscounts(ctx, req.(*ListOrderDiscountsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderService_ListOrderRedeemPackages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListOrderRedeemPackagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServiceServer).ListOrderRedeemPackages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderService_ListOrderRedeemPackages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServiceServer).ListOrderRedeemPackages(ctx, req.(*ListOrderRedeemPackagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// OrderService_ServiceDesc is the grpc.ServiceDesc for OrderService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OrderService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "moego.business.order.v1.OrderService",
	HandlerType: (*OrderServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetOrder",
			Handler:    _OrderService_GetOrder_Handler,
		},
		{
			MethodName: "ListOrders",
			Handler:    _OrderService_ListOrders_Handler,
		},
		{
			MethodName: "ListOrderLineItems",
			Handler:    _OrderService_ListOrderLineItems_Handler,
		},
		{
			MethodName: "ListOrderDiscounts",
			Handler:    _OrderService_ListOrderDiscounts_Handler,
		},
		{
			MethodName: "ListOrderRedeemPackages",
			Handler:    _OrderService_ListOrderRedeemPackages_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "moego/business/order/v1/order_service.proto",
}
