// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        (unknown)
// source: moego/business/order/v1/order_service.proto

package orderpb

import (
	commonpb "github.com/MoeGolibrary/moegoapis/genproto/go/common/v1/commonpb"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	interval "google.golang.org/genproto/googleapis/type/interval"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request message for listing orders.
type ListOrdersRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Pagination parameters for the request
	// Required. Defines page size and token for continuation
	Pagination *commonpb.Pagination `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
	// ID of the company to list orders for
	// Required. Must be a valid company ID
	CompanyId string `protobuf:"bytes,2,opt,name=company_id,json=companyId,proto3" json:"company_id,omitempty"`
	// List of business locations to filter orders by
	// Required. Must be valid business IDs within the company
	BusinessIds []string `protobuf:"bytes,3,rep,name=business_ids,json=businessIds,proto3" json:"business_ids,omitempty"`
	// Optional filters to apply to the order list
	Filter        *ListOrdersRequest_Filter `protobuf:"bytes,4,opt,name=filter,proto3" json:"filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOrdersRequest) Reset() {
	*x = ListOrdersRequest{}
	mi := &file_moego_business_order_v1_order_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOrdersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOrdersRequest) ProtoMessage() {}

func (x *ListOrdersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_moego_business_order_v1_order_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOrdersRequest.ProtoReflect.Descriptor instead.
func (*ListOrdersRequest) Descriptor() ([]byte, []int) {
	return file_moego_business_order_v1_order_service_proto_rawDescGZIP(), []int{0}
}

func (x *ListOrdersRequest) GetPagination() *commonpb.Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *ListOrdersRequest) GetCompanyId() string {
	if x != nil {
		return x.CompanyId
	}
	return ""
}

func (x *ListOrdersRequest) GetBusinessIds() []string {
	if x != nil {
		return x.BusinessIds
	}
	return nil
}

func (x *ListOrdersRequest) GetFilter() *ListOrdersRequest_Filter {
	if x != nil {
		return x.Filter
	}
	return nil
}

// Response message for listing orders.
type ListOrdersResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Token for retrieving the next page of results
	// Empty if there are no more results
	NextPageToken string `protobuf:"bytes,1,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	// List of orders matching the request criteria
	// May be empty if no orders match
	Orders        []*Order `protobuf:"bytes,2,rep,name=orders,proto3" json:"orders,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOrdersResponse) Reset() {
	*x = ListOrdersResponse{}
	mi := &file_moego_business_order_v1_order_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOrdersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOrdersResponse) ProtoMessage() {}

func (x *ListOrdersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_moego_business_order_v1_order_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOrdersResponse.ProtoReflect.Descriptor instead.
func (*ListOrdersResponse) Descriptor() ([]byte, []int) {
	return file_moego_business_order_v1_order_service_proto_rawDescGZIP(), []int{1}
}

func (x *ListOrdersResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

func (x *ListOrdersResponse) GetOrders() []*Order {
	if x != nil {
		return x.Orders
	}
	return nil
}

// Request message for retrieving a specific order.
type GetOrderRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique identifier of the order to retrieve
	// Required. Format: "ord_" followed by random characters
	Id            string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderRequest) Reset() {
	*x = GetOrderRequest{}
	mi := &file_moego_business_order_v1_order_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderRequest) ProtoMessage() {}

func (x *GetOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_moego_business_order_v1_order_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderRequest.ProtoReflect.Descriptor instead.
func (*GetOrderRequest) Descriptor() ([]byte, []int) {
	return file_moego_business_order_v1_order_service_proto_rawDescGZIP(), []int{2}
}

func (x *GetOrderRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// Request message for listing order line items.
type ListOrderLineItemsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID of the company to list line items for
	// Required. Must be a valid company ID
	CompanyId string `protobuf:"bytes,1,opt,name=company_id,json=companyId,proto3" json:"company_id,omitempty"`
	// Include tax information in the response
	// Optional. If true, the response will include tax details
	IncludeTax bool `protobuf:"varint,2,opt,name=include_tax,json=includeTax,proto3" json:"include_tax,omitempty"`
	// Optional filters to apply to the line item list
	Filter        *ListOrderLineItemsRequest_Filter `protobuf:"bytes,3,opt,name=filter,proto3" json:"filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOrderLineItemsRequest) Reset() {
	*x = ListOrderLineItemsRequest{}
	mi := &file_moego_business_order_v1_order_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOrderLineItemsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOrderLineItemsRequest) ProtoMessage() {}

func (x *ListOrderLineItemsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_moego_business_order_v1_order_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOrderLineItemsRequest.ProtoReflect.Descriptor instead.
func (*ListOrderLineItemsRequest) Descriptor() ([]byte, []int) {
	return file_moego_business_order_v1_order_service_proto_rawDescGZIP(), []int{3}
}

func (x *ListOrderLineItemsRequest) GetCompanyId() string {
	if x != nil {
		return x.CompanyId
	}
	return ""
}

func (x *ListOrderLineItemsRequest) GetIncludeTax() bool {
	if x != nil {
		return x.IncludeTax
	}
	return false
}

func (x *ListOrderLineItemsRequest) GetFilter() *ListOrderLineItemsRequest_Filter {
	if x != nil {
		return x.Filter
	}
	return nil
}

// Response message for listing order line items.
type ListOrderLineItemsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// List of line items matching the request criteria
	// May be empty if no items match
	OrderLineItems []*OrderLineItem `protobuf:"bytes,1,rep,name=order_line_items,json=orderLineItems,proto3" json:"order_line_items,omitempty"`
	// List of line items with tax information matching the request criteria
	// May be empty if no items match or if include_tax was false
	OrderLineItemTaxes []*OrderLineTax `protobuf:"bytes,2,rep,name=order_line_item_taxes,json=orderLineItemTaxes,proto3" json:"order_line_item_taxes,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ListOrderLineItemsResponse) Reset() {
	*x = ListOrderLineItemsResponse{}
	mi := &file_moego_business_order_v1_order_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOrderLineItemsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOrderLineItemsResponse) ProtoMessage() {}

func (x *ListOrderLineItemsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_moego_business_order_v1_order_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOrderLineItemsResponse.ProtoReflect.Descriptor instead.
func (*ListOrderLineItemsResponse) Descriptor() ([]byte, []int) {
	return file_moego_business_order_v1_order_service_proto_rawDescGZIP(), []int{4}
}

func (x *ListOrderLineItemsResponse) GetOrderLineItems() []*OrderLineItem {
	if x != nil {
		return x.OrderLineItems
	}
	return nil
}

func (x *ListOrderLineItemsResponse) GetOrderLineItemTaxes() []*OrderLineTax {
	if x != nil {
		return x.OrderLineItemTaxes
	}
	return nil
}

// Request message for listing order discounts.
type ListOrderDiscountsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID of the company to list discounts for
	// Required. Must be a valid company ID
	CompanyId string `protobuf:"bytes,1,opt,name=company_id,json=companyId,proto3" json:"company_id,omitempty"`
	// Optional filters to apply to the discount list
	Filter        *ListOrderDiscountsRequest_Filter `protobuf:"bytes,2,opt,name=filter,proto3" json:"filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOrderDiscountsRequest) Reset() {
	*x = ListOrderDiscountsRequest{}
	mi := &file_moego_business_order_v1_order_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOrderDiscountsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOrderDiscountsRequest) ProtoMessage() {}

func (x *ListOrderDiscountsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_moego_business_order_v1_order_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOrderDiscountsRequest.ProtoReflect.Descriptor instead.
func (*ListOrderDiscountsRequest) Descriptor() ([]byte, []int) {
	return file_moego_business_order_v1_order_service_proto_rawDescGZIP(), []int{5}
}

func (x *ListOrderDiscountsRequest) GetCompanyId() string {
	if x != nil {
		return x.CompanyId
	}
	return ""
}

func (x *ListOrderDiscountsRequest) GetFilter() *ListOrderDiscountsRequest_Filter {
	if x != nil {
		return x.Filter
	}
	return nil
}

// Response message for listing order discounts.
type ListOrderDiscountsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// List of discounts matching the request criteria
	// May be empty if no discounts match
	OrderDiscounts []*OrderDiscount `protobuf:"bytes,1,rep,name=order_discounts,json=orderDiscounts,proto3" json:"order_discounts,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ListOrderDiscountsResponse) Reset() {
	*x = ListOrderDiscountsResponse{}
	mi := &file_moego_business_order_v1_order_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOrderDiscountsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOrderDiscountsResponse) ProtoMessage() {}

func (x *ListOrderDiscountsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_moego_business_order_v1_order_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOrderDiscountsResponse.ProtoReflect.Descriptor instead.
func (*ListOrderDiscountsResponse) Descriptor() ([]byte, []int) {
	return file_moego_business_order_v1_order_service_proto_rawDescGZIP(), []int{6}
}

func (x *ListOrderDiscountsResponse) GetOrderDiscounts() []*OrderDiscount {
	if x != nil {
		return x.OrderDiscounts
	}
	return nil
}

// Request message for listing order redeem packages.
type ListOrderRedeemPackagesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID of the company to list redeem packages for
	// Required. Must be a valid company ID
	CompanyId string `protobuf:"bytes,1,opt,name=company_id,json=companyId,proto3" json:"company_id,omitempty"`
	// Optional filters to apply to the redeem package list
	Filter        *ListOrderRedeemPackagesRequest_Filter `protobuf:"bytes,2,opt,name=filter,proto3" json:"filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOrderRedeemPackagesRequest) Reset() {
	*x = ListOrderRedeemPackagesRequest{}
	mi := &file_moego_business_order_v1_order_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOrderRedeemPackagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOrderRedeemPackagesRequest) ProtoMessage() {}

func (x *ListOrderRedeemPackagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_moego_business_order_v1_order_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOrderRedeemPackagesRequest.ProtoReflect.Descriptor instead.
func (*ListOrderRedeemPackagesRequest) Descriptor() ([]byte, []int) {
	return file_moego_business_order_v1_order_service_proto_rawDescGZIP(), []int{7}
}

func (x *ListOrderRedeemPackagesRequest) GetCompanyId() string {
	if x != nil {
		return x.CompanyId
	}
	return ""
}

func (x *ListOrderRedeemPackagesRequest) GetFilter() *ListOrderRedeemPackagesRequest_Filter {
	if x != nil {
		return x.Filter
	}
	return nil
}

// Response message for listing order redeem packages.
type ListOrderRedeemPackagesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// List of redeem packages matching the request criteria
	// May be empty if no redeem packages match
	OrderRedeemPackages []*OrderRedeemPackage `protobuf:"bytes,1,rep,name=order_redeem_packages,json=orderRedeemPackages,proto3" json:"order_redeem_packages,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ListOrderRedeemPackagesResponse) Reset() {
	*x = ListOrderRedeemPackagesResponse{}
	mi := &file_moego_business_order_v1_order_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOrderRedeemPackagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOrderRedeemPackagesResponse) ProtoMessage() {}

func (x *ListOrderRedeemPackagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_moego_business_order_v1_order_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOrderRedeemPackagesResponse.ProtoReflect.Descriptor instead.
func (*ListOrderRedeemPackagesResponse) Descriptor() ([]byte, []int) {
	return file_moego_business_order_v1_order_service_proto_rawDescGZIP(), []int{8}
}

func (x *ListOrderRedeemPackagesResponse) GetOrderRedeemPackages() []*OrderRedeemPackage {
	if x != nil {
		return x.OrderRedeemPackages
	}
	return nil
}

// Filter parameters for the order list
type ListOrdersRequest_Filter struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Specific order IDs to retrieve
	// Optional. If provided, other filters are ignored
	Ids []string `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
	// Order statuses to include in results
	// Optional. If empty, returns orders in all statuses
	Statuses []Order_Status `protobuf:"varint,2,rep,packed,name=statuses,proto3,enum=moego.business.order.v1.Order_Status" json:"statuses,omitempty"`
	// Time range for filtering orders by last update time
	// Optional. If not provided, returns all orders
	LastUpdatedTime *interval.Interval `protobuf:"bytes,3,opt,name=last_updated_time,json=lastUpdatedTime,proto3" json:"last_updated_time,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ListOrdersRequest_Filter) Reset() {
	*x = ListOrdersRequest_Filter{}
	mi := &file_moego_business_order_v1_order_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOrdersRequest_Filter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOrdersRequest_Filter) ProtoMessage() {}

func (x *ListOrdersRequest_Filter) ProtoReflect() protoreflect.Message {
	mi := &file_moego_business_order_v1_order_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOrdersRequest_Filter.ProtoReflect.Descriptor instead.
func (*ListOrdersRequest_Filter) Descriptor() ([]byte, []int) {
	return file_moego_business_order_v1_order_service_proto_rawDescGZIP(), []int{0, 0}
}

func (x *ListOrdersRequest_Filter) GetIds() []string {
	if x != nil {
		return x.Ids
	}
	return nil
}

func (x *ListOrdersRequest_Filter) GetStatuses() []Order_Status {
	if x != nil {
		return x.Statuses
	}
	return nil
}

func (x *ListOrdersRequest_Filter) GetLastUpdatedTime() *interval.Interval {
	if x != nil {
		return x.LastUpdatedTime
	}
	return nil
}

// Filter parameters for the line item list
type ListOrderLineItemsRequest_Filter struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Specific order IDs to retrieve line items for
	// Optional. If empty, returns items from all orders
	OrderIds      []string `protobuf:"bytes,1,rep,name=order_ids,json=orderIds,proto3" json:"order_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOrderLineItemsRequest_Filter) Reset() {
	*x = ListOrderLineItemsRequest_Filter{}
	mi := &file_moego_business_order_v1_order_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOrderLineItemsRequest_Filter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOrderLineItemsRequest_Filter) ProtoMessage() {}

func (x *ListOrderLineItemsRequest_Filter) ProtoReflect() protoreflect.Message {
	mi := &file_moego_business_order_v1_order_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOrderLineItemsRequest_Filter.ProtoReflect.Descriptor instead.
func (*ListOrderLineItemsRequest_Filter) Descriptor() ([]byte, []int) {
	return file_moego_business_order_v1_order_service_proto_rawDescGZIP(), []int{3, 0}
}

func (x *ListOrderLineItemsRequest_Filter) GetOrderIds() []string {
	if x != nil {
		return x.OrderIds
	}
	return nil
}

// Filter parameters for the discount list
type ListOrderDiscountsRequest_Filter struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Specific order IDs to retrieve discounts for
	// Optional. If empty, returns discounts from all orders
	OrderIds      []string `protobuf:"bytes,1,rep,name=order_ids,json=orderIds,proto3" json:"order_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOrderDiscountsRequest_Filter) Reset() {
	*x = ListOrderDiscountsRequest_Filter{}
	mi := &file_moego_business_order_v1_order_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOrderDiscountsRequest_Filter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOrderDiscountsRequest_Filter) ProtoMessage() {}

func (x *ListOrderDiscountsRequest_Filter) ProtoReflect() protoreflect.Message {
	mi := &file_moego_business_order_v1_order_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOrderDiscountsRequest_Filter.ProtoReflect.Descriptor instead.
func (*ListOrderDiscountsRequest_Filter) Descriptor() ([]byte, []int) {
	return file_moego_business_order_v1_order_service_proto_rawDescGZIP(), []int{5, 0}
}

func (x *ListOrderDiscountsRequest_Filter) GetOrderIds() []string {
	if x != nil {
		return x.OrderIds
	}
	return nil
}

// Filter parameters for the redeem package list
type ListOrderRedeemPackagesRequest_Filter struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Specific order IDs to retrieve redeem packages for
	// Optional. If empty, returns redeem packages from all orders
	OrderIds      []string `protobuf:"bytes,1,rep,name=order_ids,json=orderIds,proto3" json:"order_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOrderRedeemPackagesRequest_Filter) Reset() {
	*x = ListOrderRedeemPackagesRequest_Filter{}
	mi := &file_moego_business_order_v1_order_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOrderRedeemPackagesRequest_Filter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOrderRedeemPackagesRequest_Filter) ProtoMessage() {}

func (x *ListOrderRedeemPackagesRequest_Filter) ProtoReflect() protoreflect.Message {
	mi := &file_moego_business_order_v1_order_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOrderRedeemPackagesRequest_Filter.ProtoReflect.Descriptor instead.
func (*ListOrderRedeemPackagesRequest_Filter) Descriptor() ([]byte, []int) {
	return file_moego_business_order_v1_order_service_proto_rawDescGZIP(), []int{7, 0}
}

func (x *ListOrderRedeemPackagesRequest_Filter) GetOrderIds() []string {
	if x != nil {
		return x.OrderIds
	}
	return nil
}

var File_moego_business_order_v1_order_service_proto protoreflect.FileDescriptor

const file_moego_business_order_v1_order_service_proto_rawDesc = "" +
	"\n" +
	"+moego/business/order/v1/order_service.proto\x12\x17moego.business.order.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x1agoogle/type/interval.proto\x1a#moego/business/order/v1/order.proto\x1a-moego/business/order/v1/order_line_item.proto\x1a,moego/business/order/v1/order_line_tax.proto\x1a,moego/business/order/v1/order_discount.proto\x1a moego/common/v1/pagination.proto\"\x9e\x03\n" +
	"\x11ListOrdersRequest\x12@\n" +
	"\n" +
	"pagination\x18\x01 \x01(\v2\x1b.moego.common.v1.PaginationB\x03\xe0A\x02R\n" +
	"pagination\x12\"\n" +
	"\n" +
	"company_id\x18\x02 \x01(\tB\x03\xe0A\x02R\tcompanyId\x12&\n" +
	"\fbusiness_ids\x18\x03 \x03(\tB\x03\xe0A\x02R\vbusinessIds\x12I\n" +
	"\x06filter\x18\x04 \x01(\v21.moego.business.order.v1.ListOrdersRequest.FilterR\x06filter\x1a\xaf\x01\n" +
	"\x06Filter\x12\x15\n" +
	"\x03ids\x18\x01 \x03(\tB\x03\xe0A\x01R\x03ids\x12F\n" +
	"\bstatuses\x18\x02 \x03(\x0e2%.moego.business.order.v1.Order.StatusB\x03\xe0A\x01R\bstatuses\x12F\n" +
	"\x11last_updated_time\x18\x03 \x01(\v2\x15.google.type.IntervalB\x03\xe0A\x01R\x0flastUpdatedTime\"t\n" +
	"\x12ListOrdersResponse\x12&\n" +
	"\x0fnext_page_token\x18\x01 \x01(\tR\rnextPageToken\x126\n" +
	"\x06orders\x18\x02 \x03(\v2\x1e.moego.business.order.v1.OrderR\x06orders\"&\n" +
	"\x0fGetOrderRequest\x12\x13\n" +
	"\x02id\x18\x01 \x01(\tB\x03\xe0A\x02R\x02id\"\xe4\x01\n" +
	"\x19ListOrderLineItemsRequest\x12\"\n" +
	"\n" +
	"company_id\x18\x01 \x01(\tB\x03\xe0A\x02R\tcompanyId\x12$\n" +
	"\vinclude_tax\x18\x02 \x01(\bB\x03\xe0A\x01R\n" +
	"includeTax\x12Q\n" +
	"\x06filter\x18\x03 \x01(\v29.moego.business.order.v1.ListOrderLineItemsRequest.FilterR\x06filter\x1a*\n" +
	"\x06Filter\x12 \n" +
	"\torder_ids\x18\x01 \x03(\tB\x03\xe0A\x01R\borderIds\"\xc8\x01\n" +
	"\x1aListOrderLineItemsResponse\x12P\n" +
	"\x10order_line_items\x18\x01 \x03(\v2&.moego.business.order.v1.OrderLineItemR\x0eorderLineItems\x12X\n" +
	"\x15order_line_item_taxes\x18\x02 \x03(\v2%.moego.business.order.v1.OrderLineTaxR\x12orderLineItemTaxes\"\xbe\x01\n" +
	"\x19ListOrderDiscountsRequest\x12\"\n" +
	"\n" +
	"company_id\x18\x01 \x01(\tB\x03\xe0A\x02R\tcompanyId\x12Q\n" +
	"\x06filter\x18\x02 \x01(\v29.moego.business.order.v1.ListOrderDiscountsRequest.FilterR\x06filter\x1a*\n" +
	"\x06Filter\x12 \n" +
	"\torder_ids\x18\x01 \x03(\tB\x03\xe0A\x01R\borderIds\"m\n" +
	"\x1aListOrderDiscountsResponse\x12O\n" +
	"\x0forder_discounts\x18\x01 \x03(\v2&.moego.business.order.v1.OrderDiscountR\x0eorderDiscounts\"\xc8\x01\n" +
	"\x1eListOrderRedeemPackagesRequest\x12\"\n" +
	"\n" +
	"company_id\x18\x01 \x01(\tB\x03\xe0A\x02R\tcompanyId\x12V\n" +
	"\x06filter\x18\x02 \x01(\v2>.moego.business.order.v1.ListOrderRedeemPackagesRequest.FilterR\x06filter\x1a*\n" +
	"\x06Filter\x12 \n" +
	"\torder_ids\x18\x01 \x03(\tB\x03\xe0A\x01R\borderIds\"\x82\x01\n" +
	"\x1fListOrderRedeemPackagesResponse\x12_\n" +
	"\x15order_redeem_packages\x18\x01 \x03(\v2+.moego.business.order.v1.OrderRedeemPackageR\x13orderRedeemPackages2\x83\x06\n" +
	"\fOrderService\x12m\n" +
	"\bGetOrder\x12(.moego.business.order.v1.GetOrderRequest\x1a\x1e.moego.business.order.v1.Order\"\x17\x82\xd3\xe4\x93\x02\x11\x12\x0f/v1/orders/{id}\x12\x81\x01\n" +
	"\n" +
	"ListOrders\x12*.moego.business.order.v1.ListOrdersRequest\x1a+.moego.business.order.v1.ListOrdersResponse\"\x1a\x82\xd3\xe4\x93\x02\x14:\x01*\"\x0f/v1/orders:list\x12\x9f\x01\n" +
	"\x12ListOrderLineItems\x122.moego.business.order.v1.ListOrderLineItemsRequest\x1a3.moego.business.order.v1.ListOrderLineItemsResponse\" \x82\xd3\xe4\x93\x02\x1a:\x01*\"\x15/v1/orders/items:list\x12\xa3\x01\n" +
	"\x12ListOrderDiscounts\x122.moego.business.order.v1.ListOrderDiscountsRequest\x1a3.moego.business.order.v1.ListOrderDiscountsResponse\"$\x82\xd3\xe4\x93\x02\x1e:\x01*\"\x19/v1/orders/discounts:list\x12\xb7\x01\n" +
	"\x17ListOrderRedeemPackages\x127.moego.business.order.v1.ListOrderRedeemPackagesRequest\x1a8.moego.business.order.v1.ListOrderRedeemPackagesResponse\")\x82\xd3\xe4\x93\x02#:\x01*\"\x1e/v1/orders/redeemPackages:listB\x80\x01\n" +
	"\x1fcom.moego.api.business.order.v1B\n" +
	"OrderProtoP\x01ZOgithub.com/MoeGolibrary/moegoapis/genproto/go/business/order/v1/orderpb;orderpbb\x06proto3"

var (
	file_moego_business_order_v1_order_service_proto_rawDescOnce sync.Once
	file_moego_business_order_v1_order_service_proto_rawDescData []byte
)

func file_moego_business_order_v1_order_service_proto_rawDescGZIP() []byte {
	file_moego_business_order_v1_order_service_proto_rawDescOnce.Do(func() {
		file_moego_business_order_v1_order_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_moego_business_order_v1_order_service_proto_rawDesc), len(file_moego_business_order_v1_order_service_proto_rawDesc)))
	})
	return file_moego_business_order_v1_order_service_proto_rawDescData
}

var file_moego_business_order_v1_order_service_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_moego_business_order_v1_order_service_proto_goTypes = []any{
	(*ListOrdersRequest)(nil),                     // 0: moego.business.order.v1.ListOrdersRequest
	(*ListOrdersResponse)(nil),                    // 1: moego.business.order.v1.ListOrdersResponse
	(*GetOrderRequest)(nil),                       // 2: moego.business.order.v1.GetOrderRequest
	(*ListOrderLineItemsRequest)(nil),             // 3: moego.business.order.v1.ListOrderLineItemsRequest
	(*ListOrderLineItemsResponse)(nil),            // 4: moego.business.order.v1.ListOrderLineItemsResponse
	(*ListOrderDiscountsRequest)(nil),             // 5: moego.business.order.v1.ListOrderDiscountsRequest
	(*ListOrderDiscountsResponse)(nil),            // 6: moego.business.order.v1.ListOrderDiscountsResponse
	(*ListOrderRedeemPackagesRequest)(nil),        // 7: moego.business.order.v1.ListOrderRedeemPackagesRequest
	(*ListOrderRedeemPackagesResponse)(nil),       // 8: moego.business.order.v1.ListOrderRedeemPackagesResponse
	(*ListOrdersRequest_Filter)(nil),              // 9: moego.business.order.v1.ListOrdersRequest.Filter
	(*ListOrderLineItemsRequest_Filter)(nil),      // 10: moego.business.order.v1.ListOrderLineItemsRequest.Filter
	(*ListOrderDiscountsRequest_Filter)(nil),      // 11: moego.business.order.v1.ListOrderDiscountsRequest.Filter
	(*ListOrderRedeemPackagesRequest_Filter)(nil), // 12: moego.business.order.v1.ListOrderRedeemPackagesRequest.Filter
	(*commonpb.Pagination)(nil),                   // 13: moego.common.v1.Pagination
	(*Order)(nil),                                 // 14: moego.business.order.v1.Order
	(*OrderLineItem)(nil),                         // 15: moego.business.order.v1.OrderLineItem
	(*OrderLineTax)(nil),                          // 16: moego.business.order.v1.OrderLineTax
	(*OrderDiscount)(nil),                         // 17: moego.business.order.v1.OrderDiscount
	(*OrderRedeemPackage)(nil),                    // 18: moego.business.order.v1.OrderRedeemPackage
	(Order_Status)(0),                             // 19: moego.business.order.v1.Order.Status
	(*interval.Interval)(nil),                     // 20: google.type.Interval
}
var file_moego_business_order_v1_order_service_proto_depIdxs = []int32{
	13, // 0: moego.business.order.v1.ListOrdersRequest.pagination:type_name -> moego.common.v1.Pagination
	9,  // 1: moego.business.order.v1.ListOrdersRequest.filter:type_name -> moego.business.order.v1.ListOrdersRequest.Filter
	14, // 2: moego.business.order.v1.ListOrdersResponse.orders:type_name -> moego.business.order.v1.Order
	10, // 3: moego.business.order.v1.ListOrderLineItemsRequest.filter:type_name -> moego.business.order.v1.ListOrderLineItemsRequest.Filter
	15, // 4: moego.business.order.v1.ListOrderLineItemsResponse.order_line_items:type_name -> moego.business.order.v1.OrderLineItem
	16, // 5: moego.business.order.v1.ListOrderLineItemsResponse.order_line_item_taxes:type_name -> moego.business.order.v1.OrderLineTax
	11, // 6: moego.business.order.v1.ListOrderDiscountsRequest.filter:type_name -> moego.business.order.v1.ListOrderDiscountsRequest.Filter
	17, // 7: moego.business.order.v1.ListOrderDiscountsResponse.order_discounts:type_name -> moego.business.order.v1.OrderDiscount
	12, // 8: moego.business.order.v1.ListOrderRedeemPackagesRequest.filter:type_name -> moego.business.order.v1.ListOrderRedeemPackagesRequest.Filter
	18, // 9: moego.business.order.v1.ListOrderRedeemPackagesResponse.order_redeem_packages:type_name -> moego.business.order.v1.OrderRedeemPackage
	19, // 10: moego.business.order.v1.ListOrdersRequest.Filter.statuses:type_name -> moego.business.order.v1.Order.Status
	20, // 11: moego.business.order.v1.ListOrdersRequest.Filter.last_updated_time:type_name -> google.type.Interval
	2,  // 12: moego.business.order.v1.OrderService.GetOrder:input_type -> moego.business.order.v1.GetOrderRequest
	0,  // 13: moego.business.order.v1.OrderService.ListOrders:input_type -> moego.business.order.v1.ListOrdersRequest
	3,  // 14: moego.business.order.v1.OrderService.ListOrderLineItems:input_type -> moego.business.order.v1.ListOrderLineItemsRequest
	5,  // 15: moego.business.order.v1.OrderService.ListOrderDiscounts:input_type -> moego.business.order.v1.ListOrderDiscountsRequest
	7,  // 16: moego.business.order.v1.OrderService.ListOrderRedeemPackages:input_type -> moego.business.order.v1.ListOrderRedeemPackagesRequest
	14, // 17: moego.business.order.v1.OrderService.GetOrder:output_type -> moego.business.order.v1.Order
	1,  // 18: moego.business.order.v1.OrderService.ListOrders:output_type -> moego.business.order.v1.ListOrdersResponse
	4,  // 19: moego.business.order.v1.OrderService.ListOrderLineItems:output_type -> moego.business.order.v1.ListOrderLineItemsResponse
	6,  // 20: moego.business.order.v1.OrderService.ListOrderDiscounts:output_type -> moego.business.order.v1.ListOrderDiscountsResponse
	8,  // 21: moego.business.order.v1.OrderService.ListOrderRedeemPackages:output_type -> moego.business.order.v1.ListOrderRedeemPackagesResponse
	17, // [17:22] is the sub-list for method output_type
	12, // [12:17] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_moego_business_order_v1_order_service_proto_init() }
func file_moego_business_order_v1_order_service_proto_init() {
	if File_moego_business_order_v1_order_service_proto != nil {
		return
	}
	file_moego_business_order_v1_order_proto_init()
	file_moego_business_order_v1_order_line_item_proto_init()
	file_moego_business_order_v1_order_line_tax_proto_init()
	file_moego_business_order_v1_order_discount_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_moego_business_order_v1_order_service_proto_rawDesc), len(file_moego_business_order_v1_order_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_moego_business_order_v1_order_service_proto_goTypes,
		DependencyIndexes: file_moego_business_order_v1_order_service_proto_depIdxs,
		MessageInfos:      file_moego_business_order_v1_order_service_proto_msgTypes,
	}.Build()
	File_moego_business_order_v1_order_service_proto = out.File
	file_moego_business_order_v1_order_service_proto_goTypes = nil
	file_moego_business_order_v1_order_service_proto_depIdxs = nil
}
