// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: moego/business/business/v1/business.proto

package businesspb

import (
	commonpb "github.com/MoeGolibrary/moegoapis/genproto/go/common/v1/commonpb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Business represents a physical or virtual location where services are provided.
// Each business location operates under a parent company and maintains its own
// staff, services, and operational settings. Business profiles include contact
// information and social media presence for customer engagement.
type Business struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique identifier for the business location
	// Format: "bus_" followed by random characters
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Display name of the business location
	// Used in customer communications and UI
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// URL to the business location's logo or image
	// Optional. Must be a valid HTTPS URL
	Avatar string `protobuf:"bytes,3,opt,name=avatar,proto3" json:"avatar,omitempty"`
	// Primary contact phone number
	// Format: E.164 format (e.g., +12125551234)
	Phone string `protobuf:"bytes,4,opt,name=phone,proto3" json:"phone,omitempty"`
	// Public business phone number
	// Format: E.164 format (e.g., +12125551234)
	BusinessPhone string `protobuf:"bytes,5,opt,name=business_phone,json=businessPhone,proto3" json:"business_phone,omitempty"`
	// Business contact email address
	// Format: Must be a valid email address
	Email string `protobuf:"bytes,6,opt,name=email,proto3" json:"email,omitempty"`
	// Physical location details
	// Required for in-person services
	Address *commonpb.Address `protobuf:"bytes,7,opt,name=address,proto3" json:"address,omitempty"`
	// Business website URL
	// Optional. Must be a valid HTTPS URL
	Website string `protobuf:"bytes,8,opt,name=website,proto3" json:"website,omitempty"`
	// Facebook page URL
	// Optional. Must be a valid Facebook page URL
	Facebook string `protobuf:"bytes,9,opt,name=facebook,proto3" json:"facebook,omitempty"`
	// Instagram profile URL
	// Optional. Must be a valid Instagram profile URL
	Instagram string `protobuf:"bytes,10,opt,name=instagram,proto3" json:"instagram,omitempty"`
	// Yelp business page URL
	// Optional. Must be a valid Yelp business URL
	Yelp string `protobuf:"bytes,11,opt,name=yelp,proto3" json:"yelp,omitempty"`
	// Google Business Profile URL
	// Optional. Must be a valid Google Business URL
	Google string `protobuf:"bytes,12,opt,name=google,proto3" json:"google,omitempty"`
	// ID of the parent company
	// Required. Must be a valid company ID
	CompanyId     string `protobuf:"bytes,13,opt,name=company_id,json=companyId,proto3" json:"company_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Business) Reset() {
	*x = Business{}
	mi := &file_moego_business_business_v1_business_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Business) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Business) ProtoMessage() {}

func (x *Business) ProtoReflect() protoreflect.Message {
	mi := &file_moego_business_business_v1_business_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Business.ProtoReflect.Descriptor instead.
func (*Business) Descriptor() ([]byte, []int) {
	return file_moego_business_business_v1_business_proto_rawDescGZIP(), []int{0}
}

func (x *Business) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Business) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Business) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *Business) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *Business) GetBusinessPhone() string {
	if x != nil {
		return x.BusinessPhone
	}
	return ""
}

func (x *Business) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Business) GetAddress() *commonpb.Address {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *Business) GetWebsite() string {
	if x != nil {
		return x.Website
	}
	return ""
}

func (x *Business) GetFacebook() string {
	if x != nil {
		return x.Facebook
	}
	return ""
}

func (x *Business) GetInstagram() string {
	if x != nil {
		return x.Instagram
	}
	return ""
}

func (x *Business) GetYelp() string {
	if x != nil {
		return x.Yelp
	}
	return ""
}

func (x *Business) GetGoogle() string {
	if x != nil {
		return x.Google
	}
	return ""
}

func (x *Business) GetCompanyId() string {
	if x != nil {
		return x.CompanyId
	}
	return ""
}

var File_moego_business_business_v1_business_proto protoreflect.FileDescriptor

const file_moego_business_business_v1_business_proto_rawDesc = "" +
	"\n" +
	")moego/business/business/v1/business.proto\x12\x1amoego.business.business.v1\x1a\x1dmoego/common/v1/address.proto\"\xec\x02\n" +
	"\bBusiness\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06avatar\x18\x03 \x01(\tR\x06avatar\x12\x14\n" +
	"\x05phone\x18\x04 \x01(\tR\x05phone\x12%\n" +
	"\x0ebusiness_phone\x18\x05 \x01(\tR\rbusinessPhone\x12\x14\n" +
	"\x05email\x18\x06 \x01(\tR\x05email\x122\n" +
	"\aaddress\x18\a \x01(\v2\x18.moego.common.v1.AddressR\aaddress\x12\x18\n" +
	"\awebsite\x18\b \x01(\tR\awebsite\x12\x1a\n" +
	"\bfacebook\x18\t \x01(\tR\bfacebook\x12\x1c\n" +
	"\tinstagram\x18\n" +
	" \x01(\tR\tinstagram\x12\x12\n" +
	"\x04yelp\x18\v \x01(\tR\x04yelp\x12\x16\n" +
	"\x06google\x18\f \x01(\tR\x06google\x12\x1d\n" +
	"\n" +
	"company_id\x18\r \x01(\tR\tcompanyIdB\x8f\x01\n" +
	"\"com.moego.api.business.business.v1B\rBusinessProtoP\x01ZXgithub.com/MoeGolibrary/moegoapis/genproto/go/business/business/v1/businesspb;businesspbb\x06proto3"

var (
	file_moego_business_business_v1_business_proto_rawDescOnce sync.Once
	file_moego_business_business_v1_business_proto_rawDescData []byte
)

func file_moego_business_business_v1_business_proto_rawDescGZIP() []byte {
	file_moego_business_business_v1_business_proto_rawDescOnce.Do(func() {
		file_moego_business_business_v1_business_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_moego_business_business_v1_business_proto_rawDesc), len(file_moego_business_business_v1_business_proto_rawDesc)))
	})
	return file_moego_business_business_v1_business_proto_rawDescData
}

var file_moego_business_business_v1_business_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_moego_business_business_v1_business_proto_goTypes = []any{
	(*Business)(nil),         // 0: moego.business.business.v1.Business
	(*commonpb.Address)(nil), // 1: moego.common.v1.Address
}
var file_moego_business_business_v1_business_proto_depIdxs = []int32{
	1, // 0: moego.business.business.v1.Business.address:type_name -> moego.common.v1.Address
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_moego_business_business_v1_business_proto_init() }
func file_moego_business_business_v1_business_proto_init() {
	if File_moego_business_business_v1_business_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_moego_business_business_v1_business_proto_rawDesc), len(file_moego_business_business_v1_business_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_moego_business_business_v1_business_proto_goTypes,
		DependencyIndexes: file_moego_business_business_v1_business_proto_depIdxs,
		MessageInfos:      file_moego_business_business_v1_business_proto_msgTypes,
	}.Build()
	File_moego_business_business_v1_business_proto = out.File
	file_moego_business_business_v1_business_proto_goTypes = nil
	file_moego_business_business_v1_business_proto_depIdxs = nil
}
