// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: moego/business/report/v1/report.proto

package reportpb

import (
	money "google.golang.org/genproto/googleapis/type/money"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Type specifies the data type and formatting rules for a field.
// This determines how values are stored, displayed, and processed.
type Field_Type int32

const (
	// Default value when type is not specified
	// Should not be used when creating new fields
	Field_TYPE_UNSPECIFIED Field_Type = 0
	// Represents monetary values with currency information
	// Uses google.type.Money for storage
	Field_MONEY Field_Type = 1
	// Represents text or string values
	// Used for names, descriptions, and other textual data
	Field_TEXT Field_Type = 2
	// Represents date values without time
	// Stored as Timestamp with time set to midnight
	Field_DATE Field_Type = 3
	// Represents time values without date
	// Stored as Timestamp with date set to epoch
	Field_TIME Field_Type = 4
	// Represents whole numbers
	// Used for counts and integer quantities
	Field_NUMBER Field_Type = 5
	// Represents numbers with decimal points
	// Used for precise numerical values
	Field_DECIMAL_NUMBER Field_Type = 6
	// Represents percentage values
	// Stored as decimal (e.g., 0.75 for 75%)
	Field_PERCENTAGE Field_Type = 7
	// Represents time duration in minutes
	// Used for service times and intervals
	Field_DURATION Field_Type = 8
	// Represents full date and time values
	// Used for exact temporal data points
	Field_DATETIME Field_Type = 9
)

// Enum value maps for Field_Type.
var (
	Field_Type_name = map[int32]string{
		0: "TYPE_UNSPECIFIED",
		1: "MONEY",
		2: "TEXT",
		3: "DATE",
		4: "TIME",
		5: "NUMBER",
		6: "DECIMAL_NUMBER",
		7: "PERCENTAGE",
		8: "DURATION",
		9: "DATETIME",
	}
	Field_Type_value = map[string]int32{
		"TYPE_UNSPECIFIED": 0,
		"MONEY":            1,
		"TEXT":             2,
		"DATE":             3,
		"TIME":             4,
		"NUMBER":           5,
		"DECIMAL_NUMBER":   6,
		"PERCENTAGE":       7,
		"DURATION":         8,
		"DATETIME":         9,
	}
)

func (x Field_Type) Enum() *Field_Type {
	p := new(Field_Type)
	*p = x
	return p
}

func (x Field_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Field_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_moego_business_report_v1_report_proto_enumTypes[0].Descriptor()
}

func (Field_Type) Type() protoreflect.EnumType {
	return &file_moego_business_report_v1_report_proto_enumTypes[0]
}

func (x Field_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Field_Type.Descriptor instead.
func (Field_Type) EnumDescriptor() ([]byte, []int) {
	return file_moego_business_report_v1_report_proto_rawDescGZIP(), []int{1, 0}
}

// Report represents a customizable business report definition.
// Reports are used to generate structured data views with configurable fields
// and formatting options. Each report can be used to analyze different aspects
// of business operations.
type Report struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique identifier for the report
	// Format: "rpt_" followed by random characters
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Display name of the report
	// Used in UI and exported documents
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Detailed description of the report's purpose and contents
	// Helps users understand what data is included
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	// List of fields included in the report
	// Defines the structure and data types of the report
	Fields        []*Field `protobuf:"bytes,4,rep,name=fields,proto3" json:"fields,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Report) Reset() {
	*x = Report{}
	mi := &file_moego_business_report_v1_report_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Report) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Report) ProtoMessage() {}

func (x *Report) ProtoReflect() protoreflect.Message {
	mi := &file_moego_business_report_v1_report_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Report.ProtoReflect.Descriptor instead.
func (*Report) Descriptor() ([]byte, []int) {
	return file_moego_business_report_v1_report_proto_rawDescGZIP(), []int{0}
}

func (x *Report) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Report) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Report) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Report) GetFields() []*Field {
	if x != nil {
		return x.Fields
	}
	return nil
}

// Field defines a single data column in a report.
// Each field has a specific data type and display properties.
// Fields can be used for grouping data and determining how values are formatted.
type Field struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Display label for the field
	// Used in report headers and UI elements
	Label string `protobuf:"bytes,1,opt,name=label,proto3" json:"label,omitempty"`
	// Data type of the field
	// Determines value formatting and validation
	Type Field_Type `protobuf:"varint,2,opt,name=type,proto3,enum=moego.business.report.v1.Field_Type" json:"type,omitempty"`
	// Unique identifier for the field within the report
	// Used to reference field values in data structures
	Key string `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
	// Whether this field can be used as a grouping criterion
	// Affects report aggregation options
	GroupByEnable bool `protobuf:"varint,4,opt,name=group_by_enable,json=groupByEnable,proto3" json:"group_by_enable,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Field) Reset() {
	*x = Field{}
	mi := &file_moego_business_report_v1_report_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Field) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Field) ProtoMessage() {}

func (x *Field) ProtoReflect() protoreflect.Message {
	mi := &file_moego_business_report_v1_report_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Field.ProtoReflect.Descriptor instead.
func (*Field) Descriptor() ([]byte, []int) {
	return file_moego_business_report_v1_report_proto_rawDescGZIP(), []int{1}
}

func (x *Field) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *Field) GetType() Field_Type {
	if x != nil {
		return x.Type
	}
	return Field_TYPE_UNSPECIFIED
}

func (x *Field) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Field) GetGroupByEnable() bool {
	if x != nil {
		return x.GroupByEnable
	}
	return false
}

// TableData represents a complete data set for a report.
// Contains both the structure (fields) and content (rows) of the report.
type TableData struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Individual data rows in the table
	// Each row contains values for all defined fields
	Rows []*TableRowData `protobuf:"bytes,1,rep,name=rows,proto3" json:"rows,omitempty"`
	// Field definitions for the table
	// Can be from TableMeta or dynamically generated
	Fields        []*Field `protobuf:"bytes,2,rep,name=fields,proto3" json:"fields,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TableData) Reset() {
	*x = TableData{}
	mi := &file_moego_business_report_v1_report_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TableData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TableData) ProtoMessage() {}

func (x *TableData) ProtoReflect() protoreflect.Message {
	mi := &file_moego_business_report_v1_report_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TableData.ProtoReflect.Descriptor instead.
func (*TableData) Descriptor() ([]byte, []int) {
	return file_moego_business_report_v1_report_proto_rawDescGZIP(), []int{2}
}

func (x *TableData) GetRows() []*TableRowData {
	if x != nil {
		return x.Rows
	}
	return nil
}

func (x *TableData) GetFields() []*Field {
	if x != nil {
		return x.Fields
	}
	return nil
}

// TableRowData represents a single row of data in a report.
// Contains values for each field defined in the table structure.
type TableRowData struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Map of field values indexed by field key
	// Each entry corresponds to a column in the report
	Data          map[string]*Data `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TableRowData) Reset() {
	*x = TableRowData{}
	mi := &file_moego_business_report_v1_report_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TableRowData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TableRowData) ProtoMessage() {}

func (x *TableRowData) ProtoReflect() protoreflect.Message {
	mi := &file_moego_business_report_v1_report_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TableRowData.ProtoReflect.Descriptor instead.
func (*TableRowData) Descriptor() ([]byte, []int) {
	return file_moego_business_report_v1_report_proto_rawDescGZIP(), []int{3}
}

func (x *TableRowData) GetData() map[string]*Data {
	if x != nil {
		return x.Data
	}
	return nil
}

// Data represents a single cell value in a report table.
// Includes both the field metadata and the actual value.
type Data struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Reference to the field definition
	// Must match a field key in the table structure
	FieldKey string `protobuf:"bytes,1,opt,name=field_key,json=fieldKey,proto3" json:"field_key,omitempty"`
	// Data type of the value
	// Must match the field definition
	FieldType Field_Type `protobuf:"varint,2,opt,name=field_type,json=fieldType,proto3,enum=moego.business.report.v1.Field_Type" json:"field_type,omitempty"`
	// Actual value of the cell
	// Type must match field_type
	Value         *Value `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Data) Reset() {
	*x = Data{}
	mi := &file_moego_business_report_v1_report_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data) ProtoMessage() {}

func (x *Data) ProtoReflect() protoreflect.Message {
	mi := &file_moego_business_report_v1_report_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data.ProtoReflect.Descriptor instead.
func (*Data) Descriptor() ([]byte, []int) {
	return file_moego_business_report_v1_report_proto_rawDescGZIP(), []int{4}
}

func (x *Data) GetFieldKey() string {
	if x != nil {
		return x.FieldKey
	}
	return ""
}

func (x *Data) GetFieldType() Field_Type {
	if x != nil {
		return x.FieldType
	}
	return Field_TYPE_UNSPECIFIED
}

func (x *Data) GetValue() *Value {
	if x != nil {
		return x.Value
	}
	return nil
}

// Value represents a typed data value used in reports.
// Supports multiple data types through a oneof field.
type Value struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The actual value in its appropriate type
	//
	// Types that are valid to be assigned to Value:
	//
	//	*Value_String_
	//	*Value_Double
	//	*Value_Int64
	//	*Value_Bool
	//	*Value_Money
	//	*Value_Timestamp
	Value         isValue_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Value) Reset() {
	*x = Value{}
	mi := &file_moego_business_report_v1_report_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Value) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Value) ProtoMessage() {}

func (x *Value) ProtoReflect() protoreflect.Message {
	mi := &file_moego_business_report_v1_report_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Value.ProtoReflect.Descriptor instead.
func (*Value) Descriptor() ([]byte, []int) {
	return file_moego_business_report_v1_report_proto_rawDescGZIP(), []int{5}
}

func (x *Value) GetValue() isValue_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *Value) GetString_() string {
	if x != nil {
		if x, ok := x.Value.(*Value_String_); ok {
			return x.String_
		}
	}
	return ""
}

func (x *Value) GetDouble() float64 {
	if x != nil {
		if x, ok := x.Value.(*Value_Double); ok {
			return x.Double
		}
	}
	return 0
}

func (x *Value) GetInt64() int64 {
	if x != nil {
		if x, ok := x.Value.(*Value_Int64); ok {
			return x.Int64
		}
	}
	return 0
}

func (x *Value) GetBool() bool {
	if x != nil {
		if x, ok := x.Value.(*Value_Bool); ok {
			return x.Bool
		}
	}
	return false
}

func (x *Value) GetMoney() *money.Money {
	if x != nil {
		if x, ok := x.Value.(*Value_Money); ok {
			return x.Money
		}
	}
	return nil
}

func (x *Value) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		if x, ok := x.Value.(*Value_Timestamp); ok {
			return x.Timestamp
		}
	}
	return nil
}

type isValue_Value interface {
	isValue_Value()
}

type Value_String_ struct {
	// Text value for string fields
	String_ string `protobuf:"bytes,2,opt,name=string,proto3,oneof"`
}

type Value_Double struct {
	// Decimal value for numerical fields
	Double float64 `protobuf:"fixed64,3,opt,name=double,proto3,oneof"`
}

type Value_Int64 struct {
	// Integer value for whole number fields
	Int64 int64 `protobuf:"varint,4,opt,name=int64,proto3,oneof"`
}

type Value_Bool struct {
	// Boolean value for true/false fields
	Bool bool `protobuf:"varint,6,opt,name=bool,proto3,oneof"`
}

type Value_Money struct {
	// Monetary value with currency information
	Money *money.Money `protobuf:"bytes,7,opt,name=money,proto3,oneof"`
}

type Value_Timestamp struct {
	// Date/time value for temporal fields
	Timestamp *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=timestamp,proto3,oneof"`
}

func (*Value_String_) isValue_Value() {}

func (*Value_Double) isValue_Value() {}

func (*Value_Int64) isValue_Value() {}

func (*Value_Bool) isValue_Value() {}

func (*Value_Money) isValue_Value() {}

func (*Value_Timestamp) isValue_Value() {}

var File_moego_business_report_v1_report_proto protoreflect.FileDescriptor

const file_moego_business_report_v1_report_proto_rawDesc = "" +
	"\n" +
	"%moego/business/report/v1/report.proto\x12\x18moego.business.report.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x17google/type/money.proto\"\x87\x01\n" +
	"\x06Report\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x127\n" +
	"\x06fields\x18\x04 \x03(\v2\x1f.moego.business.report.v1.FieldR\x06fields\"\xa5\x02\n" +
	"\x05Field\x12\x14\n" +
	"\x05label\x18\x01 \x01(\tR\x05label\x128\n" +
	"\x04type\x18\x02 \x01(\x0e2$.moego.business.report.v1.Field.TypeR\x04type\x12\x10\n" +
	"\x03key\x18\x03 \x01(\tR\x03key\x12&\n" +
	"\x0fgroup_by_enable\x18\x04 \x01(\bR\rgroupByEnable\"\x91\x01\n" +
	"\x04Type\x12\x14\n" +
	"\x10TYPE_UNSPECIFIED\x10\x00\x12\t\n" +
	"\x05MONEY\x10\x01\x12\b\n" +
	"\x04TEXT\x10\x02\x12\b\n" +
	"\x04DATE\x10\x03\x12\b\n" +
	"\x04TIME\x10\x04\x12\n" +
	"\n" +
	"\x06NUMBER\x10\x05\x12\x12\n" +
	"\x0eDECIMAL_NUMBER\x10\x06\x12\x0e\n" +
	"\n" +
	"PERCENTAGE\x10\a\x12\f\n" +
	"\bDURATION\x10\b\x12\f\n" +
	"\bDATETIME\x10\t\"\x80\x01\n" +
	"\tTableData\x12:\n" +
	"\x04rows\x18\x01 \x03(\v2&.moego.business.report.v1.TableRowDataR\x04rows\x127\n" +
	"\x06fields\x18\x02 \x03(\v2\x1f.moego.business.report.v1.FieldR\x06fields\"\xad\x01\n" +
	"\fTableRowData\x12D\n" +
	"\x04data\x18\x01 \x03(\v20.moego.business.report.v1.TableRowData.DataEntryR\x04data\x1aW\n" +
	"\tDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x124\n" +
	"\x05value\x18\x02 \x01(\v2\x1e.moego.business.report.v1.DataR\x05value:\x028\x01\"\x9f\x01\n" +
	"\x04Data\x12\x1b\n" +
	"\tfield_key\x18\x01 \x01(\tR\bfieldKey\x12C\n" +
	"\n" +
	"field_type\x18\x02 \x01(\x0e2$.moego.business.report.v1.Field.TypeR\tfieldType\x125\n" +
	"\x05value\x18\x03 \x01(\v2\x1f.moego.business.report.v1.ValueR\x05value\"\xda\x01\n" +
	"\x05Value\x12\x18\n" +
	"\x06string\x18\x02 \x01(\tH\x00R\x06string\x12\x18\n" +
	"\x06double\x18\x03 \x01(\x01H\x00R\x06double\x12\x16\n" +
	"\x05int64\x18\x04 \x01(\x03H\x00R\x05int64\x12\x14\n" +
	"\x04bool\x18\x06 \x01(\bH\x00R\x04bool\x12*\n" +
	"\x05money\x18\a \x01(\v2\x12.google.type.MoneyH\x00R\x05money\x12:\n" +
	"\ttimestamp\x18\b \x01(\v2\x1a.google.protobuf.TimestampH\x00R\ttimestampB\a\n" +
	"\x05valueB\x85\x01\n" +
	" com.moego.api.business.report.v1B\vreportProtoP\x01ZRgithub.com/MoeGolibrary/moegoapis/genproto/go/business/report/v1/reportpb;reportpbb\x06proto3"

var (
	file_moego_business_report_v1_report_proto_rawDescOnce sync.Once
	file_moego_business_report_v1_report_proto_rawDescData []byte
)

func file_moego_business_report_v1_report_proto_rawDescGZIP() []byte {
	file_moego_business_report_v1_report_proto_rawDescOnce.Do(func() {
		file_moego_business_report_v1_report_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_moego_business_report_v1_report_proto_rawDesc), len(file_moego_business_report_v1_report_proto_rawDesc)))
	})
	return file_moego_business_report_v1_report_proto_rawDescData
}

var file_moego_business_report_v1_report_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_moego_business_report_v1_report_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_moego_business_report_v1_report_proto_goTypes = []any{
	(Field_Type)(0),               // 0: moego.business.report.v1.Field.Type
	(*Report)(nil),                // 1: moego.business.report.v1.Report
	(*Field)(nil),                 // 2: moego.business.report.v1.Field
	(*TableData)(nil),             // 3: moego.business.report.v1.TableData
	(*TableRowData)(nil),          // 4: moego.business.report.v1.TableRowData
	(*Data)(nil),                  // 5: moego.business.report.v1.Data
	(*Value)(nil),                 // 6: moego.business.report.v1.Value
	nil,                           // 7: moego.business.report.v1.TableRowData.DataEntry
	(*money.Money)(nil),           // 8: google.type.Money
	(*timestamppb.Timestamp)(nil), // 9: google.protobuf.Timestamp
}
var file_moego_business_report_v1_report_proto_depIdxs = []int32{
	2,  // 0: moego.business.report.v1.Report.fields:type_name -> moego.business.report.v1.Field
	0,  // 1: moego.business.report.v1.Field.type:type_name -> moego.business.report.v1.Field.Type
	4,  // 2: moego.business.report.v1.TableData.rows:type_name -> moego.business.report.v1.TableRowData
	2,  // 3: moego.business.report.v1.TableData.fields:type_name -> moego.business.report.v1.Field
	7,  // 4: moego.business.report.v1.TableRowData.data:type_name -> moego.business.report.v1.TableRowData.DataEntry
	0,  // 5: moego.business.report.v1.Data.field_type:type_name -> moego.business.report.v1.Field.Type
	6,  // 6: moego.business.report.v1.Data.value:type_name -> moego.business.report.v1.Value
	8,  // 7: moego.business.report.v1.Value.money:type_name -> google.type.Money
	9,  // 8: moego.business.report.v1.Value.timestamp:type_name -> google.protobuf.Timestamp
	5,  // 9: moego.business.report.v1.TableRowData.DataEntry.value:type_name -> moego.business.report.v1.Data
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_moego_business_report_v1_report_proto_init() }
func file_moego_business_report_v1_report_proto_init() {
	if File_moego_business_report_v1_report_proto != nil {
		return
	}
	file_moego_business_report_v1_report_proto_msgTypes[5].OneofWrappers = []any{
		(*Value_String_)(nil),
		(*Value_Double)(nil),
		(*Value_Int64)(nil),
		(*Value_Bool)(nil),
		(*Value_Money)(nil),
		(*Value_Timestamp)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_moego_business_report_v1_report_proto_rawDesc), len(file_moego_business_report_v1_report_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_moego_business_report_v1_report_proto_goTypes,
		DependencyIndexes: file_moego_business_report_v1_report_proto_depIdxs,
		EnumInfos:         file_moego_business_report_v1_report_proto_enumTypes,
		MessageInfos:      file_moego_business_report_v1_report_proto_msgTypes,
	}.Build()
	File_moego_business_report_v1_report_proto = out.File
	file_moego_business_report_v1_report_proto_goTypes = nil
	file_moego_business_report_v1_report_proto_depIdxs = nil
}
