// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: moego/business/online_booking/v1/booking_request_service.proto

package onlinebookingpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BookingRequestService_GetBookingRequest_FullMethodName     = "/moego.business.online_booking.v1.BookingRequestService/GetBookingRequest"
	BookingRequestService_ListBookingRequests_FullMethodName   = "/moego.business.online_booking.v1.BookingRequestService/ListBookingRequests"
	BookingRequestService_GetAbandonedBooking_FullMethodName   = "/moego.business.online_booking.v1.BookingRequestService/GetAbandonedBooking"
	BookingRequestService_ListAbandonedBookings_FullMethodName = "/moego.business.online_booking.v1.BookingRequestService/ListAbandonedBookings"
)

// BookingRequestServiceClient is the client API for BookingRequestService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// The BookingRequestService provides methods for managing online booking requests,
// including retrieving individual requests and listing filtered sets.
//
// All methods require authentication and proper business context.
type BookingRequestServiceClient interface {
	// Retrieves a single booking request by ID.
	//
	// Returns detailed information about the customer, requested services,
	// time window, and current status. Returns NOT_FOUND if not found.
	GetBookingRequest(ctx context.Context, in *GetBookingRequestRequest, opts ...grpc.CallOption) (*BookingRequest, error)
	// Lists booking requests matching specified criteria.
	//
	// Returns a paginated list of booking requests filtered by time range,
	// status, customer ID, or associated appointment ID.
	ListBookingRequests(ctx context.Context, in *ListBookingRequestsRequest, opts ...grpc.CallOption) (*ListBookingRequestResponse, error)
	// Retrieves a single abandoned booking by ID.
	//
	// Returns detailed information about the abandoned booking including customer info,
	// step where it was abandoned, and associated lead type. Returns NOT_FOUND if not found.
	GetAbandonedBooking(ctx context.Context, in *GetAbandonedBookingRequest, opts ...grpc.CallOption) (*AbandonedBooking, error)
	// Lists abandoned bookings matching specified criteria.
	//
	// Returns a paginated list of abandoned bookings filtered by abandon time,
	// status, step, or lead type.
	ListAbandonedBookings(ctx context.Context, in *ListAbandonedBookingRequest, opts ...grpc.CallOption) (*ListAbandonedBookingResponse, error)
}

type bookingRequestServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBookingRequestServiceClient(cc grpc.ClientConnInterface) BookingRequestServiceClient {
	return &bookingRequestServiceClient{cc}
}

func (c *bookingRequestServiceClient) GetBookingRequest(ctx context.Context, in *GetBookingRequestRequest, opts ...grpc.CallOption) (*BookingRequest, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BookingRequest)
	err := c.cc.Invoke(ctx, BookingRequestService_GetBookingRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookingRequestServiceClient) ListBookingRequests(ctx context.Context, in *ListBookingRequestsRequest, opts ...grpc.CallOption) (*ListBookingRequestResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListBookingRequestResponse)
	err := c.cc.Invoke(ctx, BookingRequestService_ListBookingRequests_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookingRequestServiceClient) GetAbandonedBooking(ctx context.Context, in *GetAbandonedBookingRequest, opts ...grpc.CallOption) (*AbandonedBooking, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AbandonedBooking)
	err := c.cc.Invoke(ctx, BookingRequestService_GetAbandonedBooking_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookingRequestServiceClient) ListAbandonedBookings(ctx context.Context, in *ListAbandonedBookingRequest, opts ...grpc.CallOption) (*ListAbandonedBookingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAbandonedBookingResponse)
	err := c.cc.Invoke(ctx, BookingRequestService_ListAbandonedBookings_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BookingRequestServiceServer is the server API for BookingRequestService service.
// All implementations must embed UnimplementedBookingRequestServiceServer
// for forward compatibility.
//
// The BookingRequestService provides methods for managing online booking requests,
// including retrieving individual requests and listing filtered sets.
//
// All methods require authentication and proper business context.
type BookingRequestServiceServer interface {
	// Retrieves a single booking request by ID.
	//
	// Returns detailed information about the customer, requested services,
	// time window, and current status. Returns NOT_FOUND if not found.
	GetBookingRequest(context.Context, *GetBookingRequestRequest) (*BookingRequest, error)
	// Lists booking requests matching specified criteria.
	//
	// Returns a paginated list of booking requests filtered by time range,
	// status, customer ID, or associated appointment ID.
	ListBookingRequests(context.Context, *ListBookingRequestsRequest) (*ListBookingRequestResponse, error)
	// Retrieves a single abandoned booking by ID.
	//
	// Returns detailed information about the abandoned booking including customer info,
	// step where it was abandoned, and associated lead type. Returns NOT_FOUND if not found.
	GetAbandonedBooking(context.Context, *GetAbandonedBookingRequest) (*AbandonedBooking, error)
	// Lists abandoned bookings matching specified criteria.
	//
	// Returns a paginated list of abandoned bookings filtered by abandon time,
	// status, step, or lead type.
	ListAbandonedBookings(context.Context, *ListAbandonedBookingRequest) (*ListAbandonedBookingResponse, error)
	mustEmbedUnimplementedBookingRequestServiceServer()
}

// UnimplementedBookingRequestServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBookingRequestServiceServer struct{}

func (UnimplementedBookingRequestServiceServer) GetBookingRequest(context.Context, *GetBookingRequestRequest) (*BookingRequest, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBookingRequest not implemented")
}
func (UnimplementedBookingRequestServiceServer) ListBookingRequests(context.Context, *ListBookingRequestsRequest) (*ListBookingRequestResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListBookingRequests not implemented")
}
func (UnimplementedBookingRequestServiceServer) GetAbandonedBooking(context.Context, *GetAbandonedBookingRequest) (*AbandonedBooking, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAbandonedBooking not implemented")
}
func (UnimplementedBookingRequestServiceServer) ListAbandonedBookings(context.Context, *ListAbandonedBookingRequest) (*ListAbandonedBookingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListAbandonedBookings not implemented")
}
func (UnimplementedBookingRequestServiceServer) mustEmbedUnimplementedBookingRequestServiceServer() {}
func (UnimplementedBookingRequestServiceServer) testEmbeddedByValue()                               {}

// UnsafeBookingRequestServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BookingRequestServiceServer will
// result in compilation errors.
type UnsafeBookingRequestServiceServer interface {
	mustEmbedUnimplementedBookingRequestServiceServer()
}

func RegisterBookingRequestServiceServer(s grpc.ServiceRegistrar, srv BookingRequestServiceServer) {
	// If the following call pancis, it indicates UnimplementedBookingRequestServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BookingRequestService_ServiceDesc, srv)
}

func _BookingRequestService_GetBookingRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBookingRequestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookingRequestServiceServer).GetBookingRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BookingRequestService_GetBookingRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookingRequestServiceServer).GetBookingRequest(ctx, req.(*GetBookingRequestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BookingRequestService_ListBookingRequests_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListBookingRequestsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookingRequestServiceServer).ListBookingRequests(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BookingRequestService_ListBookingRequests_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookingRequestServiceServer).ListBookingRequests(ctx, req.(*ListBookingRequestsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BookingRequestService_GetAbandonedBooking_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAbandonedBookingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookingRequestServiceServer).GetAbandonedBooking(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BookingRequestService_GetAbandonedBooking_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookingRequestServiceServer).GetAbandonedBooking(ctx, req.(*GetAbandonedBookingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BookingRequestService_ListAbandonedBookings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAbandonedBookingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookingRequestServiceServer).ListAbandonedBookings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BookingRequestService_ListAbandonedBookings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookingRequestServiceServer).ListAbandonedBookings(ctx, req.(*ListAbandonedBookingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BookingRequestService_ServiceDesc is the grpc.ServiceDesc for BookingRequestService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BookingRequestService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "moego.business.online_booking.v1.BookingRequestService",
	HandlerType: (*BookingRequestServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetBookingRequest",
			Handler:    _BookingRequestService_GetBookingRequest_Handler,
		},
		{
			MethodName: "ListBookingRequests",
			Handler:    _BookingRequestService_ListBookingRequests_Handler,
		},
		{
			MethodName: "GetAbandonedBooking",
			Handler:    _BookingRequestService_GetAbandonedBooking_Handler,
		},
		{
			MethodName: "ListAbandonedBookings",
			Handler:    _BookingRequestService_ListAbandonedBookings_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "moego/business/online_booking/v1/booking_request_service.proto",
}
