// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: moego/business/online_booking/v1/booking_request_service.proto

package onlinebookingpb

import (
	commonpb "github.com/MoeGolibrary/moegoapis/genproto/go/common/v1/commonpb"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	interval "google.golang.org/genproto/googleapis/type/interval"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request to list booking requests matching specified criteria.
type ListBookingRequestsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Pagination parameters.
	// Use page_size to specify results per page (max 500).
	// Use page_token from previous response for next page.
	Pagination *commonpb.Pagination `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
	// The company identifier for multi-location businesses.
	// Required for company-wide booking request listing.
	CompanyId string `protobuf:"bytes,2,opt,name=company_id,json=companyId,proto3" json:"company_id,omitempty"`
	// List of business location IDs to include.
	BusinessIds []string `protobuf:"bytes,3,rep,name=business_ids,json=businessIds,proto3" json:"business_ids,omitempty"`
	// Optional filters to narrow the results.
	Filter        *ListBookingRequestsRequest_Filter `protobuf:"bytes,4,opt,name=filter,proto3" json:"filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBookingRequestsRequest) Reset() {
	*x = ListBookingRequestsRequest{}
	mi := &file_moego_business_online_booking_v1_booking_request_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBookingRequestsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBookingRequestsRequest) ProtoMessage() {}

func (x *ListBookingRequestsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_moego_business_online_booking_v1_booking_request_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBookingRequestsRequest.ProtoReflect.Descriptor instead.
func (*ListBookingRequestsRequest) Descriptor() ([]byte, []int) {
	return file_moego_business_online_booking_v1_booking_request_service_proto_rawDescGZIP(), []int{0}
}

func (x *ListBookingRequestsRequest) GetPagination() *commonpb.Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *ListBookingRequestsRequest) GetCompanyId() string {
	if x != nil {
		return x.CompanyId
	}
	return ""
}

func (x *ListBookingRequestsRequest) GetBusinessIds() []string {
	if x != nil {
		return x.BusinessIds
	}
	return nil
}

func (x *ListBookingRequestsRequest) GetFilter() *ListBookingRequestsRequest_Filter {
	if x != nil {
		return x.Filter
	}
	return nil
}

// Response for listing booking requests.
type ListBookingRequestResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Token for retrieving the next page of results.
	// Empty if there are no more results.
	NextPageToken string `protobuf:"bytes,1,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	// List of booking requests matching the request criteria.
	// Ordered by start time in ascending order.
	BookingRequests []*BookingRequest `protobuf:"bytes,2,rep,name=booking_requests,json=bookingRequests,proto3" json:"booking_requests,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ListBookingRequestResponse) Reset() {
	*x = ListBookingRequestResponse{}
	mi := &file_moego_business_online_booking_v1_booking_request_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBookingRequestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBookingRequestResponse) ProtoMessage() {}

func (x *ListBookingRequestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_moego_business_online_booking_v1_booking_request_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBookingRequestResponse.ProtoReflect.Descriptor instead.
func (*ListBookingRequestResponse) Descriptor() ([]byte, []int) {
	return file_moego_business_online_booking_v1_booking_request_service_proto_rawDescGZIP(), []int{1}
}

func (x *ListBookingRequestResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

func (x *ListBookingRequestResponse) GetBookingRequests() []*BookingRequest {
	if x != nil {
		return x.BookingRequests
	}
	return nil
}

// Request to get a booking request by its ID.
type GetBookingRequestRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The unique identifier of the booking request to retrieve.
	// Format: "obg_" followed by random characters
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// The business location's identifier.
	// Must match the business_id of the booking request.
	BusinessId    string `protobuf:"bytes,2,opt,name=business_id,json=businessId,proto3" json:"business_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBookingRequestRequest) Reset() {
	*x = GetBookingRequestRequest{}
	mi := &file_moego_business_online_booking_v1_booking_request_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBookingRequestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBookingRequestRequest) ProtoMessage() {}

func (x *GetBookingRequestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_moego_business_online_booking_v1_booking_request_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBookingRequestRequest.ProtoReflect.Descriptor instead.
func (*GetBookingRequestRequest) Descriptor() ([]byte, []int) {
	return file_moego_business_online_booking_v1_booking_request_service_proto_rawDescGZIP(), []int{2}
}

func (x *GetBookingRequestRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetBookingRequestRequest) GetBusinessId() string {
	if x != nil {
		return x.BusinessId
	}
	return ""
}

// Request to list abandoned bookings.
type ListAbandonedBookingRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Pagination parameters.
	// Use page_size to specify results per page (max 500).
	// Use page_token from previous response for next page.
	Pagination *commonpb.Pagination `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
	// The company identifier for multi-location businesses.
	// Required for company-wide listing.
	CompanyId string `protobuf:"bytes,2,opt,name=company_id,json=companyId,proto3" json:"company_id,omitempty"`
	// List of business location IDs to include.
	BusinessIds []string `protobuf:"bytes,3,rep,name=business_ids,json=businessIds,proto3" json:"business_ids,omitempty"`
	// Optional filters to narrow the results.
	Filter        *ListAbandonedBookingRequest_Filter `protobuf:"bytes,4,opt,name=filter,proto3" json:"filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAbandonedBookingRequest) Reset() {
	*x = ListAbandonedBookingRequest{}
	mi := &file_moego_business_online_booking_v1_booking_request_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAbandonedBookingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAbandonedBookingRequest) ProtoMessage() {}

func (x *ListAbandonedBookingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_moego_business_online_booking_v1_booking_request_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAbandonedBookingRequest.ProtoReflect.Descriptor instead.
func (*ListAbandonedBookingRequest) Descriptor() ([]byte, []int) {
	return file_moego_business_online_booking_v1_booking_request_service_proto_rawDescGZIP(), []int{3}
}

func (x *ListAbandonedBookingRequest) GetPagination() *commonpb.Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *ListAbandonedBookingRequest) GetCompanyId() string {
	if x != nil {
		return x.CompanyId
	}
	return ""
}

func (x *ListAbandonedBookingRequest) GetBusinessIds() []string {
	if x != nil {
		return x.BusinessIds
	}
	return nil
}

func (x *ListAbandonedBookingRequest) GetFilter() *ListAbandonedBookingRequest_Filter {
	if x != nil {
		return x.Filter
	}
	return nil
}

// Response for listing abandoned bookings.
type ListAbandonedBookingResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Token for retrieving the next page of results.
	// Empty if there are no more results.
	NextPageToken string `protobuf:"bytes,1,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	// List of abandoned bookings matching the request criteria.
	Bookings      []*AbandonedBooking `protobuf:"bytes,2,rep,name=bookings,proto3" json:"bookings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAbandonedBookingResponse) Reset() {
	*x = ListAbandonedBookingResponse{}
	mi := &file_moego_business_online_booking_v1_booking_request_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAbandonedBookingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAbandonedBookingResponse) ProtoMessage() {}

func (x *ListAbandonedBookingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_moego_business_online_booking_v1_booking_request_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAbandonedBookingResponse.ProtoReflect.Descriptor instead.
func (*ListAbandonedBookingResponse) Descriptor() ([]byte, []int) {
	return file_moego_business_online_booking_v1_booking_request_service_proto_rawDescGZIP(), []int{4}
}

func (x *ListAbandonedBookingResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

func (x *ListAbandonedBookingResponse) GetBookings() []*AbandonedBooking {
	if x != nil {
		return x.Bookings
	}
	return nil
}

// Request to retrieve a specific abandoned booking.
type GetAbandonedBookingRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The unique identifier of the abandoned booking to retrieve.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// The business location's identifier.
	// Must match the business_id of the abandoned booking.
	BusinessId    string `protobuf:"bytes,2,opt,name=business_id,json=businessId,proto3" json:"business_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAbandonedBookingRequest) Reset() {
	*x = GetAbandonedBookingRequest{}
	mi := &file_moego_business_online_booking_v1_booking_request_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAbandonedBookingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAbandonedBookingRequest) ProtoMessage() {}

func (x *GetAbandonedBookingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_moego_business_online_booking_v1_booking_request_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAbandonedBookingRequest.ProtoReflect.Descriptor instead.
func (*GetAbandonedBookingRequest) Descriptor() ([]byte, []int) {
	return file_moego_business_online_booking_v1_booking_request_service_proto_rawDescGZIP(), []int{5}
}

func (x *GetAbandonedBookingRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetAbandonedBookingRequest) GetBusinessId() string {
	if x != nil {
		return x.BusinessId
	}
	return ""
}

// Filter parameters for the booking request list.
type ListBookingRequestsRequest_Filter struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Filter by the start time range of the booking request.
	StartTime *interval.Interval `protobuf:"bytes,1,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	// Filter by the end time range of the booking request.
	EndTime *interval.Interval `protobuf:"bytes,2,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	// Filter by the statuses of the booking requests.
	// Example values: ["SUBMITTED", "WAIT_LIST", "SCHEDULED", "DECLINED", "DELETED"]
	Statuses []BookingRequest_Status `protobuf:"varint,3,rep,packed,name=statuses,proto3,enum=moego.business.online_booking.v1.BookingRequest_Status" json:"statuses,omitempty"`
	// Optional. Filter by the payment statuses of the booking requests.
	// Supported values include: ["NO_PAYMENT", "WAITING", "PROCESSING", "SUCCESS", "FAILED"].
	PaymentStatuses []BookingRequest_PaymentStatus `protobuf:"varint,4,rep,packed,name=payment_statuses,json=paymentStatuses,proto3,enum=moego.business.online_booking.v1.BookingRequest_PaymentStatus" json:"payment_statuses,omitempty"`
	// Optional. Filter by associated customer IDs.
	CustomerId []string `protobuf:"bytes,5,rep,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	// Optional. Filter by associated appointment IDs.
	AppointmentIds []string `protobuf:"bytes,6,rep,name=appointment_ids,json=appointmentIds,proto3" json:"appointment_ids,omitempty"`
	// Optional. Filter by whether the waitlist booking request is expired.
	IsWaitlistExpired bool `protobuf:"varint,7,opt,name=is_waitlist_expired,json=isWaitlistExpired,proto3" json:"is_waitlist_expired,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ListBookingRequestsRequest_Filter) Reset() {
	*x = ListBookingRequestsRequest_Filter{}
	mi := &file_moego_business_online_booking_v1_booking_request_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBookingRequestsRequest_Filter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBookingRequestsRequest_Filter) ProtoMessage() {}

func (x *ListBookingRequestsRequest_Filter) ProtoReflect() protoreflect.Message {
	mi := &file_moego_business_online_booking_v1_booking_request_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBookingRequestsRequest_Filter.ProtoReflect.Descriptor instead.
func (*ListBookingRequestsRequest_Filter) Descriptor() ([]byte, []int) {
	return file_moego_business_online_booking_v1_booking_request_service_proto_rawDescGZIP(), []int{0, 0}
}

func (x *ListBookingRequestsRequest_Filter) GetStartTime() *interval.Interval {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *ListBookingRequestsRequest_Filter) GetEndTime() *interval.Interval {
	if x != nil {
		return x.EndTime
	}
	return nil
}

func (x *ListBookingRequestsRequest_Filter) GetStatuses() []BookingRequest_Status {
	if x != nil {
		return x.Statuses
	}
	return nil
}

func (x *ListBookingRequestsRequest_Filter) GetPaymentStatuses() []BookingRequest_PaymentStatus {
	if x != nil {
		return x.PaymentStatuses
	}
	return nil
}

func (x *ListBookingRequestsRequest_Filter) GetCustomerId() []string {
	if x != nil {
		return x.CustomerId
	}
	return nil
}

func (x *ListBookingRequestsRequest_Filter) GetAppointmentIds() []string {
	if x != nil {
		return x.AppointmentIds
	}
	return nil
}

func (x *ListBookingRequestsRequest_Filter) GetIsWaitlistExpired() bool {
	if x != nil {
		return x.IsWaitlistExpired
	}
	return false
}

// Filter parameters for the abandoned booking list.
type ListAbandonedBookingRequest_Filter struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Filter by the abandon time range of the booking.
	AbandonTime *interval.Interval `protobuf:"bytes,1,opt,name=abandon_time,json=abandonTime,proto3" json:"abandon_time,omitempty"`
	// Filter by the lead types of the abandoned booking.
	// Example values: ["LEAD_TYPE_UNSPECIFIED", "NEW_VISITOR", "EXISTING_CLIENT"]
	LeadTypes []AbandonedBooking_LeadType `protobuf:"varint,2,rep,packed,name=lead_types,json=leadTypes,proto3,enum=moego.business.online_booking.v1.AbandonedBooking_LeadType" json:"lead_types,omitempty"`
	// Filter by the steps at which the booking was abandoned.
	// Example values: ["WELCOME_PAGE", "BASIC_INFO", "SELECT_CARE_TYPE", ...]
	Steps []AbandonedBooking_Step `protobuf:"varint,3,rep,packed,name=steps,proto3,enum=moego.business.online_booking.v1.AbandonedBooking_Step" json:"steps,omitempty"`
	// Filter by the statuses of the abandoned bookings.
	// Example values: ["CONFIRMED", "CHECKED_IN"]
	Statuses      []AbandonedBooking_Status `protobuf:"varint,4,rep,packed,name=statuses,proto3,enum=moego.business.online_booking.v1.AbandonedBooking_Status" json:"statuses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAbandonedBookingRequest_Filter) Reset() {
	*x = ListAbandonedBookingRequest_Filter{}
	mi := &file_moego_business_online_booking_v1_booking_request_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAbandonedBookingRequest_Filter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAbandonedBookingRequest_Filter) ProtoMessage() {}

func (x *ListAbandonedBookingRequest_Filter) ProtoReflect() protoreflect.Message {
	mi := &file_moego_business_online_booking_v1_booking_request_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAbandonedBookingRequest_Filter.ProtoReflect.Descriptor instead.
func (*ListAbandonedBookingRequest_Filter) Descriptor() ([]byte, []int) {
	return file_moego_business_online_booking_v1_booking_request_service_proto_rawDescGZIP(), []int{3, 0}
}

func (x *ListAbandonedBookingRequest_Filter) GetAbandonTime() *interval.Interval {
	if x != nil {
		return x.AbandonTime
	}
	return nil
}

func (x *ListAbandonedBookingRequest_Filter) GetLeadTypes() []AbandonedBooking_LeadType {
	if x != nil {
		return x.LeadTypes
	}
	return nil
}

func (x *ListAbandonedBookingRequest_Filter) GetSteps() []AbandonedBooking_Step {
	if x != nil {
		return x.Steps
	}
	return nil
}

func (x *ListAbandonedBookingRequest_Filter) GetStatuses() []AbandonedBooking_Status {
	if x != nil {
		return x.Statuses
	}
	return nil
}

var File_moego_business_online_booking_v1_booking_request_service_proto protoreflect.FileDescriptor

const file_moego_business_online_booking_v1_booking_request_service_proto_rawDesc = "" +
	"\n" +
	">moego/business/online_booking/v1/booking_request_service.proto\x12 moego.business.online_booking.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x1agoogle/type/interval.proto\x1a8moego/business/online_booking/v1/abandoned_booking.proto\x1a6moego/business/online_booking/v1/booking_request.proto\x1a moego/common/v1/pagination.proto\"\xd7\x05\n" +
	"\x1aListBookingRequestsRequest\x12@\n" +
	"\n" +
	"pagination\x18\x01 \x01(\v2\x1b.moego.common.v1.PaginationB\x03\xe0A\x02R\n" +
	"pagination\x12\"\n" +
	"\n" +
	"company_id\x18\x02 \x01(\tB\x03\xe0A\x02R\tcompanyId\x12&\n" +
	"\fbusiness_ids\x18\x03 \x03(\tB\x03\xe0A\x02R\vbusinessIds\x12[\n" +
	"\x06filter\x18\x04 \x01(\v2C.moego.business.online_booking.v1.ListBookingRequestsRequest.FilterR\x06filter\x1a\xcd\x03\n" +
	"\x06Filter\x129\n" +
	"\n" +
	"start_time\x18\x01 \x01(\v2\x15.google.type.IntervalB\x03\xe0A\x01R\tstartTime\x125\n" +
	"\bend_time\x18\x02 \x01(\v2\x15.google.type.IntervalB\x03\xe0A\x01R\aendTime\x12X\n" +
	"\bstatuses\x18\x03 \x03(\x0e27.moego.business.online_booking.v1.BookingRequest.StatusB\x03\xe0A\x01R\bstatuses\x12n\n" +
	"\x10payment_statuses\x18\x04 \x03(\x0e2>.moego.business.online_booking.v1.BookingRequest.PaymentStatusB\x03\xe0A\x01R\x0fpaymentStatuses\x12$\n" +
	"\vcustomer_id\x18\x05 \x03(\tB\x03\xe0A\x01R\n" +
	"customerId\x12,\n" +
	"\x0fappointment_ids\x18\x06 \x03(\tB\x03\xe0A\x01R\x0eappointmentIds\x123\n" +
	"\x13is_waitlist_expired\x18\a \x01(\bB\x03\xe0A\x01R\x11isWaitlistExpired\"\xa1\x01\n" +
	"\x1aListBookingRequestResponse\x12&\n" +
	"\x0fnext_page_token\x18\x01 \x01(\tR\rnextPageToken\x12[\n" +
	"\x10booking_requests\x18\x02 \x03(\v20.moego.business.online_booking.v1.BookingRequestR\x0fbookingRequests\"U\n" +
	"\x18GetBookingRequestRequest\x12\x13\n" +
	"\x02id\x18\x01 \x01(\tB\x03\xe0A\x02R\x02id\x12$\n" +
	"\vbusiness_id\x18\x02 \x01(\tB\x03\xe0A\x02R\n" +
	"businessId\"\xe4\x04\n" +
	"\x1bListAbandonedBookingRequest\x12@\n" +
	"\n" +
	"pagination\x18\x01 \x01(\v2\x1b.moego.common.v1.PaginationB\x03\xe0A\x02R\n" +
	"pagination\x12\"\n" +
	"\n" +
	"company_id\x18\x02 \x01(\tB\x03\xe0A\x02R\tcompanyId\x12&\n" +
	"\fbusiness_ids\x18\x03 \x03(\tB\x03\xe0A\x02R\vbusinessIds\x12\\\n" +
	"\x06filter\x18\x04 \x01(\v2D.moego.business.online_booking.v1.ListAbandonedBookingRequest.FilterR\x06filter\x1a\xd8\x02\n" +
	"\x06Filter\x12=\n" +
	"\fabandon_time\x18\x01 \x01(\v2\x15.google.type.IntervalB\x03\xe0A\x01R\vabandonTime\x12_\n" +
	"\n" +
	"lead_types\x18\x02 \x03(\x0e2;.moego.business.online_booking.v1.AbandonedBooking.LeadTypeB\x03\xe0A\x01R\tleadTypes\x12R\n" +
	"\x05steps\x18\x03 \x03(\x0e27.moego.business.online_booking.v1.AbandonedBooking.StepB\x03\xe0A\x01R\x05steps\x12Z\n" +
	"\bstatuses\x18\x04 \x03(\x0e29.moego.business.online_booking.v1.AbandonedBooking.StatusB\x03\xe0A\x01R\bstatuses\"\x96\x01\n" +
	"\x1cListAbandonedBookingResponse\x12&\n" +
	"\x0fnext_page_token\x18\x01 \x01(\tR\rnextPageToken\x12N\n" +
	"\bbookings\x18\x02 \x03(\v22.moego.business.online_booking.v1.AbandonedBookingR\bbookings\"W\n" +
	"\x1aGetAbandonedBookingRequest\x12\x13\n" +
	"\x02id\x18\x01 \x01(\tB\x03\xe0A\x02R\x02id\x12$\n" +
	"\vbusiness_id\x18\x02 \x01(\tB\x03\xe0A\x02R\n" +
	"businessId2\xe8\x05\n" +
	"\x15BookingRequestService\x12\xa4\x01\n" +
	"\x11GetBookingRequest\x12:.moego.business.online_booking.v1.GetBookingRequestRequest\x1a0.moego.business.online_booking.v1.BookingRequest\"!\x82\xd3\xe4\x93\x02\x1b\x12\x19/v1/booking_requests/{id}\x12\xb7\x01\n" +
	"\x13ListBookingRequests\x12<.moego.business.online_booking.v1.ListBookingRequestsRequest\x1a<.moego.business.online_booking.v1.ListBookingRequestResponse\"$\x82\xd3\xe4\x93\x02\x1e:\x01*\"\x19/v1/booking_requests:list\x12\xac\x01\n" +
	"\x13GetAbandonedBooking\x12<.moego.business.online_booking.v1.GetAbandonedBookingRequest\x1a2.moego.business.online_booking.v1.AbandonedBooking\"#\x82\xd3\xe4\x93\x02\x1d\x12\x1b/v1/abandoned_bookings/{id}\x12\xbe\x01\n" +
	"\x15ListAbandonedBookings\x12=.moego.business.online_booking.v1.ListAbandonedBookingRequest\x1a>.moego.business.online_booking.v1.ListAbandonedBookingResponse\"&\x82\xd3\xe4\x93\x02 :\x01*\"\x1b/v1/abandoned_bookings:listB\xb2\x01\n" +
	"(com.moego.api.business.online_booking.v1B\x1aBookingRequestServiceProtoP\x01Zhgithub.com/MoeGolibrary/moegoapis/genproto/go/business/online_booking/v1/onlinebookingpb;onlinebookingpbb\x06proto3"

var (
	file_moego_business_online_booking_v1_booking_request_service_proto_rawDescOnce sync.Once
	file_moego_business_online_booking_v1_booking_request_service_proto_rawDescData []byte
)

func file_moego_business_online_booking_v1_booking_request_service_proto_rawDescGZIP() []byte {
	file_moego_business_online_booking_v1_booking_request_service_proto_rawDescOnce.Do(func() {
		file_moego_business_online_booking_v1_booking_request_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_moego_business_online_booking_v1_booking_request_service_proto_rawDesc), len(file_moego_business_online_booking_v1_booking_request_service_proto_rawDesc)))
	})
	return file_moego_business_online_booking_v1_booking_request_service_proto_rawDescData
}

var file_moego_business_online_booking_v1_booking_request_service_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_moego_business_online_booking_v1_booking_request_service_proto_goTypes = []any{
	(*ListBookingRequestsRequest)(nil),         // 0: moego.business.online_booking.v1.ListBookingRequestsRequest
	(*ListBookingRequestResponse)(nil),         // 1: moego.business.online_booking.v1.ListBookingRequestResponse
	(*GetBookingRequestRequest)(nil),           // 2: moego.business.online_booking.v1.GetBookingRequestRequest
	(*ListAbandonedBookingRequest)(nil),        // 3: moego.business.online_booking.v1.ListAbandonedBookingRequest
	(*ListAbandonedBookingResponse)(nil),       // 4: moego.business.online_booking.v1.ListAbandonedBookingResponse
	(*GetAbandonedBookingRequest)(nil),         // 5: moego.business.online_booking.v1.GetAbandonedBookingRequest
	(*ListBookingRequestsRequest_Filter)(nil),  // 6: moego.business.online_booking.v1.ListBookingRequestsRequest.Filter
	(*ListAbandonedBookingRequest_Filter)(nil), // 7: moego.business.online_booking.v1.ListAbandonedBookingRequest.Filter
	(*commonpb.Pagination)(nil),                // 8: moego.common.v1.Pagination
	(*BookingRequest)(nil),                     // 9: moego.business.online_booking.v1.BookingRequest
	(*AbandonedBooking)(nil),                   // 10: moego.business.online_booking.v1.AbandonedBooking
	(*interval.Interval)(nil),                  // 11: google.type.Interval
	(BookingRequest_Status)(0),                 // 12: moego.business.online_booking.v1.BookingRequest.Status
	(BookingRequest_PaymentStatus)(0),          // 13: moego.business.online_booking.v1.BookingRequest.PaymentStatus
	(AbandonedBooking_LeadType)(0),             // 14: moego.business.online_booking.v1.AbandonedBooking.LeadType
	(AbandonedBooking_Step)(0),                 // 15: moego.business.online_booking.v1.AbandonedBooking.Step
	(AbandonedBooking_Status)(0),               // 16: moego.business.online_booking.v1.AbandonedBooking.Status
}
var file_moego_business_online_booking_v1_booking_request_service_proto_depIdxs = []int32{
	8,  // 0: moego.business.online_booking.v1.ListBookingRequestsRequest.pagination:type_name -> moego.common.v1.Pagination
	6,  // 1: moego.business.online_booking.v1.ListBookingRequestsRequest.filter:type_name -> moego.business.online_booking.v1.ListBookingRequestsRequest.Filter
	9,  // 2: moego.business.online_booking.v1.ListBookingRequestResponse.booking_requests:type_name -> moego.business.online_booking.v1.BookingRequest
	8,  // 3: moego.business.online_booking.v1.ListAbandonedBookingRequest.pagination:type_name -> moego.common.v1.Pagination
	7,  // 4: moego.business.online_booking.v1.ListAbandonedBookingRequest.filter:type_name -> moego.business.online_booking.v1.ListAbandonedBookingRequest.Filter
	10, // 5: moego.business.online_booking.v1.ListAbandonedBookingResponse.bookings:type_name -> moego.business.online_booking.v1.AbandonedBooking
	11, // 6: moego.business.online_booking.v1.ListBookingRequestsRequest.Filter.start_time:type_name -> google.type.Interval
	11, // 7: moego.business.online_booking.v1.ListBookingRequestsRequest.Filter.end_time:type_name -> google.type.Interval
	12, // 8: moego.business.online_booking.v1.ListBookingRequestsRequest.Filter.statuses:type_name -> moego.business.online_booking.v1.BookingRequest.Status
	13, // 9: moego.business.online_booking.v1.ListBookingRequestsRequest.Filter.payment_statuses:type_name -> moego.business.online_booking.v1.BookingRequest.PaymentStatus
	11, // 10: moego.business.online_booking.v1.ListAbandonedBookingRequest.Filter.abandon_time:type_name -> google.type.Interval
	14, // 11: moego.business.online_booking.v1.ListAbandonedBookingRequest.Filter.lead_types:type_name -> moego.business.online_booking.v1.AbandonedBooking.LeadType
	15, // 12: moego.business.online_booking.v1.ListAbandonedBookingRequest.Filter.steps:type_name -> moego.business.online_booking.v1.AbandonedBooking.Step
	16, // 13: moego.business.online_booking.v1.ListAbandonedBookingRequest.Filter.statuses:type_name -> moego.business.online_booking.v1.AbandonedBooking.Status
	2,  // 14: moego.business.online_booking.v1.BookingRequestService.GetBookingRequest:input_type -> moego.business.online_booking.v1.GetBookingRequestRequest
	0,  // 15: moego.business.online_booking.v1.BookingRequestService.ListBookingRequests:input_type -> moego.business.online_booking.v1.ListBookingRequestsRequest
	5,  // 16: moego.business.online_booking.v1.BookingRequestService.GetAbandonedBooking:input_type -> moego.business.online_booking.v1.GetAbandonedBookingRequest
	3,  // 17: moego.business.online_booking.v1.BookingRequestService.ListAbandonedBookings:input_type -> moego.business.online_booking.v1.ListAbandonedBookingRequest
	9,  // 18: moego.business.online_booking.v1.BookingRequestService.GetBookingRequest:output_type -> moego.business.online_booking.v1.BookingRequest
	1,  // 19: moego.business.online_booking.v1.BookingRequestService.ListBookingRequests:output_type -> moego.business.online_booking.v1.ListBookingRequestResponse
	10, // 20: moego.business.online_booking.v1.BookingRequestService.GetAbandonedBooking:output_type -> moego.business.online_booking.v1.AbandonedBooking
	4,  // 21: moego.business.online_booking.v1.BookingRequestService.ListAbandonedBookings:output_type -> moego.business.online_booking.v1.ListAbandonedBookingResponse
	18, // [18:22] is the sub-list for method output_type
	14, // [14:18] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_moego_business_online_booking_v1_booking_request_service_proto_init() }
func file_moego_business_online_booking_v1_booking_request_service_proto_init() {
	if File_moego_business_online_booking_v1_booking_request_service_proto != nil {
		return
	}
	file_moego_business_online_booking_v1_abandoned_booking_proto_init()
	file_moego_business_online_booking_v1_booking_request_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_moego_business_online_booking_v1_booking_request_service_proto_rawDesc), len(file_moego_business_online_booking_v1_booking_request_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_moego_business_online_booking_v1_booking_request_service_proto_goTypes,
		DependencyIndexes: file_moego_business_online_booking_v1_booking_request_service_proto_depIdxs,
		MessageInfos:      file_moego_business_online_booking_v1_booking_request_service_proto_msgTypes,
	}.Build()
	File_moego_business_online_booking_v1_booking_request_service_proto = out.File
	file_moego_business_online_booking_v1_booking_request_service_proto_goTypes = nil
	file_moego_business_online_booking_v1_booking_request_service_proto_depIdxs = nil
}
