// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: moego/business/customer/v1/pet_service.proto

package customerpb

import (
	commonpb "github.com/MoeGolibrary/moegoapis/genproto/go/common/v1/commonpb"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	interval "google.golang.org/genproto/googleapis/type/interval"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request message for creating a new pet profile.
type CreatePetRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID of the customer who owns the pet
	// Required. Must be a valid customer ID
	CustomerId string `protobuf:"bytes,1,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	// Complete pet information to be created
	// Required. Must include all required pet fields
	Pet           *Pet `protobuf:"bytes,2,opt,name=pet,proto3" json:"pet,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePetRequest) Reset() {
	*x = CreatePetRequest{}
	mi := &file_moego_business_customer_v1_pet_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePetRequest) ProtoMessage() {}

func (x *CreatePetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_moego_business_customer_v1_pet_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePetRequest.ProtoReflect.Descriptor instead.
func (*CreatePetRequest) Descriptor() ([]byte, []int) {
	return file_moego_business_customer_v1_pet_service_proto_rawDescGZIP(), []int{0}
}

func (x *CreatePetRequest) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *CreatePetRequest) GetPet() *Pet {
	if x != nil {
		return x.Pet
	}
	return nil
}

// Response message for creating a new pet profile.
type CreatePetResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The newly created pet profile
	// Includes system-generated fields like ID
	Pet           *Pet `protobuf:"bytes,1,opt,name=pet,proto3" json:"pet,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePetResponse) Reset() {
	*x = CreatePetResponse{}
	mi := &file_moego_business_customer_v1_pet_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePetResponse) ProtoMessage() {}

func (x *CreatePetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_moego_business_customer_v1_pet_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePetResponse.ProtoReflect.Descriptor instead.
func (*CreatePetResponse) Descriptor() ([]byte, []int) {
	return file_moego_business_customer_v1_pet_service_proto_rawDescGZIP(), []int{1}
}

func (x *CreatePetResponse) GetPet() *Pet {
	if x != nil {
		return x.Pet
	}
	return nil
}

// Request message for retrieving a specific pet.
type GetPetRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID of the customer who owns the pet
	// Required. Must be a valid customer ID
	CustomerId string `protobuf:"bytes,1,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	// Unique identifier of the pet to retrieve
	// Required. Format: "pet_" followed by random characters
	Id            string `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPetRequest) Reset() {
	*x = GetPetRequest{}
	mi := &file_moego_business_customer_v1_pet_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPetRequest) ProtoMessage() {}

func (x *GetPetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_moego_business_customer_v1_pet_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPetRequest.ProtoReflect.Descriptor instead.
func (*GetPetRequest) Descriptor() ([]byte, []int) {
	return file_moego_business_customer_v1_pet_service_proto_rawDescGZIP(), []int{2}
}

func (x *GetPetRequest) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *GetPetRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// Request message for listing a customer's pets.
type ListPetsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID of the customer whose pets to list
	// Required. Must be a valid customer ID
	CustomerId    string `protobuf:"bytes,1,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPetsRequest) Reset() {
	*x = ListPetsRequest{}
	mi := &file_moego_business_customer_v1_pet_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPetsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPetsRequest) ProtoMessage() {}

func (x *ListPetsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_moego_business_customer_v1_pet_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPetsRequest.ProtoReflect.Descriptor instead.
func (*ListPetsRequest) Descriptor() ([]byte, []int) {
	return file_moego_business_customer_v1_pet_service_proto_rawDescGZIP(), []int{3}
}

func (x *ListPetsRequest) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

// Response message for listing a customer's pets.
type ListPetsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// List of pets belonging to the customer
	// May be empty if the customer has no pets
	Pets          []*Pet `protobuf:"bytes,1,rep,name=pets,proto3" json:"pets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPetsResponse) Reset() {
	*x = ListPetsResponse{}
	mi := &file_moego_business_customer_v1_pet_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPetsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPetsResponse) ProtoMessage() {}

func (x *ListPetsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_moego_business_customer_v1_pet_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPetsResponse.ProtoReflect.Descriptor instead.
func (*ListPetsResponse) Descriptor() ([]byte, []int) {
	return file_moego_business_customer_v1_pet_service_proto_rawDescGZIP(), []int{4}
}

func (x *ListPetsResponse) GetPets() []*Pet {
	if x != nil {
		return x.Pets
	}
	return nil
}

// Request message for adding codes to a pet's profile.
type AppendPetCodesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID of the customer who owns the pet
	// Required. Must be a valid customer ID
	CustomerId string `protobuf:"bytes,1,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	// Unique identifier of the pet
	// Required. Format: "pet_" followed by random characters
	Id string `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	// IDs of the codes to add to the pet's profile
	// Required. Must be valid code IDs
	PetCodeIds    []string `protobuf:"bytes,3,rep,name=pet_code_ids,json=petCodeIds,proto3" json:"pet_code_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppendPetCodesRequest) Reset() {
	*x = AppendPetCodesRequest{}
	mi := &file_moego_business_customer_v1_pet_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppendPetCodesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendPetCodesRequest) ProtoMessage() {}

func (x *AppendPetCodesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_moego_business_customer_v1_pet_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendPetCodesRequest.ProtoReflect.Descriptor instead.
func (*AppendPetCodesRequest) Descriptor() ([]byte, []int) {
	return file_moego_business_customer_v1_pet_service_proto_rawDescGZIP(), []int{5}
}

func (x *AppendPetCodesRequest) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *AppendPetCodesRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AppendPetCodesRequest) GetPetCodeIds() []string {
	if x != nil {
		return x.PetCodeIds
	}
	return nil
}

// Response message for adding codes to a pet's profile.
type AppendPetCodesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Codes that were successfully added
	// Includes full code details
	Codes         []*Pet_Code `protobuf:"bytes,1,rep,name=codes,proto3" json:"codes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppendPetCodesResponse) Reset() {
	*x = AppendPetCodesResponse{}
	mi := &file_moego_business_customer_v1_pet_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppendPetCodesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendPetCodesResponse) ProtoMessage() {}

func (x *AppendPetCodesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_moego_business_customer_v1_pet_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendPetCodesResponse.ProtoReflect.Descriptor instead.
func (*AppendPetCodesResponse) Descriptor() ([]byte, []int) {
	return file_moego_business_customer_v1_pet_service_proto_rawDescGZIP(), []int{6}
}

func (x *AppendPetCodesResponse) GetCodes() []*Pet_Code {
	if x != nil {
		return x.Codes
	}
	return nil
}

// Request message for adding notes to a pet's profile.
type AppendPetNotesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID of the customer who owns the pet
	// Required. Must be a valid customer ID
	CustomerId string `protobuf:"bytes,1,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	// Unique identifier of the pet
	// Required. Format: "pet_" followed by random characters
	Id string `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	// Notes to add to the pet's profile
	// Required. At least one note must be provided
	Notes         []*Pet_Note `protobuf:"bytes,3,rep,name=notes,proto3" json:"notes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppendPetNotesRequest) Reset() {
	*x = AppendPetNotesRequest{}
	mi := &file_moego_business_customer_v1_pet_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppendPetNotesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendPetNotesRequest) ProtoMessage() {}

func (x *AppendPetNotesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_moego_business_customer_v1_pet_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendPetNotesRequest.ProtoReflect.Descriptor instead.
func (*AppendPetNotesRequest) Descriptor() ([]byte, []int) {
	return file_moego_business_customer_v1_pet_service_proto_rawDescGZIP(), []int{7}
}

func (x *AppendPetNotesRequest) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *AppendPetNotesRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AppendPetNotesRequest) GetNotes() []*Pet_Note {
	if x != nil {
		return x.Notes
	}
	return nil
}

// Response message for adding notes to a pet's profile.
type AppendPetNotesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Notes that were successfully added
	// Includes generated IDs and timestamps
	Notes         []*Pet_Note `protobuf:"bytes,1,rep,name=notes,proto3" json:"notes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppendPetNotesResponse) Reset() {
	*x = AppendPetNotesResponse{}
	mi := &file_moego_business_customer_v1_pet_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppendPetNotesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendPetNotesResponse) ProtoMessage() {}

func (x *AppendPetNotesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_moego_business_customer_v1_pet_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendPetNotesResponse.ProtoReflect.Descriptor instead.
func (*AppendPetNotesResponse) Descriptor() ([]byte, []int) {
	return file_moego_business_customer_v1_pet_service_proto_rawDescGZIP(), []int{8}
}

func (x *AppendPetNotesResponse) GetNotes() []*Pet_Note {
	if x != nil {
		return x.Notes
	}
	return nil
}

// Request message for listing a pet's notes.
type ListPetNotesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Pagination parameters for the request
	// Required. Defines page size and token for continuation
	Pagination *commonpb.Pagination `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
	// ID of the customer who owns the pet
	// Required. Must be a valid customer ID
	CustomerId string `protobuf:"bytes,2,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	// Unique identifier of the pet
	// Required. Format: "pet_" followed by random characters
	Id            string `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPetNotesRequest) Reset() {
	*x = ListPetNotesRequest{}
	mi := &file_moego_business_customer_v1_pet_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPetNotesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPetNotesRequest) ProtoMessage() {}

func (x *ListPetNotesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_moego_business_customer_v1_pet_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPetNotesRequest.ProtoReflect.Descriptor instead.
func (*ListPetNotesRequest) Descriptor() ([]byte, []int) {
	return file_moego_business_customer_v1_pet_service_proto_rawDescGZIP(), []int{9}
}

func (x *ListPetNotesRequest) GetPagination() *commonpb.Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *ListPetNotesRequest) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *ListPetNotesRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// Response message for listing a pet's notes.
type ListPetNotesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Token for retrieving the next page of results
	// Empty if there are no more results
	NextPageToken string `protobuf:"bytes,1,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	// List of notes for the pet
	// May be empty if the pet has no notes
	Notes         []*Pet_Note `protobuf:"bytes,2,rep,name=notes,proto3" json:"notes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPetNotesResponse) Reset() {
	*x = ListPetNotesResponse{}
	mi := &file_moego_business_customer_v1_pet_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPetNotesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPetNotesResponse) ProtoMessage() {}

func (x *ListPetNotesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_moego_business_customer_v1_pet_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPetNotesResponse.ProtoReflect.Descriptor instead.
func (*ListPetNotesResponse) Descriptor() ([]byte, []int) {
	return file_moego_business_customer_v1_pet_service_proto_rawDescGZIP(), []int{10}
}

func (x *ListPetNotesResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

func (x *ListPetNotesResponse) GetNotes() []*Pet_Note {
	if x != nil {
		return x.Notes
	}
	return nil
}

// Request message for listing all pets in the company.
type ListAllPetsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Pagination parameters for the request
	// Required. Defines page size and token for continuation
	Pagination *commonpb.Pagination `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
	// ID of the company to list pets for
	// Required. Must be a valid company ID
	CompanyId string `protobuf:"bytes,2,opt,name=company_id,json=companyId,proto3" json:"company_id,omitempty"`
	// Optional filters to apply to the pet list
	Filter        *ListAllPetsRequest_Filter `protobuf:"bytes,3,opt,name=filter,proto3" json:"filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAllPetsRequest) Reset() {
	*x = ListAllPetsRequest{}
	mi := &file_moego_business_customer_v1_pet_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAllPetsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAllPetsRequest) ProtoMessage() {}

func (x *ListAllPetsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_moego_business_customer_v1_pet_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAllPetsRequest.ProtoReflect.Descriptor instead.
func (*ListAllPetsRequest) Descriptor() ([]byte, []int) {
	return file_moego_business_customer_v1_pet_service_proto_rawDescGZIP(), []int{11}
}

func (x *ListAllPetsRequest) GetPagination() *commonpb.Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *ListAllPetsRequest) GetCompanyId() string {
	if x != nil {
		return x.CompanyId
	}
	return ""
}

func (x *ListAllPetsRequest) GetFilter() *ListAllPetsRequest_Filter {
	if x != nil {
		return x.Filter
	}
	return nil
}

// Response message for listing all pets.
type ListAllPetsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Token for retrieving the next page of results
	// Empty if there are no more results
	NextPageToken string `protobuf:"bytes,1,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	// List of pets matching the request criteria
	// May be empty if no pets match
	Pets          []*Pet `protobuf:"bytes,2,rep,name=pets,proto3" json:"pets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAllPetsResponse) Reset() {
	*x = ListAllPetsResponse{}
	mi := &file_moego_business_customer_v1_pet_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAllPetsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAllPetsResponse) ProtoMessage() {}

func (x *ListAllPetsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_moego_business_customer_v1_pet_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAllPetsResponse.ProtoReflect.Descriptor instead.
func (*ListAllPetsResponse) Descriptor() ([]byte, []int) {
	return file_moego_business_customer_v1_pet_service_proto_rawDescGZIP(), []int{12}
}

func (x *ListAllPetsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

func (x *ListAllPetsResponse) GetPets() []*Pet {
	if x != nil {
		return x.Pets
	}
	return nil
}

// Filter parameters for the pet list
type ListAllPetsRequest_Filter struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional list of customer IDs to filter by
	// If provided, only returns pets belonging to these customers
	CustomerIds []string `protobuf:"bytes,1,rep,name=customer_ids,json=customerIds,proto3" json:"customer_ids,omitempty"`
	// Optional list of time intervals to filter by
	// If provided, only returns pets with appointments within these intervals
	LastUpdatedTime *interval.Interval `protobuf:"bytes,2,opt,name=last_updated_time,json=lastUpdatedTime,proto3" json:"last_updated_time,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ListAllPetsRequest_Filter) Reset() {
	*x = ListAllPetsRequest_Filter{}
	mi := &file_moego_business_customer_v1_pet_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAllPetsRequest_Filter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAllPetsRequest_Filter) ProtoMessage() {}

func (x *ListAllPetsRequest_Filter) ProtoReflect() protoreflect.Message {
	mi := &file_moego_business_customer_v1_pet_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAllPetsRequest_Filter.ProtoReflect.Descriptor instead.
func (*ListAllPetsRequest_Filter) Descriptor() ([]byte, []int) {
	return file_moego_business_customer_v1_pet_service_proto_rawDescGZIP(), []int{11, 0}
}

func (x *ListAllPetsRequest_Filter) GetCustomerIds() []string {
	if x != nil {
		return x.CustomerIds
	}
	return nil
}

func (x *ListAllPetsRequest_Filter) GetLastUpdatedTime() *interval.Interval {
	if x != nil {
		return x.LastUpdatedTime
	}
	return nil
}

var File_moego_business_customer_v1_pet_service_proto protoreflect.FileDescriptor

const file_moego_business_customer_v1_pet_service_proto_rawDesc = "" +
	"\n" +
	",moego/business/customer/v1/pet_service.proto\x12\x1amoego.business.customer.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x1agoogle/type/interval.proto\x1a$moego/business/customer/v1/pet.proto\x1a moego/common/v1/pagination.proto\"p\n" +
	"\x10CreatePetRequest\x12$\n" +
	"\vcustomer_id\x18\x01 \x01(\tB\x03\xe0A\x02R\n" +
	"customerId\x126\n" +
	"\x03pet\x18\x02 \x01(\v2\x1f.moego.business.customer.v1.PetB\x03\xe0A\x02R\x03pet\"K\n" +
	"\x11CreatePetResponse\x126\n" +
	"\x03pet\x18\x01 \x01(\v2\x1f.moego.business.customer.v1.PetB\x03\xe0A\x03R\x03pet\"J\n" +
	"\rGetPetRequest\x12$\n" +
	"\vcustomer_id\x18\x01 \x01(\tB\x03\xe0A\x02R\n" +
	"customerId\x12\x13\n" +
	"\x02id\x18\x02 \x01(\tB\x03\xe0A\x02R\x02id\"7\n" +
	"\x0fListPetsRequest\x12$\n" +
	"\vcustomer_id\x18\x01 \x01(\tB\x03\xe0A\x02R\n" +
	"customerId\"G\n" +
	"\x10ListPetsResponse\x123\n" +
	"\x04pets\x18\x01 \x03(\v2\x1f.moego.business.customer.v1.PetR\x04pets\"y\n" +
	"\x15AppendPetCodesRequest\x12$\n" +
	"\vcustomer_id\x18\x01 \x01(\tB\x03\xe0A\x02R\n" +
	"customerId\x12\x13\n" +
	"\x02id\x18\x02 \x01(\tB\x03\xe0A\x02R\x02id\x12%\n" +
	"\fpet_code_ids\x18\x03 \x03(\tB\x03\xe0A\x02R\n" +
	"petCodeIds\"Y\n" +
	"\x16AppendPetCodesResponse\x12?\n" +
	"\x05codes\x18\x01 \x03(\v2$.moego.business.customer.v1.Pet.CodeB\x03\xe0A\x03R\x05codes\"\x8e\x01\n" +
	"\x15AppendPetNotesRequest\x12$\n" +
	"\vcustomer_id\x18\x01 \x01(\tB\x03\xe0A\x02R\n" +
	"customerId\x12\x13\n" +
	"\x02id\x18\x02 \x01(\tB\x03\xe0A\x02R\x02id\x12:\n" +
	"\x05notes\x18\x03 \x03(\v2$.moego.business.customer.v1.Pet.NoteR\x05notes\"T\n" +
	"\x16AppendPetNotesResponse\x12:\n" +
	"\x05notes\x18\x01 \x03(\v2$.moego.business.customer.v1.Pet.NoteR\x05notes\"\x92\x01\n" +
	"\x13ListPetNotesRequest\x12@\n" +
	"\n" +
	"pagination\x18\x01 \x01(\v2\x1b.moego.common.v1.PaginationB\x03\xe0A\x02R\n" +
	"pagination\x12$\n" +
	"\vcustomer_id\x18\x02 \x01(\tB\x03\xe0A\x02R\n" +
	"customerId\x12\x13\n" +
	"\x02id\x18\x03 \x01(\tB\x03\xe0A\x02R\x02id\"z\n" +
	"\x14ListPetNotesResponse\x12&\n" +
	"\x0fnext_page_token\x18\x01 \x01(\tR\rnextPageToken\x12:\n" +
	"\x05notes\x18\x02 \x03(\v2$.moego.business.customer.v1.Pet.NoteR\x05notes\"\xc3\x02\n" +
	"\x12ListAllPetsRequest\x12@\n" +
	"\n" +
	"pagination\x18\x01 \x01(\v2\x1b.moego.common.v1.PaginationB\x03\xe0A\x02R\n" +
	"pagination\x12\"\n" +
	"\n" +
	"company_id\x18\x02 \x01(\tB\x03\xe0A\x02R\tcompanyId\x12M\n" +
	"\x06filter\x18\x03 \x01(\v25.moego.business.customer.v1.ListAllPetsRequest.FilterR\x06filter\x1ax\n" +
	"\x06Filter\x12&\n" +
	"\fcustomer_ids\x18\x01 \x03(\tB\x03\xe0A\x01R\vcustomerIds\x12F\n" +
	"\x11last_updated_time\x18\x02 \x01(\v2\x15.google.type.IntervalB\x03\xe0A\x01R\x0flastUpdatedTime\"r\n" +
	"\x13ListAllPetsResponse\x12&\n" +
	"\x0fnext_page_token\x18\x01 \x01(\tR\rnextPageToken\x123\n" +
	"\x04pets\x18\x02 \x03(\v2\x1f.moego.business.customer.v1.PetR\x04pets2\xe4\b\n" +
	"\n" +
	"PetService\x12\x95\x01\n" +
	"\tCreatePet\x12,.moego.business.customer.v1.CreatePetRequest\x1a-.moego.business.customer.v1.CreatePetResponse\"+\x82\xd3\xe4\x93\x02%:\x01*\" /v1/customers/{customer_id}/pets\x12\x83\x01\n" +
	"\x06GetPet\x12).moego.business.customer.v1.GetPetRequest\x1a\x1f.moego.business.customer.v1.Pet\"-\x82\xd3\xe4\x93\x02'\x12%/v1/customers/{customer_id}/pets/{id}\x12\x97\x01\n" +
	"\bListPets\x12+.moego.business.customer.v1.ListPetsRequest\x1a,.moego.business.customer.v1.ListPetsResponse\"0\x82\xd3\xe4\x93\x02*:\x01*\"%/v1/customers/{customer_id}/pets:list\x12\xaf\x01\n" +
	"\x0eAppendPetCodes\x121.moego.business.customer.v1.AppendPetCodesRequest\x1a2.moego.business.customer.v1.AppendPetCodesResponse\"6\x82\xd3\xe4\x93\x020:\x01*\"+/v1/customers/{customer_id}/pets/{id}/codes\x12\xaf\x01\n" +
	"\x0eAppendPetNotes\x121.moego.business.customer.v1.AppendPetNotesRequest\x1a2.moego.business.customer.v1.AppendPetNotesResponse\"6\x82\xd3\xe4\x93\x020:\x01*\"+/v1/customers/{customer_id}/pets/{id}/notes\x12\xae\x01\n" +
	"\fListPetNotes\x12/.moego.business.customer.v1.ListPetNotesRequest\x1a0.moego.business.customer.v1.ListPetNotesResponse\";\x82\xd3\xe4\x93\x025:\x01*\"0/v1/customers/{customer_id}/pets/{id}/notes:list\x12\x88\x01\n" +
	"\vListAllPets\x12..moego.business.customer.v1.ListAllPetsRequest\x1a/.moego.business.customer.v1.ListAllPetsResponse\"\x18\x82\xd3\xe4\x93\x02\x12:\x01*\"\r/v1/pets:listB\x96\x01\n" +
	"\"com.moego.api.business.customer.v1B\x14CustomerServiceProtoP\x01ZXgithub.com/MoeGolibrary/moegoapis/genproto/go/business/customer/v1/customerpb;customerpbb\x06proto3"

var (
	file_moego_business_customer_v1_pet_service_proto_rawDescOnce sync.Once
	file_moego_business_customer_v1_pet_service_proto_rawDescData []byte
)

func file_moego_business_customer_v1_pet_service_proto_rawDescGZIP() []byte {
	file_moego_business_customer_v1_pet_service_proto_rawDescOnce.Do(func() {
		file_moego_business_customer_v1_pet_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_moego_business_customer_v1_pet_service_proto_rawDesc), len(file_moego_business_customer_v1_pet_service_proto_rawDesc)))
	})
	return file_moego_business_customer_v1_pet_service_proto_rawDescData
}

var file_moego_business_customer_v1_pet_service_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_moego_business_customer_v1_pet_service_proto_goTypes = []any{
	(*CreatePetRequest)(nil),          // 0: moego.business.customer.v1.CreatePetRequest
	(*CreatePetResponse)(nil),         // 1: moego.business.customer.v1.CreatePetResponse
	(*GetPetRequest)(nil),             // 2: moego.business.customer.v1.GetPetRequest
	(*ListPetsRequest)(nil),           // 3: moego.business.customer.v1.ListPetsRequest
	(*ListPetsResponse)(nil),          // 4: moego.business.customer.v1.ListPetsResponse
	(*AppendPetCodesRequest)(nil),     // 5: moego.business.customer.v1.AppendPetCodesRequest
	(*AppendPetCodesResponse)(nil),    // 6: moego.business.customer.v1.AppendPetCodesResponse
	(*AppendPetNotesRequest)(nil),     // 7: moego.business.customer.v1.AppendPetNotesRequest
	(*AppendPetNotesResponse)(nil),    // 8: moego.business.customer.v1.AppendPetNotesResponse
	(*ListPetNotesRequest)(nil),       // 9: moego.business.customer.v1.ListPetNotesRequest
	(*ListPetNotesResponse)(nil),      // 10: moego.business.customer.v1.ListPetNotesResponse
	(*ListAllPetsRequest)(nil),        // 11: moego.business.customer.v1.ListAllPetsRequest
	(*ListAllPetsResponse)(nil),       // 12: moego.business.customer.v1.ListAllPetsResponse
	(*ListAllPetsRequest_Filter)(nil), // 13: moego.business.customer.v1.ListAllPetsRequest.Filter
	(*Pet)(nil),                       // 14: moego.business.customer.v1.Pet
	(*Pet_Code)(nil),                  // 15: moego.business.customer.v1.Pet.Code
	(*Pet_Note)(nil),                  // 16: moego.business.customer.v1.Pet.Note
	(*commonpb.Pagination)(nil),       // 17: moego.common.v1.Pagination
	(*interval.Interval)(nil),         // 18: google.type.Interval
}
var file_moego_business_customer_v1_pet_service_proto_depIdxs = []int32{
	14, // 0: moego.business.customer.v1.CreatePetRequest.pet:type_name -> moego.business.customer.v1.Pet
	14, // 1: moego.business.customer.v1.CreatePetResponse.pet:type_name -> moego.business.customer.v1.Pet
	14, // 2: moego.business.customer.v1.ListPetsResponse.pets:type_name -> moego.business.customer.v1.Pet
	15, // 3: moego.business.customer.v1.AppendPetCodesResponse.codes:type_name -> moego.business.customer.v1.Pet.Code
	16, // 4: moego.business.customer.v1.AppendPetNotesRequest.notes:type_name -> moego.business.customer.v1.Pet.Note
	16, // 5: moego.business.customer.v1.AppendPetNotesResponse.notes:type_name -> moego.business.customer.v1.Pet.Note
	17, // 6: moego.business.customer.v1.ListPetNotesRequest.pagination:type_name -> moego.common.v1.Pagination
	16, // 7: moego.business.customer.v1.ListPetNotesResponse.notes:type_name -> moego.business.customer.v1.Pet.Note
	17, // 8: moego.business.customer.v1.ListAllPetsRequest.pagination:type_name -> moego.common.v1.Pagination
	13, // 9: moego.business.customer.v1.ListAllPetsRequest.filter:type_name -> moego.business.customer.v1.ListAllPetsRequest.Filter
	14, // 10: moego.business.customer.v1.ListAllPetsResponse.pets:type_name -> moego.business.customer.v1.Pet
	18, // 11: moego.business.customer.v1.ListAllPetsRequest.Filter.last_updated_time:type_name -> google.type.Interval
	0,  // 12: moego.business.customer.v1.PetService.CreatePet:input_type -> moego.business.customer.v1.CreatePetRequest
	2,  // 13: moego.business.customer.v1.PetService.GetPet:input_type -> moego.business.customer.v1.GetPetRequest
	3,  // 14: moego.business.customer.v1.PetService.ListPets:input_type -> moego.business.customer.v1.ListPetsRequest
	5,  // 15: moego.business.customer.v1.PetService.AppendPetCodes:input_type -> moego.business.customer.v1.AppendPetCodesRequest
	7,  // 16: moego.business.customer.v1.PetService.AppendPetNotes:input_type -> moego.business.customer.v1.AppendPetNotesRequest
	9,  // 17: moego.business.customer.v1.PetService.ListPetNotes:input_type -> moego.business.customer.v1.ListPetNotesRequest
	11, // 18: moego.business.customer.v1.PetService.ListAllPets:input_type -> moego.business.customer.v1.ListAllPetsRequest
	1,  // 19: moego.business.customer.v1.PetService.CreatePet:output_type -> moego.business.customer.v1.CreatePetResponse
	14, // 20: moego.business.customer.v1.PetService.GetPet:output_type -> moego.business.customer.v1.Pet
	4,  // 21: moego.business.customer.v1.PetService.ListPets:output_type -> moego.business.customer.v1.ListPetsResponse
	6,  // 22: moego.business.customer.v1.PetService.AppendPetCodes:output_type -> moego.business.customer.v1.AppendPetCodesResponse
	8,  // 23: moego.business.customer.v1.PetService.AppendPetNotes:output_type -> moego.business.customer.v1.AppendPetNotesResponse
	10, // 24: moego.business.customer.v1.PetService.ListPetNotes:output_type -> moego.business.customer.v1.ListPetNotesResponse
	12, // 25: moego.business.customer.v1.PetService.ListAllPets:output_type -> moego.business.customer.v1.ListAllPetsResponse
	19, // [19:26] is the sub-list for method output_type
	12, // [12:19] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_moego_business_customer_v1_pet_service_proto_init() }
func file_moego_business_customer_v1_pet_service_proto_init() {
	if File_moego_business_customer_v1_pet_service_proto != nil {
		return
	}
	file_moego_business_customer_v1_pet_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_moego_business_customer_v1_pet_service_proto_rawDesc), len(file_moego_business_customer_v1_pet_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_moego_business_customer_v1_pet_service_proto_goTypes,
		DependencyIndexes: file_moego_business_customer_v1_pet_service_proto_depIdxs,
		MessageInfos:      file_moego_business_customer_v1_pet_service_proto_msgTypes,
	}.Build()
	File_moego_business_customer_v1_pet_service_proto = out.File
	file_moego_business_customer_v1_pet_service_proto_goTypes = nil
	file_moego_business_customer_v1_pet_service_proto_depIdxs = nil
}
