// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             (unknown)
// source: moego/business/customer/v1/pet_note_service.proto

package customerpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	PetNoteService_CreatePetNote_FullMethodName = "/moego.business.customer.v1.PetNoteService/CreatePetNote"
	PetNoteService_PetNoteList_FullMethodName   = "/moego.business.customer.v1.PetNoteService/PetNoteList"
)

// PetNoteServiceClient is the client API for PetNoteService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PetNoteServiceClient interface {
	// TODO： Create a petNote
	CreatePetNote(ctx context.Context, in *CreatePetNoteRequest, opts ...grpc.CallOption) (*CreatePetNoteResponse, error)
	// PetNoteList
	PetNoteList(ctx context.Context, in *PetNoteListRequest, opts ...grpc.CallOption) (*PetNoteListResponse, error)
}

type petNoteServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPetNoteServiceClient(cc grpc.ClientConnInterface) PetNoteServiceClient {
	return &petNoteServiceClient{cc}
}

func (c *petNoteServiceClient) CreatePetNote(ctx context.Context, in *CreatePetNoteRequest, opts ...grpc.CallOption) (*CreatePetNoteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreatePetNoteResponse)
	err := c.cc.Invoke(ctx, PetNoteService_CreatePetNote_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *petNoteServiceClient) PetNoteList(ctx context.Context, in *PetNoteListRequest, opts ...grpc.CallOption) (*PetNoteListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PetNoteListResponse)
	err := c.cc.Invoke(ctx, PetNoteService_PetNoteList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PetNoteServiceServer is the server API for PetNoteService service.
// All implementations must embed UnimplementedPetNoteServiceServer
// for forward compatibility
type PetNoteServiceServer interface {
	// TODO： Create a petNote
	CreatePetNote(context.Context, *CreatePetNoteRequest) (*CreatePetNoteResponse, error)
	// PetNoteList
	PetNoteList(context.Context, *PetNoteListRequest) (*PetNoteListResponse, error)
	mustEmbedUnimplementedPetNoteServiceServer()
}

// UnimplementedPetNoteServiceServer must be embedded to have forward compatible implementations.
type UnimplementedPetNoteServiceServer struct {
}

func (UnimplementedPetNoteServiceServer) CreatePetNote(context.Context, *CreatePetNoteRequest) (*CreatePetNoteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreatePetNote not implemented")
}
func (UnimplementedPetNoteServiceServer) PetNoteList(context.Context, *PetNoteListRequest) (*PetNoteListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PetNoteList not implemented")
}
func (UnimplementedPetNoteServiceServer) mustEmbedUnimplementedPetNoteServiceServer() {}

// UnsafePetNoteServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PetNoteServiceServer will
// result in compilation errors.
type UnsafePetNoteServiceServer interface {
	mustEmbedUnimplementedPetNoteServiceServer()
}

func RegisterPetNoteServiceServer(s grpc.ServiceRegistrar, srv PetNoteServiceServer) {
	s.RegisterService(&PetNoteService_ServiceDesc, srv)
}

func _PetNoteService_CreatePetNote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePetNoteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PetNoteServiceServer).CreatePetNote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PetNoteService_CreatePetNote_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PetNoteServiceServer).CreatePetNote(ctx, req.(*CreatePetNoteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PetNoteService_PetNoteList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PetNoteListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PetNoteServiceServer).PetNoteList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PetNoteService_PetNoteList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PetNoteServiceServer).PetNoteList(ctx, req.(*PetNoteListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PetNoteService_ServiceDesc is the grpc.ServiceDesc for PetNoteService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PetNoteService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "moego.business.customer.v1.PetNoteService",
	HandlerType: (*PetNoteServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreatePetNote",
			Handler:    _PetNoteService_CreatePetNote_Handler,
		},
		{
			MethodName: "PetNoteList",
			Handler:    _PetNoteService_PetNoteList_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "moego/business/customer/v1/pet_note_service.proto",
}
