// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: moego/business/customer/v1/pet_service.proto

package customerpb

import (
	settingpb "github.com/MoeGolibrary/moegoapis/genproto/go/business/setting/v1/settingpb"
	commonpb "github.com/MoeGolibrary/moegoapis/genproto/go/common/v1/commonpb"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	date "google.golang.org/genproto/googleapis/type/date"
	interval "google.golang.org/genproto/googleapis/type/interval"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request message for creating a new pet profile.
type CreatePetRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID of the customer who owns the pet
	// Required. Must be a valid customer ID
	CustomerId string `protobuf:"bytes,1,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	// Complete pet information to be created
	// Required. Must include all required pet fields
	Pet           *Pet `protobuf:"bytes,2,opt,name=pet,proto3" json:"pet,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePetRequest) Reset() {
	*x = CreatePetRequest{}
	mi := &file_moego_business_customer_v1_pet_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePetRequest) ProtoMessage() {}

func (x *CreatePetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_moego_business_customer_v1_pet_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePetRequest.ProtoReflect.Descriptor instead.
func (*CreatePetRequest) Descriptor() ([]byte, []int) {
	return file_moego_business_customer_v1_pet_service_proto_rawDescGZIP(), []int{0}
}

func (x *CreatePetRequest) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *CreatePetRequest) GetPet() *Pet {
	if x != nil {
		return x.Pet
	}
	return nil
}

// Response message for creating a new pet profile.
type CreatePetResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The newly created pet profile
	// Includes system-generated fields like ID
	Pet           *Pet `protobuf:"bytes,1,opt,name=pet,proto3" json:"pet,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePetResponse) Reset() {
	*x = CreatePetResponse{}
	mi := &file_moego_business_customer_v1_pet_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePetResponse) ProtoMessage() {}

func (x *CreatePetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_moego_business_customer_v1_pet_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePetResponse.ProtoReflect.Descriptor instead.
func (*CreatePetResponse) Descriptor() ([]byte, []int) {
	return file_moego_business_customer_v1_pet_service_proto_rawDescGZIP(), []int{1}
}

func (x *CreatePetResponse) GetPet() *Pet {
	if x != nil {
		return x.Pet
	}
	return nil
}

// Request message for updating a pet's profile.
type UpdatePetRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID of the customer who owns the pet
	// Required. Must be a valid customer ID
	CustomerId string `protobuf:"bytes,1,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	// Unique identifier for the pet
	// Format: "pet_" followed by random characters
	Id string `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	// Pet's given name
	// Optional. If not provided, current value will be retained
	Name *string `protobuf:"bytes,3,opt,name=name,proto3,oneof" json:"name,omitempty"`
	// Pet's date of birth
	// Optional. If not provided, current value will be retained
	Birthday *date.Date `protobuf:"bytes,4,opt,name=birthday,proto3,oneof" json:"birthday,omitempty"`
	// Species of the pet
	// Optional. If not provided, current value will be retained
	Type *Pet_Type `protobuf:"varint,5,opt,name=type,proto3,enum=moego.business.customer.v1.Pet_Type,oneof" json:"type,omitempty"`
	// Specific breed within the pet type
	// Optional. If not provided, current value will be retained
	Breed *string `protobuf:"bytes,6,opt,name=breed,proto3,oneof" json:"breed,omitempty"`
	// Pet's gender
	// Optional. If not provided, current value will be retained
	Gender *Pet_Gender `protobuf:"varint,7,opt,name=gender,proto3,enum=moego.business.customer.v1.Pet_Gender,oneof" json:"gender,omitempty"`
	// Pet's current weight
	// Optional. If not provided, current value will be retained
	Weight *commonpb.Weight `protobuf:"bytes,8,opt,name=weight,proto3,oneof" json:"weight,omitempty"`
	// Spay/neuter status
	// Values: "yes", "no", "unknown"
	// Optional. If not provided, current value will be retained
	Fixed *string `protobuf:"bytes,9,opt,name=fixed,proto3,oneof" json:"fixed,omitempty"`
	// Description of the pet's coat
	// Example: "long double coat", "short hair"
	// Optional. If not provided, current value will be retained
	Coat *string `protobuf:"bytes,10,opt,name=coat,proto3,oneof" json:"coat,omitempty"`
	// General temperament and behavior notes
	// Example: "friendly", "nervous with new people"
	// Optional. If not provided, current value will be retained
	Behavior *string `protobuf:"bytes,11,opt,name=behavior,proto3,oneof" json:"behavior,omitempty"`
	// Primary veterinary care provider
	// Used for emergencies and health verifications
	// Optional. If not provided, current value will be retained
	Vet *Pet_Vet `protobuf:"bytes,12,opt,name=vet,proto3,oneof" json:"vet,omitempty"`
	// Current evaluation status for services
	// Determines service availability
	EvaluationStatus *Pet_EvaluationStatus `protobuf:"varint,13,opt,name=evaluation_status,json=evaluationStatus,proto3,enum=moego.business.customer.v1.Pet_EvaluationStatus,oneof" json:"evaluation_status,omitempty"`
	// photo url of pet.
	Photo *string `protobuf:"bytes,14,opt,name=photo,proto3,oneof" json:"photo,omitempty"`
	// Current vaccination records
	// Optional. If not provided, current value will be retained
	Vaccinations  []*Pet_Vaccination `protobuf:"bytes,15,rep,name=vaccinations,proto3" json:"vaccinations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePetRequest) Reset() {
	*x = UpdatePetRequest{}
	mi := &file_moego_business_customer_v1_pet_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePetRequest) ProtoMessage() {}

func (x *UpdatePetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_moego_business_customer_v1_pet_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePetRequest.ProtoReflect.Descriptor instead.
func (*UpdatePetRequest) Descriptor() ([]byte, []int) {
	return file_moego_business_customer_v1_pet_service_proto_rawDescGZIP(), []int{2}
}

func (x *UpdatePetRequest) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *UpdatePetRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdatePetRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *UpdatePetRequest) GetBirthday() *date.Date {
	if x != nil {
		return x.Birthday
	}
	return nil
}

func (x *UpdatePetRequest) GetType() Pet_Type {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return Pet_TYPE_UNSPECIFIED
}

func (x *UpdatePetRequest) GetBreed() string {
	if x != nil && x.Breed != nil {
		return *x.Breed
	}
	return ""
}

func (x *UpdatePetRequest) GetGender() Pet_Gender {
	if x != nil && x.Gender != nil {
		return *x.Gender
	}
	return Pet_GENDER_UNSPECIFIED
}

func (x *UpdatePetRequest) GetWeight() *commonpb.Weight {
	if x != nil {
		return x.Weight
	}
	return nil
}

func (x *UpdatePetRequest) GetFixed() string {
	if x != nil && x.Fixed != nil {
		return *x.Fixed
	}
	return ""
}

func (x *UpdatePetRequest) GetCoat() string {
	if x != nil && x.Coat != nil {
		return *x.Coat
	}
	return ""
}

func (x *UpdatePetRequest) GetBehavior() string {
	if x != nil && x.Behavior != nil {
		return *x.Behavior
	}
	return ""
}

func (x *UpdatePetRequest) GetVet() *Pet_Vet {
	if x != nil {
		return x.Vet
	}
	return nil
}

func (x *UpdatePetRequest) GetEvaluationStatus() Pet_EvaluationStatus {
	if x != nil && x.EvaluationStatus != nil {
		return *x.EvaluationStatus
	}
	return Pet_EVALUATION_STATUS_UNSPECIFIED
}

func (x *UpdatePetRequest) GetPhoto() string {
	if x != nil && x.Photo != nil {
		return *x.Photo
	}
	return ""
}

func (x *UpdatePetRequest) GetVaccinations() []*Pet_Vaccination {
	if x != nil {
		return x.Vaccinations
	}
	return nil
}

// Request message for retrieving a specific pet.
type GetPetRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID of the customer who owns the pet
	// Required. Must be a valid customer ID
	CustomerId string `protobuf:"bytes,1,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	// Unique identifier of the pet to retrieve
	// Required. Format: "pet_" followed by random characters
	Id            string `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPetRequest) Reset() {
	*x = GetPetRequest{}
	mi := &file_moego_business_customer_v1_pet_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPetRequest) ProtoMessage() {}

func (x *GetPetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_moego_business_customer_v1_pet_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPetRequest.ProtoReflect.Descriptor instead.
func (*GetPetRequest) Descriptor() ([]byte, []int) {
	return file_moego_business_customer_v1_pet_service_proto_rawDescGZIP(), []int{3}
}

func (x *GetPetRequest) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *GetPetRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// Request message for listing a customer's pets.
type ListPetsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID of the customer whose pets to list
	// Required. Must be a valid customer ID
	CustomerId    string `protobuf:"bytes,1,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPetsRequest) Reset() {
	*x = ListPetsRequest{}
	mi := &file_moego_business_customer_v1_pet_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPetsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPetsRequest) ProtoMessage() {}

func (x *ListPetsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_moego_business_customer_v1_pet_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPetsRequest.ProtoReflect.Descriptor instead.
func (*ListPetsRequest) Descriptor() ([]byte, []int) {
	return file_moego_business_customer_v1_pet_service_proto_rawDescGZIP(), []int{4}
}

func (x *ListPetsRequest) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

// Response message for listing a customer's pets.
type ListPetsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// List of pets belonging to the customer
	// May be empty if the customer has no pets
	Pets          []*Pet `protobuf:"bytes,1,rep,name=pets,proto3" json:"pets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPetsResponse) Reset() {
	*x = ListPetsResponse{}
	mi := &file_moego_business_customer_v1_pet_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPetsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPetsResponse) ProtoMessage() {}

func (x *ListPetsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_moego_business_customer_v1_pet_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPetsResponse.ProtoReflect.Descriptor instead.
func (*ListPetsResponse) Descriptor() ([]byte, []int) {
	return file_moego_business_customer_v1_pet_service_proto_rawDescGZIP(), []int{5}
}

func (x *ListPetsResponse) GetPets() []*Pet {
	if x != nil {
		return x.Pets
	}
	return nil
}

// Request message for adding codes to a pet's profile.
type AppendPetCodesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID of the customer who owns the pet
	// Required. Must be a valid customer ID
	CustomerId string `protobuf:"bytes,1,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	// Unique identifier of the pet
	// Required. Format: "pet_" followed by random characters
	Id string `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	// IDs of the codes to add to the pet's profile
	// Required. Must be valid code IDs
	PetCodeIds    []string `protobuf:"bytes,3,rep,name=pet_code_ids,json=petCodeIds,proto3" json:"pet_code_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppendPetCodesRequest) Reset() {
	*x = AppendPetCodesRequest{}
	mi := &file_moego_business_customer_v1_pet_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppendPetCodesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendPetCodesRequest) ProtoMessage() {}

func (x *AppendPetCodesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_moego_business_customer_v1_pet_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendPetCodesRequest.ProtoReflect.Descriptor instead.
func (*AppendPetCodesRequest) Descriptor() ([]byte, []int) {
	return file_moego_business_customer_v1_pet_service_proto_rawDescGZIP(), []int{6}
}

func (x *AppendPetCodesRequest) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *AppendPetCodesRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AppendPetCodesRequest) GetPetCodeIds() []string {
	if x != nil {
		return x.PetCodeIds
	}
	return nil
}

// Response message for adding codes to a pet's profile.
type AppendPetCodesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Codes that were successfully added
	// Includes full code details
	Codes         []*settingpb.PetCode `protobuf:"bytes,1,rep,name=codes,proto3" json:"codes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppendPetCodesResponse) Reset() {
	*x = AppendPetCodesResponse{}
	mi := &file_moego_business_customer_v1_pet_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppendPetCodesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendPetCodesResponse) ProtoMessage() {}

func (x *AppendPetCodesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_moego_business_customer_v1_pet_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendPetCodesResponse.ProtoReflect.Descriptor instead.
func (*AppendPetCodesResponse) Descriptor() ([]byte, []int) {
	return file_moego_business_customer_v1_pet_service_proto_rawDescGZIP(), []int{7}
}

func (x *AppendPetCodesResponse) GetCodes() []*settingpb.PetCode {
	if x != nil {
		return x.Codes
	}
	return nil
}

// Request message for adding notes to a pet's profile.
type AppendPetNotesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID of the customer who owns the pet
	// Required. Must be a valid customer ID
	CustomerId string `protobuf:"bytes,1,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	// Unique identifier of the pet
	// Required. Format: "pet_" followed by random characters
	Id string `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	// Notes to add to the pet's profile
	// Required. At least one note must be provided
	Notes         []*Pet_Note `protobuf:"bytes,3,rep,name=notes,proto3" json:"notes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppendPetNotesRequest) Reset() {
	*x = AppendPetNotesRequest{}
	mi := &file_moego_business_customer_v1_pet_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppendPetNotesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendPetNotesRequest) ProtoMessage() {}

func (x *AppendPetNotesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_moego_business_customer_v1_pet_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendPetNotesRequest.ProtoReflect.Descriptor instead.
func (*AppendPetNotesRequest) Descriptor() ([]byte, []int) {
	return file_moego_business_customer_v1_pet_service_proto_rawDescGZIP(), []int{8}
}

func (x *AppendPetNotesRequest) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *AppendPetNotesRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AppendPetNotesRequest) GetNotes() []*Pet_Note {
	if x != nil {
		return x.Notes
	}
	return nil
}

// Response message for adding notes to a pet's profile.
type AppendPetNotesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Notes that were successfully added
	// Includes generated IDs and timestamps
	Notes         []*Pet_Note `protobuf:"bytes,1,rep,name=notes,proto3" json:"notes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppendPetNotesResponse) Reset() {
	*x = AppendPetNotesResponse{}
	mi := &file_moego_business_customer_v1_pet_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppendPetNotesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendPetNotesResponse) ProtoMessage() {}

func (x *AppendPetNotesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_moego_business_customer_v1_pet_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendPetNotesResponse.ProtoReflect.Descriptor instead.
func (*AppendPetNotesResponse) Descriptor() ([]byte, []int) {
	return file_moego_business_customer_v1_pet_service_proto_rawDescGZIP(), []int{9}
}

func (x *AppendPetNotesResponse) GetNotes() []*Pet_Note {
	if x != nil {
		return x.Notes
	}
	return nil
}

// Request message for listing a pet's notes.
type ListPetNotesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Pagination parameters for the request
	// Required. Defines page size and token for continuation
	Pagination *commonpb.Pagination `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
	// ID of the customer who owns the pet
	// Required. Must be a valid customer ID
	CustomerId string `protobuf:"bytes,2,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	// Unique identifier of the pet
	// Required. Format: "pet_" followed by random characters
	Id            string `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPetNotesRequest) Reset() {
	*x = ListPetNotesRequest{}
	mi := &file_moego_business_customer_v1_pet_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPetNotesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPetNotesRequest) ProtoMessage() {}

func (x *ListPetNotesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_moego_business_customer_v1_pet_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPetNotesRequest.ProtoReflect.Descriptor instead.
func (*ListPetNotesRequest) Descriptor() ([]byte, []int) {
	return file_moego_business_customer_v1_pet_service_proto_rawDescGZIP(), []int{10}
}

func (x *ListPetNotesRequest) GetPagination() *commonpb.Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *ListPetNotesRequest) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *ListPetNotesRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// Response message for listing a pet's notes.
type ListPetNotesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Token for retrieving the next page of results
	// Empty if there are no more results
	NextPageToken string `protobuf:"bytes,1,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	// List of notes for the pet
	// May be empty if the pet has no notes
	Notes         []*Pet_Note `protobuf:"bytes,2,rep,name=notes,proto3" json:"notes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPetNotesResponse) Reset() {
	*x = ListPetNotesResponse{}
	mi := &file_moego_business_customer_v1_pet_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPetNotesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPetNotesResponse) ProtoMessage() {}

func (x *ListPetNotesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_moego_business_customer_v1_pet_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPetNotesResponse.ProtoReflect.Descriptor instead.
func (*ListPetNotesResponse) Descriptor() ([]byte, []int) {
	return file_moego_business_customer_v1_pet_service_proto_rawDescGZIP(), []int{11}
}

func (x *ListPetNotesResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

func (x *ListPetNotesResponse) GetNotes() []*Pet_Note {
	if x != nil {
		return x.Notes
	}
	return nil
}

// Request message for listing all pets in the company.
type ListAllPetsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Pagination parameters for the request
	// Required. Defines page size and token for continuation
	Pagination *commonpb.Pagination `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
	// ID of the company to list pets for
	// Required. Must be a valid company ID
	CompanyId string `protobuf:"bytes,2,opt,name=company_id,json=companyId,proto3" json:"company_id,omitempty"`
	// Optional filters to apply to the pet list
	Filter        *ListAllPetsRequest_Filter `protobuf:"bytes,3,opt,name=filter,proto3" json:"filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAllPetsRequest) Reset() {
	*x = ListAllPetsRequest{}
	mi := &file_moego_business_customer_v1_pet_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAllPetsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAllPetsRequest) ProtoMessage() {}

func (x *ListAllPetsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_moego_business_customer_v1_pet_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAllPetsRequest.ProtoReflect.Descriptor instead.
func (*ListAllPetsRequest) Descriptor() ([]byte, []int) {
	return file_moego_business_customer_v1_pet_service_proto_rawDescGZIP(), []int{12}
}

func (x *ListAllPetsRequest) GetPagination() *commonpb.Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *ListAllPetsRequest) GetCompanyId() string {
	if x != nil {
		return x.CompanyId
	}
	return ""
}

func (x *ListAllPetsRequest) GetFilter() *ListAllPetsRequest_Filter {
	if x != nil {
		return x.Filter
	}
	return nil
}

// Response message for listing all pets.
type ListAllPetsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Token for retrieving the next page of results
	// Empty if there are no more results
	NextPageToken string `protobuf:"bytes,1,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	// List of pets matching the request criteria
	// May be empty if no pets match
	Pets          []*Pet `protobuf:"bytes,2,rep,name=pets,proto3" json:"pets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAllPetsResponse) Reset() {
	*x = ListAllPetsResponse{}
	mi := &file_moego_business_customer_v1_pet_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAllPetsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAllPetsResponse) ProtoMessage() {}

func (x *ListAllPetsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_moego_business_customer_v1_pet_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAllPetsResponse.ProtoReflect.Descriptor instead.
func (*ListAllPetsResponse) Descriptor() ([]byte, []int) {
	return file_moego_business_customer_v1_pet_service_proto_rawDescGZIP(), []int{13}
}

func (x *ListAllPetsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

func (x *ListAllPetsResponse) GetPets() []*Pet {
	if x != nil {
		return x.Pets
	}
	return nil
}

// Filter parameters for the pet list
type ListAllPetsRequest_Filter struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional list of customer IDs to filter by
	// If provided, only returns pets belonging to these customers
	CustomerIds []string `protobuf:"bytes,1,rep,name=customer_ids,json=customerIds,proto3" json:"customer_ids,omitempty"`
	// Optional list of time intervals to filter by
	// If provided, only returns pets with appointments within these intervals
	LastUpdatedTime *interval.Interval `protobuf:"bytes,2,opt,name=last_updated_time,json=lastUpdatedTime,proto3" json:"last_updated_time,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ListAllPetsRequest_Filter) Reset() {
	*x = ListAllPetsRequest_Filter{}
	mi := &file_moego_business_customer_v1_pet_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAllPetsRequest_Filter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAllPetsRequest_Filter) ProtoMessage() {}

func (x *ListAllPetsRequest_Filter) ProtoReflect() protoreflect.Message {
	mi := &file_moego_business_customer_v1_pet_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAllPetsRequest_Filter.ProtoReflect.Descriptor instead.
func (*ListAllPetsRequest_Filter) Descriptor() ([]byte, []int) {
	return file_moego_business_customer_v1_pet_service_proto_rawDescGZIP(), []int{12, 0}
}

func (x *ListAllPetsRequest_Filter) GetCustomerIds() []string {
	if x != nil {
		return x.CustomerIds
	}
	return nil
}

func (x *ListAllPetsRequest_Filter) GetLastUpdatedTime() *interval.Interval {
	if x != nil {
		return x.LastUpdatedTime
	}
	return nil
}

var File_moego_business_customer_v1_pet_service_proto protoreflect.FileDescriptor

const file_moego_business_customer_v1_pet_service_proto_rawDesc = "" +
	"\n" +
	",moego/business/customer/v1/pet_service.proto\x12\x1amoego.business.customer.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x16google/type/date.proto\x1a\x1agoogle/type/interval.proto\x1a$moego/business/customer/v1/pet.proto\x1a#moego/business/setting/v1/pet.proto\x1a moego/common/v1/pagination.proto\x1a\x1cmoego/common/v1/weight.proto\"p\n" +
	"\x10CreatePetRequest\x12$\n" +
	"\vcustomer_id\x18\x01 \x01(\tB\x03\xe0A\x02R\n" +
	"customerId\x126\n" +
	"\x03pet\x18\x02 \x01(\v2\x1f.moego.business.customer.v1.PetB\x03\xe0A\x02R\x03pet\"K\n" +
	"\x11CreatePetResponse\x126\n" +
	"\x03pet\x18\x01 \x01(\v2\x1f.moego.business.customer.v1.PetB\x03\xe0A\x03R\x03pet\"\xd7\x06\n" +
	"\x10UpdatePetRequest\x12$\n" +
	"\vcustomer_id\x18\x01 \x01(\tB\x03\xe0A\x02R\n" +
	"customerId\x12\x13\n" +
	"\x02id\x18\x02 \x01(\tB\x03\xe0A\x02R\x02id\x12\x17\n" +
	"\x04name\x18\x03 \x01(\tH\x00R\x04name\x88\x01\x01\x122\n" +
	"\bbirthday\x18\x04 \x01(\v2\x11.google.type.DateH\x01R\bbirthday\x88\x01\x01\x12=\n" +
	"\x04type\x18\x05 \x01(\x0e2$.moego.business.customer.v1.Pet.TypeH\x02R\x04type\x88\x01\x01\x12\x19\n" +
	"\x05breed\x18\x06 \x01(\tH\x03R\x05breed\x88\x01\x01\x12C\n" +
	"\x06gender\x18\a \x01(\x0e2&.moego.business.customer.v1.Pet.GenderH\x04R\x06gender\x88\x01\x01\x124\n" +
	"\x06weight\x18\b \x01(\v2\x17.moego.common.v1.WeightH\x05R\x06weight\x88\x01\x01\x12\x19\n" +
	"\x05fixed\x18\t \x01(\tH\x06R\x05fixed\x88\x01\x01\x12\x17\n" +
	"\x04coat\x18\n" +
	" \x01(\tH\aR\x04coat\x88\x01\x01\x12\x1f\n" +
	"\bbehavior\x18\v \x01(\tH\bR\bbehavior\x88\x01\x01\x12:\n" +
	"\x03vet\x18\f \x01(\v2#.moego.business.customer.v1.Pet.VetH\tR\x03vet\x88\x01\x01\x12b\n" +
	"\x11evaluation_status\x18\r \x01(\x0e20.moego.business.customer.v1.Pet.EvaluationStatusH\n" +
	"R\x10evaluationStatus\x88\x01\x01\x12\x19\n" +
	"\x05photo\x18\x0e \x01(\tH\vR\x05photo\x88\x01\x01\x12O\n" +
	"\fvaccinations\x18\x0f \x03(\v2+.moego.business.customer.v1.Pet.VaccinationR\fvaccinationsB\a\n" +
	"\x05_nameB\v\n" +
	"\t_birthdayB\a\n" +
	"\x05_typeB\b\n" +
	"\x06_breedB\t\n" +
	"\a_genderB\t\n" +
	"\a_weightB\b\n" +
	"\x06_fixedB\a\n" +
	"\x05_coatB\v\n" +
	"\t_behaviorB\x06\n" +
	"\x04_vetB\x14\n" +
	"\x12_evaluation_statusB\b\n" +
	"\x06_photo\"J\n" +
	"\rGetPetRequest\x12$\n" +
	"\vcustomer_id\x18\x01 \x01(\tB\x03\xe0A\x02R\n" +
	"customerId\x12\x13\n" +
	"\x02id\x18\x02 \x01(\tB\x03\xe0A\x02R\x02id\"7\n" +
	"\x0fListPetsRequest\x12$\n" +
	"\vcustomer_id\x18\x01 \x01(\tB\x03\xe0A\x02R\n" +
	"customerId\"G\n" +
	"\x10ListPetsResponse\x123\n" +
	"\x04pets\x18\x01 \x03(\v2\x1f.moego.business.customer.v1.PetR\x04pets\"y\n" +
	"\x15AppendPetCodesRequest\x12$\n" +
	"\vcustomer_id\x18\x01 \x01(\tB\x03\xe0A\x02R\n" +
	"customerId\x12\x13\n" +
	"\x02id\x18\x02 \x01(\tB\x03\xe0A\x02R\x02id\x12%\n" +
	"\fpet_code_ids\x18\x03 \x03(\tB\x03\xe0A\x02R\n" +
	"petCodeIds\"W\n" +
	"\x16AppendPetCodesResponse\x12=\n" +
	"\x05codes\x18\x01 \x03(\v2\".moego.business.setting.v1.PetCodeB\x03\xe0A\x03R\x05codes\"\x8e\x01\n" +
	"\x15AppendPetNotesRequest\x12$\n" +
	"\vcustomer_id\x18\x01 \x01(\tB\x03\xe0A\x02R\n" +
	"customerId\x12\x13\n" +
	"\x02id\x18\x02 \x01(\tB\x03\xe0A\x02R\x02id\x12:\n" +
	"\x05notes\x18\x03 \x03(\v2$.moego.business.customer.v1.Pet.NoteR\x05notes\"T\n" +
	"\x16AppendPetNotesResponse\x12:\n" +
	"\x05notes\x18\x01 \x03(\v2$.moego.business.customer.v1.Pet.NoteR\x05notes\"\x92\x01\n" +
	"\x13ListPetNotesRequest\x12@\n" +
	"\n" +
	"pagination\x18\x01 \x01(\v2\x1b.moego.common.v1.PaginationB\x03\xe0A\x02R\n" +
	"pagination\x12$\n" +
	"\vcustomer_id\x18\x02 \x01(\tB\x03\xe0A\x02R\n" +
	"customerId\x12\x13\n" +
	"\x02id\x18\x03 \x01(\tB\x03\xe0A\x02R\x02id\"z\n" +
	"\x14ListPetNotesResponse\x12&\n" +
	"\x0fnext_page_token\x18\x01 \x01(\tR\rnextPageToken\x12:\n" +
	"\x05notes\x18\x02 \x03(\v2$.moego.business.customer.v1.Pet.NoteR\x05notes\"\xc3\x02\n" +
	"\x12ListAllPetsRequest\x12@\n" +
	"\n" +
	"pagination\x18\x01 \x01(\v2\x1b.moego.common.v1.PaginationB\x03\xe0A\x02R\n" +
	"pagination\x12\"\n" +
	"\n" +
	"company_id\x18\x02 \x01(\tB\x03\xe0A\x02R\tcompanyId\x12M\n" +
	"\x06filter\x18\x03 \x01(\v25.moego.business.customer.v1.ListAllPetsRequest.FilterR\x06filter\x1ax\n" +
	"\x06Filter\x12&\n" +
	"\fcustomer_ids\x18\x01 \x03(\tB\x03\xe0A\x01R\vcustomerIds\x12F\n" +
	"\x11last_updated_time\x18\x02 \x01(\v2\x15.google.type.IntervalB\x03\xe0A\x01R\x0flastUpdatedTime\"r\n" +
	"\x13ListAllPetsResponse\x12&\n" +
	"\x0fnext_page_token\x18\x01 \x01(\tR\rnextPageToken\x123\n" +
	"\x04pets\x18\x02 \x03(\v2\x1f.moego.business.customer.v1.PetR\x04pets2\xf3\t\n" +
	"\n" +
	"PetService\x12\x95\x01\n" +
	"\tCreatePet\x12,.moego.business.customer.v1.CreatePetRequest\x1a-.moego.business.customer.v1.CreatePetResponse\"+\x82\xd3\xe4\x93\x02%:\x01*\" /v1/customers/{customer_id}/pets\x12\x8c\x01\n" +
	"\tUpdatePet\x12,.moego.business.customer.v1.UpdatePetRequest\x1a\x1f.moego.business.customer.v1.Pet\"0\x82\xd3\xe4\x93\x02*:\x01*\x1a%/v1/customers/{customer_id}/pets/{id}\x12\x83\x01\n" +
	"\x06GetPet\x12).moego.business.customer.v1.GetPetRequest\x1a\x1f.moego.business.customer.v1.Pet\"-\x82\xd3\xe4\x93\x02'\x12%/v1/customers/{customer_id}/pets/{id}\x12\x97\x01\n" +
	"\bListPets\x12+.moego.business.customer.v1.ListPetsRequest\x1a,.moego.business.customer.v1.ListPetsResponse\"0\x82\xd3\xe4\x93\x02*:\x01*\"%/v1/customers/{customer_id}/pets:list\x12\xaf\x01\n" +
	"\x0eAppendPetCodes\x121.moego.business.customer.v1.AppendPetCodesRequest\x1a2.moego.business.customer.v1.AppendPetCodesResponse\"6\x82\xd3\xe4\x93\x020:\x01*\"+/v1/customers/{customer_id}/pets/{id}/codes\x12\xaf\x01\n" +
	"\x0eAppendPetNotes\x121.moego.business.customer.v1.AppendPetNotesRequest\x1a2.moego.business.customer.v1.AppendPetNotesResponse\"6\x82\xd3\xe4\x93\x020:\x01*\"+/v1/customers/{customer_id}/pets/{id}/notes\x12\xae\x01\n" +
	"\fListPetNotes\x12/.moego.business.customer.v1.ListPetNotesRequest\x1a0.moego.business.customer.v1.ListPetNotesResponse\";\x82\xd3\xe4\x93\x025:\x01*\"0/v1/customers/{customer_id}/pets/{id}/notes:list\x12\x88\x01\n" +
	"\vListAllPets\x12..moego.business.customer.v1.ListAllPetsRequest\x1a/.moego.business.customer.v1.ListAllPetsResponse\"\x18\x82\xd3\xe4\x93\x02\x12:\x01*\"\r/v1/pets:listB\x96\x01\n" +
	"\"com.moego.api.business.customer.v1B\x14CustomerServiceProtoP\x01ZXgithub.com/MoeGolibrary/moegoapis/genproto/go/business/customer/v1/customerpb;customerpbb\x06proto3"

var (
	file_moego_business_customer_v1_pet_service_proto_rawDescOnce sync.Once
	file_moego_business_customer_v1_pet_service_proto_rawDescData []byte
)

func file_moego_business_customer_v1_pet_service_proto_rawDescGZIP() []byte {
	file_moego_business_customer_v1_pet_service_proto_rawDescOnce.Do(func() {
		file_moego_business_customer_v1_pet_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_moego_business_customer_v1_pet_service_proto_rawDesc), len(file_moego_business_customer_v1_pet_service_proto_rawDesc)))
	})
	return file_moego_business_customer_v1_pet_service_proto_rawDescData
}

var file_moego_business_customer_v1_pet_service_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_moego_business_customer_v1_pet_service_proto_goTypes = []any{
	(*CreatePetRequest)(nil),          // 0: moego.business.customer.v1.CreatePetRequest
	(*CreatePetResponse)(nil),         // 1: moego.business.customer.v1.CreatePetResponse
	(*UpdatePetRequest)(nil),          // 2: moego.business.customer.v1.UpdatePetRequest
	(*GetPetRequest)(nil),             // 3: moego.business.customer.v1.GetPetRequest
	(*ListPetsRequest)(nil),           // 4: moego.business.customer.v1.ListPetsRequest
	(*ListPetsResponse)(nil),          // 5: moego.business.customer.v1.ListPetsResponse
	(*AppendPetCodesRequest)(nil),     // 6: moego.business.customer.v1.AppendPetCodesRequest
	(*AppendPetCodesResponse)(nil),    // 7: moego.business.customer.v1.AppendPetCodesResponse
	(*AppendPetNotesRequest)(nil),     // 8: moego.business.customer.v1.AppendPetNotesRequest
	(*AppendPetNotesResponse)(nil),    // 9: moego.business.customer.v1.AppendPetNotesResponse
	(*ListPetNotesRequest)(nil),       // 10: moego.business.customer.v1.ListPetNotesRequest
	(*ListPetNotesResponse)(nil),      // 11: moego.business.customer.v1.ListPetNotesResponse
	(*ListAllPetsRequest)(nil),        // 12: moego.business.customer.v1.ListAllPetsRequest
	(*ListAllPetsResponse)(nil),       // 13: moego.business.customer.v1.ListAllPetsResponse
	(*ListAllPetsRequest_Filter)(nil), // 14: moego.business.customer.v1.ListAllPetsRequest.Filter
	(*Pet)(nil),                       // 15: moego.business.customer.v1.Pet
	(*date.Date)(nil),                 // 16: google.type.Date
	(Pet_Type)(0),                     // 17: moego.business.customer.v1.Pet.Type
	(Pet_Gender)(0),                   // 18: moego.business.customer.v1.Pet.Gender
	(*commonpb.Weight)(nil),           // 19: moego.common.v1.Weight
	(*Pet_Vet)(nil),                   // 20: moego.business.customer.v1.Pet.Vet
	(Pet_EvaluationStatus)(0),         // 21: moego.business.customer.v1.Pet.EvaluationStatus
	(*Pet_Vaccination)(nil),           // 22: moego.business.customer.v1.Pet.Vaccination
	(*settingpb.PetCode)(nil),         // 23: moego.business.setting.v1.PetCode
	(*Pet_Note)(nil),                  // 24: moego.business.customer.v1.Pet.Note
	(*commonpb.Pagination)(nil),       // 25: moego.common.v1.Pagination
	(*interval.Interval)(nil),         // 26: google.type.Interval
}
var file_moego_business_customer_v1_pet_service_proto_depIdxs = []int32{
	15, // 0: moego.business.customer.v1.CreatePetRequest.pet:type_name -> moego.business.customer.v1.Pet
	15, // 1: moego.business.customer.v1.CreatePetResponse.pet:type_name -> moego.business.customer.v1.Pet
	16, // 2: moego.business.customer.v1.UpdatePetRequest.birthday:type_name -> google.type.Date
	17, // 3: moego.business.customer.v1.UpdatePetRequest.type:type_name -> moego.business.customer.v1.Pet.Type
	18, // 4: moego.business.customer.v1.UpdatePetRequest.gender:type_name -> moego.business.customer.v1.Pet.Gender
	19, // 5: moego.business.customer.v1.UpdatePetRequest.weight:type_name -> moego.common.v1.Weight
	20, // 6: moego.business.customer.v1.UpdatePetRequest.vet:type_name -> moego.business.customer.v1.Pet.Vet
	21, // 7: moego.business.customer.v1.UpdatePetRequest.evaluation_status:type_name -> moego.business.customer.v1.Pet.EvaluationStatus
	22, // 8: moego.business.customer.v1.UpdatePetRequest.vaccinations:type_name -> moego.business.customer.v1.Pet.Vaccination
	15, // 9: moego.business.customer.v1.ListPetsResponse.pets:type_name -> moego.business.customer.v1.Pet
	23, // 10: moego.business.customer.v1.AppendPetCodesResponse.codes:type_name -> moego.business.setting.v1.PetCode
	24, // 11: moego.business.customer.v1.AppendPetNotesRequest.notes:type_name -> moego.business.customer.v1.Pet.Note
	24, // 12: moego.business.customer.v1.AppendPetNotesResponse.notes:type_name -> moego.business.customer.v1.Pet.Note
	25, // 13: moego.business.customer.v1.ListPetNotesRequest.pagination:type_name -> moego.common.v1.Pagination
	24, // 14: moego.business.customer.v1.ListPetNotesResponse.notes:type_name -> moego.business.customer.v1.Pet.Note
	25, // 15: moego.business.customer.v1.ListAllPetsRequest.pagination:type_name -> moego.common.v1.Pagination
	14, // 16: moego.business.customer.v1.ListAllPetsRequest.filter:type_name -> moego.business.customer.v1.ListAllPetsRequest.Filter
	15, // 17: moego.business.customer.v1.ListAllPetsResponse.pets:type_name -> moego.business.customer.v1.Pet
	26, // 18: moego.business.customer.v1.ListAllPetsRequest.Filter.last_updated_time:type_name -> google.type.Interval
	0,  // 19: moego.business.customer.v1.PetService.CreatePet:input_type -> moego.business.customer.v1.CreatePetRequest
	2,  // 20: moego.business.customer.v1.PetService.UpdatePet:input_type -> moego.business.customer.v1.UpdatePetRequest
	3,  // 21: moego.business.customer.v1.PetService.GetPet:input_type -> moego.business.customer.v1.GetPetRequest
	4,  // 22: moego.business.customer.v1.PetService.ListPets:input_type -> moego.business.customer.v1.ListPetsRequest
	6,  // 23: moego.business.customer.v1.PetService.AppendPetCodes:input_type -> moego.business.customer.v1.AppendPetCodesRequest
	8,  // 24: moego.business.customer.v1.PetService.AppendPetNotes:input_type -> moego.business.customer.v1.AppendPetNotesRequest
	10, // 25: moego.business.customer.v1.PetService.ListPetNotes:input_type -> moego.business.customer.v1.ListPetNotesRequest
	12, // 26: moego.business.customer.v1.PetService.ListAllPets:input_type -> moego.business.customer.v1.ListAllPetsRequest
	1,  // 27: moego.business.customer.v1.PetService.CreatePet:output_type -> moego.business.customer.v1.CreatePetResponse
	15, // 28: moego.business.customer.v1.PetService.UpdatePet:output_type -> moego.business.customer.v1.Pet
	15, // 29: moego.business.customer.v1.PetService.GetPet:output_type -> moego.business.customer.v1.Pet
	5,  // 30: moego.business.customer.v1.PetService.ListPets:output_type -> moego.business.customer.v1.ListPetsResponse
	7,  // 31: moego.business.customer.v1.PetService.AppendPetCodes:output_type -> moego.business.customer.v1.AppendPetCodesResponse
	9,  // 32: moego.business.customer.v1.PetService.AppendPetNotes:output_type -> moego.business.customer.v1.AppendPetNotesResponse
	11, // 33: moego.business.customer.v1.PetService.ListPetNotes:output_type -> moego.business.customer.v1.ListPetNotesResponse
	13, // 34: moego.business.customer.v1.PetService.ListAllPets:output_type -> moego.business.customer.v1.ListAllPetsResponse
	27, // [27:35] is the sub-list for method output_type
	19, // [19:27] is the sub-list for method input_type
	19, // [19:19] is the sub-list for extension type_name
	19, // [19:19] is the sub-list for extension extendee
	0,  // [0:19] is the sub-list for field type_name
}

func init() { file_moego_business_customer_v1_pet_service_proto_init() }
func file_moego_business_customer_v1_pet_service_proto_init() {
	if File_moego_business_customer_v1_pet_service_proto != nil {
		return
	}
	file_moego_business_customer_v1_pet_proto_init()
	file_moego_business_customer_v1_pet_service_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_moego_business_customer_v1_pet_service_proto_rawDesc), len(file_moego_business_customer_v1_pet_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_moego_business_customer_v1_pet_service_proto_goTypes,
		DependencyIndexes: file_moego_business_customer_v1_pet_service_proto_depIdxs,
		MessageInfos:      file_moego_business_customer_v1_pet_service_proto_msgTypes,
	}.Build()
	File_moego_business_customer_v1_pet_service_proto = out.File
	file_moego_business_customer_v1_pet_service_proto_goTypes = nil
	file_moego_business_customer_v1_pet_service_proto_depIdxs = nil
}
