// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        (unknown)
// source: moego/business/review/v1/review_service.proto

package reviewpb

import (
	commonpb "github.com/MoeGolibrary/moegoapis/genproto/go/common/v1/commonpb"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ListReviewsRequest encapsulates parameters for retrieving customer reviews.
// Supports pagination and filtering to customize the result set based on
// business needs and analysis requirements.
type ListReviewsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Pagination parameters for handling large result sets
	// Required to manage data volume efficiently
	Pagination *commonpb.Pagination `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
	// Business location identifier for scoping reviews
	// Required to ensure reviews are accessed within proper context
	BusinessId string `protobuf:"bytes,2,opt,name=business_id,json=businessId,proto3" json:"business_id,omitempty"`
	// Filter criteria to apply to the review list
	// Optional. If not provided, returns all reviews
	Filter        *ListReviewsRequest_Filter `protobuf:"bytes,3,opt,name=filter,proto3" json:"filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListReviewsRequest) Reset() {
	*x = ListReviewsRequest{}
	mi := &file_moego_business_review_v1_review_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListReviewsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListReviewsRequest) ProtoMessage() {}

func (x *ListReviewsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_moego_business_review_v1_review_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListReviewsRequest.ProtoReflect.Descriptor instead.
func (*ListReviewsRequest) Descriptor() ([]byte, []int) {
	return file_moego_business_review_v1_review_service_proto_rawDescGZIP(), []int{0}
}

func (x *ListReviewsRequest) GetPagination() *commonpb.Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *ListReviewsRequest) GetBusinessId() string {
	if x != nil {
		return x.BusinessId
	}
	return ""
}

func (x *ListReviewsRequest) GetFilter() *ListReviewsRequest_Filter {
	if x != nil {
		return x.Filter
	}
	return nil
}

// ListReviewsResponse contains the paginated list of reviews and metadata.
type ListReviewsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Token for retrieving the next page of results
	// Empty if there are no more results
	NextPageToken string `protobuf:"bytes,1,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	// List of reviews matching the request criteria
	// May be empty if no reviews match the filters
	Reviews       []*Review `protobuf:"bytes,2,rep,name=reviews,proto3" json:"reviews,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListReviewsResponse) Reset() {
	*x = ListReviewsResponse{}
	mi := &file_moego_business_review_v1_review_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListReviewsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListReviewsResponse) ProtoMessage() {}

func (x *ListReviewsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_moego_business_review_v1_review_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListReviewsResponse.ProtoReflect.Descriptor instead.
func (*ListReviewsResponse) Descriptor() ([]byte, []int) {
	return file_moego_business_review_v1_review_service_proto_rawDescGZIP(), []int{1}
}

func (x *ListReviewsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

func (x *ListReviewsResponse) GetReviews() []*Review {
	if x != nil {
		return x.Reviews
	}
	return nil
}

// Filter specifies criteria for filtering the review list.
// Allows targeting specific feedback sources and staff members.
type ListReviewsRequest_Filter struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Feedback channels to include in results
	// Optional. If empty, includes reviews from all sources
	Sources []Review_Source `protobuf:"varint,1,rep,packed,name=sources,proto3,enum=moego.business.review.v1.Review_Source" json:"sources,omitempty"`
	// Staff members to filter reviews by
	// Optional. If empty, includes reviews for all staff
	StaffIds      []string `protobuf:"bytes,2,rep,name=staff_ids,json=staffIds,proto3" json:"staff_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListReviewsRequest_Filter) Reset() {
	*x = ListReviewsRequest_Filter{}
	mi := &file_moego_business_review_v1_review_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListReviewsRequest_Filter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListReviewsRequest_Filter) ProtoMessage() {}

func (x *ListReviewsRequest_Filter) ProtoReflect() protoreflect.Message {
	mi := &file_moego_business_review_v1_review_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListReviewsRequest_Filter.ProtoReflect.Descriptor instead.
func (*ListReviewsRequest_Filter) Descriptor() ([]byte, []int) {
	return file_moego_business_review_v1_review_service_proto_rawDescGZIP(), []int{0, 0}
}

func (x *ListReviewsRequest_Filter) GetSources() []Review_Source {
	if x != nil {
		return x.Sources
	}
	return nil
}

func (x *ListReviewsRequest_Filter) GetStaffIds() []string {
	if x != nil {
		return x.StaffIds
	}
	return nil
}

var File_moego_business_review_v1_review_service_proto protoreflect.FileDescriptor

const file_moego_business_review_v1_review_service_proto_rawDesc = "" +
	"\n" +
	"-moego/business/review/v1/review_service.proto\x12\x18moego.business.review.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a%moego/business/review/v1/review.proto\x1a moego/common/v1/pagination.proto\"\xbd\x02\n" +
	"\x12ListReviewsRequest\x12@\n" +
	"\n" +
	"pagination\x18\x01 \x01(\v2\x1b.moego.common.v1.PaginationB\x03\xe0A\x02R\n" +
	"pagination\x12$\n" +
	"\vbusiness_id\x18\x02 \x01(\tB\x03\xe0A\x02R\n" +
	"businessId\x12K\n" +
	"\x06filter\x18\x03 \x01(\v23.moego.business.review.v1.ListReviewsRequest.FilterR\x06filter\x1ar\n" +
	"\x06Filter\x12F\n" +
	"\asources\x18\x01 \x03(\x0e2'.moego.business.review.v1.Review.SourceB\x03\xe0A\x01R\asources\x12 \n" +
	"\tstaff_ids\x18\x02 \x03(\tB\x03\xe0A\x01R\bstaffIds\"y\n" +
	"\x13ListReviewsResponse\x12&\n" +
	"\x0fnext_page_token\x18\x01 \x01(\tR\rnextPageToken\x12:\n" +
	"\areviews\x18\x02 \x03(\v2 .moego.business.review.v1.ReviewR\areviews2\x99\x01\n" +
	"\rReviewService\x12\x87\x01\n" +
	"\vListReviews\x12,.moego.business.review.v1.ListReviewsRequest\x1a-.moego.business.review.v1.ListReviewsResponse\"\x1b\x82\xd3\xe4\x93\x02\x15:\x01*\"\x10/v1/reviews:listB\x8e\x01\n" +
	" com.moego.api.business.review.v1B\x12ReviewServiceProtoP\x01ZTgithub.com/MoeGolibrary/moegoapis/genproto/go/business/business/v1/reviewpb;reviewpbb\x06proto3"

var (
	file_moego_business_review_v1_review_service_proto_rawDescOnce sync.Once
	file_moego_business_review_v1_review_service_proto_rawDescData []byte
)

func file_moego_business_review_v1_review_service_proto_rawDescGZIP() []byte {
	file_moego_business_review_v1_review_service_proto_rawDescOnce.Do(func() {
		file_moego_business_review_v1_review_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_moego_business_review_v1_review_service_proto_rawDesc), len(file_moego_business_review_v1_review_service_proto_rawDesc)))
	})
	return file_moego_business_review_v1_review_service_proto_rawDescData
}

var file_moego_business_review_v1_review_service_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_moego_business_review_v1_review_service_proto_goTypes = []any{
	(*ListReviewsRequest)(nil),        // 0: moego.business.review.v1.ListReviewsRequest
	(*ListReviewsResponse)(nil),       // 1: moego.business.review.v1.ListReviewsResponse
	(*ListReviewsRequest_Filter)(nil), // 2: moego.business.review.v1.ListReviewsRequest.Filter
	(*commonpb.Pagination)(nil),       // 3: moego.common.v1.Pagination
	(*Review)(nil),                    // 4: moego.business.review.v1.Review
	(Review_Source)(0),                // 5: moego.business.review.v1.Review.Source
}
var file_moego_business_review_v1_review_service_proto_depIdxs = []int32{
	3, // 0: moego.business.review.v1.ListReviewsRequest.pagination:type_name -> moego.common.v1.Pagination
	2, // 1: moego.business.review.v1.ListReviewsRequest.filter:type_name -> moego.business.review.v1.ListReviewsRequest.Filter
	4, // 2: moego.business.review.v1.ListReviewsResponse.reviews:type_name -> moego.business.review.v1.Review
	5, // 3: moego.business.review.v1.ListReviewsRequest.Filter.sources:type_name -> moego.business.review.v1.Review.Source
	0, // 4: moego.business.review.v1.ReviewService.ListReviews:input_type -> moego.business.review.v1.ListReviewsRequest
	1, // 5: moego.business.review.v1.ReviewService.ListReviews:output_type -> moego.business.review.v1.ListReviewsResponse
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_moego_business_review_v1_review_service_proto_init() }
func file_moego_business_review_v1_review_service_proto_init() {
	if File_moego_business_review_v1_review_service_proto != nil {
		return
	}
	file_moego_business_review_v1_review_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_moego_business_review_v1_review_service_proto_rawDesc), len(file_moego_business_review_v1_review_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_moego_business_review_v1_review_service_proto_goTypes,
		DependencyIndexes: file_moego_business_review_v1_review_service_proto_depIdxs,
		MessageInfos:      file_moego_business_review_v1_review_service_proto_msgTypes,
	}.Build()
	File_moego_business_review_v1_review_service_proto = out.File
	file_moego_business_review_v1_review_service_proto_goTypes = nil
	file_moego_business_review_v1_review_service_proto_depIdxs = nil
}
