// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: moego/business/offering/v1/offering_service.proto

package offeringpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	OfferingService_ListServices_FullMethodName = "/moego.business.offering.v1.OfferingService/ListServices"
	OfferingService_ListLodgings_FullMethodName = "/moego.business.offering.v1.OfferingService/ListLodgings"
)

// OfferingServiceClient is the client API for OfferingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// OfferingService provides APIs for querying available offerings and inventory.
// (hook test)
//
// It returns which services can be booked for given pets at a business (ListServices)
// and which lodging units have capacity for a given date (ListLodgings). Used by both
// staff tools and C-end flows (e.g. online booking) to list what is bookable and in stock.
type OfferingServiceClient interface {
	// Lists services for given pets at a business.
	//
	// Returns a flat list of services (and effective availability) for the requested care type
	// (grooming/boarding/daycare etc.) and optional date range. When service_type is ADDON,
	// pass selected_service_ids to filter add-ons that apply to the chosen primary services.
	// Response includes an overall service list and optionally a per-pet breakdown (pet_services).
	ListServices(ctx context.Context, in *ListServicesRequest, opts ...grpc.CallOption) (*ListServicesResponse, error)
	// Lists lodgings with availability (inventory) for the given date.
	//
	// Use when booking boarding or daycare to show which lodging units have capacity.
	// Each entry indicates whether the lodging is available; when not available,
	// unavailable_reason describes the cause (e.g. over capacity, date conflict).
	ListLodgings(ctx context.Context, in *ListLodgingsRequest, opts ...grpc.CallOption) (*ListLodgingsResponse, error)
}

type offeringServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewOfferingServiceClient(cc grpc.ClientConnInterface) OfferingServiceClient {
	return &offeringServiceClient{cc}
}

func (c *offeringServiceClient) ListServices(ctx context.Context, in *ListServicesRequest, opts ...grpc.CallOption) (*ListServicesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListServicesResponse)
	err := c.cc.Invoke(ctx, OfferingService_ListServices_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *offeringServiceClient) ListLodgings(ctx context.Context, in *ListLodgingsRequest, opts ...grpc.CallOption) (*ListLodgingsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListLodgingsResponse)
	err := c.cc.Invoke(ctx, OfferingService_ListLodgings_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OfferingServiceServer is the server API for OfferingService service.
// All implementations must embed UnimplementedOfferingServiceServer
// for forward compatibility.
//
// OfferingService provides APIs for querying available offerings and inventory.
// (hook test)
//
// It returns which services can be booked for given pets at a business (ListServices)
// and which lodging units have capacity for a given date (ListLodgings). Used by both
// staff tools and C-end flows (e.g. online booking) to list what is bookable and in stock.
type OfferingServiceServer interface {
	// Lists services for given pets at a business.
	//
	// Returns a flat list of services (and effective availability) for the requested care type
	// (grooming/boarding/daycare etc.) and optional date range. When service_type is ADDON,
	// pass selected_service_ids to filter add-ons that apply to the chosen primary services.
	// Response includes an overall service list and optionally a per-pet breakdown (pet_services).
	ListServices(context.Context, *ListServicesRequest) (*ListServicesResponse, error)
	// Lists lodgings with availability (inventory) for the given date.
	//
	// Use when booking boarding or daycare to show which lodging units have capacity.
	// Each entry indicates whether the lodging is available; when not available,
	// unavailable_reason describes the cause (e.g. over capacity, date conflict).
	ListLodgings(context.Context, *ListLodgingsRequest) (*ListLodgingsResponse, error)
	mustEmbedUnimplementedOfferingServiceServer()
}

// UnimplementedOfferingServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOfferingServiceServer struct{}

func (UnimplementedOfferingServiceServer) ListServices(context.Context, *ListServicesRequest) (*ListServicesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListServices not implemented")
}
func (UnimplementedOfferingServiceServer) ListLodgings(context.Context, *ListLodgingsRequest) (*ListLodgingsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListLodgings not implemented")
}
func (UnimplementedOfferingServiceServer) mustEmbedUnimplementedOfferingServiceServer() {}
func (UnimplementedOfferingServiceServer) testEmbeddedByValue()                         {}

// UnsafeOfferingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OfferingServiceServer will
// result in compilation errors.
type UnsafeOfferingServiceServer interface {
	mustEmbedUnimplementedOfferingServiceServer()
}

func RegisterOfferingServiceServer(s grpc.ServiceRegistrar, srv OfferingServiceServer) {
	// If the following call panics, it indicates UnimplementedOfferingServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&OfferingService_ServiceDesc, srv)
}

func _OfferingService_ListServices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListServicesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OfferingServiceServer).ListServices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OfferingService_ListServices_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OfferingServiceServer).ListServices(ctx, req.(*ListServicesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OfferingService_ListLodgings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListLodgingsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OfferingServiceServer).ListLodgings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OfferingService_ListLodgings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OfferingServiceServer).ListLodgings(ctx, req.(*ListLodgingsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// OfferingService_ServiceDesc is the grpc.ServiceDesc for OfferingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OfferingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "moego.business.offering.v1.OfferingService",
	HandlerType: (*OfferingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListServices",
			Handler:    _OfferingService_ListServices_Handler,
		},
		{
			MethodName: "ListLodgings",
			Handler:    _OfferingService_ListLodgings_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "moego/business/offering/v1/offering_service.proto",
}
