// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: moego/business/payment/v1/payment_service.proto

package paymentpb

import (
	commonpb "github.com/MoeGolibrary/moegoapis/genproto/go/common/v1/commonpb"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GetPaymentRequest represents a request to retrieve a specific payment.
type GetPaymentRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique identifier of the payment to retrieve.
	// This ID is required and must be a valid payment ID in the system.
	Id            string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPaymentRequest) Reset() {
	*x = GetPaymentRequest{}
	mi := &file_moego_business_payment_v1_payment_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPaymentRequest) ProtoMessage() {}

func (x *GetPaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_moego_business_payment_v1_payment_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPaymentRequest.ProtoReflect.Descriptor instead.
func (*GetPaymentRequest) Descriptor() ([]byte, []int) {
	return file_moego_business_payment_v1_payment_service_proto_rawDescGZIP(), []int{0}
}

func (x *GetPaymentRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// ListPaymentsRequest encapsulates the parameters for listing payments.
// Supports pagination and filtering to customize the result set.
type ListPaymentsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Pagination parameters to control the size and position of the result set.
	// Required to manage large result sets efficiently.
	Pagination *commonpb.Pagination `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
	// Company identifier for access control and scoping.
	// Required to ensure payments are only accessed within the proper context.
	CompanyId string `protobuf:"bytes,2,opt,name=company_id,json=companyId,proto3" json:"company_id,omitempty"`
	// Filter criteria to apply to the payment list query.
	Filter        *ListPaymentsRequest_Filter `protobuf:"bytes,3,opt,name=filter,proto3" json:"filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPaymentsRequest) Reset() {
	*x = ListPaymentsRequest{}
	mi := &file_moego_business_payment_v1_payment_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPaymentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPaymentsRequest) ProtoMessage() {}

func (x *ListPaymentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_moego_business_payment_v1_payment_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPaymentsRequest.ProtoReflect.Descriptor instead.
func (*ListPaymentsRequest) Descriptor() ([]byte, []int) {
	return file_moego_business_payment_v1_payment_service_proto_rawDescGZIP(), []int{1}
}

func (x *ListPaymentsRequest) GetPagination() *commonpb.Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *ListPaymentsRequest) GetCompanyId() string {
	if x != nil {
		return x.CompanyId
	}
	return ""
}

func (x *ListPaymentsRequest) GetFilter() *ListPaymentsRequest_Filter {
	if x != nil {
		return x.Filter
	}
	return nil
}

// ListPaymentsResponse contains the paginated list of payments and pagination metadata.
type ListPaymentsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Token for retrieving the next page of results.
	// Empty if there are no more results available.
	NextPageToken string `protobuf:"bytes,1,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	// List of payments matching the request criteria.
	// May be empty if no payments match the specified filters.
	Payments      []*Payment `protobuf:"bytes,2,rep,name=payments,proto3" json:"payments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPaymentsResponse) Reset() {
	*x = ListPaymentsResponse{}
	mi := &file_moego_business_payment_v1_payment_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPaymentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPaymentsResponse) ProtoMessage() {}

func (x *ListPaymentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_moego_business_payment_v1_payment_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPaymentsResponse.ProtoReflect.Descriptor instead.
func (*ListPaymentsResponse) Descriptor() ([]byte, []int) {
	return file_moego_business_payment_v1_payment_service_proto_rawDescGZIP(), []int{2}
}

func (x *ListPaymentsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

func (x *ListPaymentsResponse) GetPayments() []*Payment {
	if x != nil {
		return x.Payments
	}
	return nil
}

// Filter defines the criteria for filtering the payment list.
// Contains optional parameters to narrow down the result set.
type ListPaymentsRequest_Filter struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional list of order IDs to filter payments by.
	// If provided, only payments associated with these orders will be returned.
	OrderIds      []string `protobuf:"bytes,1,rep,name=order_ids,json=orderIds,proto3" json:"order_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPaymentsRequest_Filter) Reset() {
	*x = ListPaymentsRequest_Filter{}
	mi := &file_moego_business_payment_v1_payment_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPaymentsRequest_Filter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPaymentsRequest_Filter) ProtoMessage() {}

func (x *ListPaymentsRequest_Filter) ProtoReflect() protoreflect.Message {
	mi := &file_moego_business_payment_v1_payment_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPaymentsRequest_Filter.ProtoReflect.Descriptor instead.
func (*ListPaymentsRequest_Filter) Descriptor() ([]byte, []int) {
	return file_moego_business_payment_v1_payment_service_proto_rawDescGZIP(), []int{1, 0}
}

func (x *ListPaymentsRequest_Filter) GetOrderIds() []string {
	if x != nil {
		return x.OrderIds
	}
	return nil
}

var File_moego_business_payment_v1_payment_service_proto protoreflect.FileDescriptor

const file_moego_business_payment_v1_payment_service_proto_rawDesc = "" +
	"\n" +
	"/moego/business/payment/v1/payment_service.proto\x12\x19moego.business.payment.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a'moego/business/payment/v1/payment.proto\x1a moego/common/v1/pagination.proto\"(\n" +
	"\x11GetPaymentRequest\x12\x13\n" +
	"\x02id\x18\x01 \x01(\tB\x03\xe0A\x02R\x02id\"\xf6\x01\n" +
	"\x13ListPaymentsRequest\x12@\n" +
	"\n" +
	"pagination\x18\x01 \x01(\v2\x1b.moego.common.v1.PaginationB\x03\xe0A\x02R\n" +
	"pagination\x12\"\n" +
	"\n" +
	"company_id\x18\x02 \x01(\tB\x03\xe0A\x02R\tcompanyId\x12M\n" +
	"\x06filter\x18\x03 \x01(\v25.moego.business.payment.v1.ListPaymentsRequest.FilterR\x06filter\x1a*\n" +
	"\x06Filter\x12 \n" +
	"\torder_ids\x18\x01 \x03(\tB\x03\xe0A\x01R\borderIds\"~\n" +
	"\x14ListPaymentsResponse\x12&\n" +
	"\x0fnext_page_token\x18\x01 \x01(\tR\rnextPageToken\x12>\n" +
	"\bpayments\x18\x02 \x03(\v2\".moego.business.payment.v1.PaymentR\bpayments2\x9a\x02\n" +
	"\x0ePaymentService\x12x\n" +
	"\n" +
	"GetPayment\x12,.moego.business.payment.v1.GetPaymentRequest\x1a\".moego.business.payment.v1.Payment\"\x18\x82\xd3\xe4\x93\x02\x12\x12\x10/v1/payment/{id}\x12\x8d\x01\n" +
	"\fListPayments\x12..moego.business.payment.v1.ListPaymentsRequest\x1a/.moego.business.payment.v1.ListPaymentsResponse\"\x1c\x82\xd3\xe4\x93\x02\x16:\x01*\"\x11/v1/payments:listB\x8a\x01\n" +
	"!com.moego.api.business.payment.v1B\fPaymentProtoP\x01ZUgithub.com/MoeGolibrary/moegoapis/genproto/go/business/payment/v1/paymentpb;paymentpbb\x06proto3"

var (
	file_moego_business_payment_v1_payment_service_proto_rawDescOnce sync.Once
	file_moego_business_payment_v1_payment_service_proto_rawDescData []byte
)

func file_moego_business_payment_v1_payment_service_proto_rawDescGZIP() []byte {
	file_moego_business_payment_v1_payment_service_proto_rawDescOnce.Do(func() {
		file_moego_business_payment_v1_payment_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_moego_business_payment_v1_payment_service_proto_rawDesc), len(file_moego_business_payment_v1_payment_service_proto_rawDesc)))
	})
	return file_moego_business_payment_v1_payment_service_proto_rawDescData
}

var file_moego_business_payment_v1_payment_service_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_moego_business_payment_v1_payment_service_proto_goTypes = []any{
	(*GetPaymentRequest)(nil),          // 0: moego.business.payment.v1.GetPaymentRequest
	(*ListPaymentsRequest)(nil),        // 1: moego.business.payment.v1.ListPaymentsRequest
	(*ListPaymentsResponse)(nil),       // 2: moego.business.payment.v1.ListPaymentsResponse
	(*ListPaymentsRequest_Filter)(nil), // 3: moego.business.payment.v1.ListPaymentsRequest.Filter
	(*commonpb.Pagination)(nil),        // 4: moego.common.v1.Pagination
	(*Payment)(nil),                    // 5: moego.business.payment.v1.Payment
}
var file_moego_business_payment_v1_payment_service_proto_depIdxs = []int32{
	4, // 0: moego.business.payment.v1.ListPaymentsRequest.pagination:type_name -> moego.common.v1.Pagination
	3, // 1: moego.business.payment.v1.ListPaymentsRequest.filter:type_name -> moego.business.payment.v1.ListPaymentsRequest.Filter
	5, // 2: moego.business.payment.v1.ListPaymentsResponse.payments:type_name -> moego.business.payment.v1.Payment
	0, // 3: moego.business.payment.v1.PaymentService.GetPayment:input_type -> moego.business.payment.v1.GetPaymentRequest
	1, // 4: moego.business.payment.v1.PaymentService.ListPayments:input_type -> moego.business.payment.v1.ListPaymentsRequest
	5, // 5: moego.business.payment.v1.PaymentService.GetPayment:output_type -> moego.business.payment.v1.Payment
	2, // 6: moego.business.payment.v1.PaymentService.ListPayments:output_type -> moego.business.payment.v1.ListPaymentsResponse
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_moego_business_payment_v1_payment_service_proto_init() }
func file_moego_business_payment_v1_payment_service_proto_init() {
	if File_moego_business_payment_v1_payment_service_proto != nil {
		return
	}
	file_moego_business_payment_v1_payment_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_moego_business_payment_v1_payment_service_proto_rawDesc), len(file_moego_business_payment_v1_payment_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_moego_business_payment_v1_payment_service_proto_goTypes,
		DependencyIndexes: file_moego_business_payment_v1_payment_service_proto_depIdxs,
		MessageInfos:      file_moego_business_payment_v1_payment_service_proto_msgTypes,
	}.Build()
	File_moego_business_payment_v1_payment_service_proto = out.File
	file_moego_business_payment_v1_payment_service_proto_goTypes = nil
	file_moego_business_payment_v1_payment_service_proto_depIdxs = nil
}
