// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: moego/business/event/v1/health_check.proto

package eventpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// HealthCheck represents a system monitoring event used to verify the availability
// and proper functioning of webhook endpoints. These events are sent periodically
// to ensure reliable communication between system components.
type HealthCheck struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Validation string to be echoed back by the webhook endpoint
	// Used to verify bidirectional communication
	// The endpoint must return this exact string in its response
	Validation    string `protobuf:"bytes,1,opt,name=validation,proto3" json:"validation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheck) Reset() {
	*x = HealthCheck{}
	mi := &file_moego_business_event_v1_health_check_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheck) ProtoMessage() {}

func (x *HealthCheck) ProtoReflect() protoreflect.Message {
	mi := &file_moego_business_event_v1_health_check_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheck.ProtoReflect.Descriptor instead.
func (*HealthCheck) Descriptor() ([]byte, []int) {
	return file_moego_business_event_v1_health_check_proto_rawDescGZIP(), []int{0}
}

func (x *HealthCheck) GetValidation() string {
	if x != nil {
		return x.Validation
	}
	return ""
}

var File_moego_business_event_v1_health_check_proto protoreflect.FileDescriptor

const file_moego_business_event_v1_health_check_proto_rawDesc = "" +
	"\n" +
	"*moego/business/event/v1/health_check.proto\x12\x17moego.business.event.v1\"-\n" +
	"\vHealthCheck\x12\x1e\n" +
	"\n" +
	"validation\x18\x01 \x01(\tR\n" +
	"validationB\x86\x01\n" +
	"\x1fcom.moego.api.business.event.v1B\x10HealthCheckProtoP\x01ZOgithub.com/MoeGolibrary/moegoapis/genproto/go/business/event/v1/eventpb;eventpbb\x06proto3"

var (
	file_moego_business_event_v1_health_check_proto_rawDescOnce sync.Once
	file_moego_business_event_v1_health_check_proto_rawDescData []byte
)

func file_moego_business_event_v1_health_check_proto_rawDescGZIP() []byte {
	file_moego_business_event_v1_health_check_proto_rawDescOnce.Do(func() {
		file_moego_business_event_v1_health_check_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_moego_business_event_v1_health_check_proto_rawDesc), len(file_moego_business_event_v1_health_check_proto_rawDesc)))
	})
	return file_moego_business_event_v1_health_check_proto_rawDescData
}

var file_moego_business_event_v1_health_check_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_moego_business_event_v1_health_check_proto_goTypes = []any{
	(*HealthCheck)(nil), // 0: moego.business.event.v1.HealthCheck
}
var file_moego_business_event_v1_health_check_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_moego_business_event_v1_health_check_proto_init() }
func file_moego_business_event_v1_health_check_proto_init() {
	if File_moego_business_event_v1_health_check_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_moego_business_event_v1_health_check_proto_rawDesc), len(file_moego_business_event_v1_health_check_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_moego_business_event_v1_health_check_proto_goTypes,
		DependencyIndexes: file_moego_business_event_v1_health_check_proto_depIdxs,
		MessageInfos:      file_moego_business_event_v1_health_check_proto_msgTypes,
	}.Build()
	File_moego_business_event_v1_health_check_proto = out.File
	file_moego_business_event_v1_health_check_proto_goTypes = nil
	file_moego_business_event_v1_health_check_proto_depIdxs = nil
}
