// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: moego/business/retail/v1/package.proto

package retailpb

import (
	money "google.golang.org/genproto/googleapis/type/money"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Package represents a package of services that can be sold together.
type Package struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique identifier for the package
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// ID of the company that owns this package
	CompanyId string `protobuf:"bytes,2,opt,name=company_id,json=companyId,proto3" json:"company_id,omitempty"`
	// ID of the business location associated with this package
	BusinessId string `protobuf:"bytes,3,opt,name=business_id,json=businessId,proto3" json:"business_id,omitempty"`
	// Name of the package
	Name string `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	// Description of the package
	Description string `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	// Price of the package
	Price *money.Money `protobuf:"bytes,6,opt,name=price,proto3" json:"price,omitempty"`
	// Total value of the services in the package
	TotalValue *money.Money `protobuf:"bytes,7,opt,name=total_value,json=totalValue,proto3" json:"total_value,omitempty"`
	// Tax ID associated with this package
	TaxId string `protobuf:"bytes,8,opt,name=tax_id,json=taxId,proto3" json:"tax_id,omitempty"`
	// Tax rate applied to this package
	TaxRate float64 `protobuf:"fixed64,9,opt,name=tax_rate,json=taxRate,proto3" json:"tax_rate,omitempty"`
	// Number of packages sold
	SoldQuantity int32 `protobuf:"varint,10,opt,name=sold_quantity,json=soldQuantity,proto3" json:"sold_quantity,omitempty"`
	// When this package was created
	CreateTime *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	// When this package was last updated
	UpdateTime *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	// Whether this package is active
	IsActive bool `protobuf:"varint,13,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	// Whether this package can be booked online
	EnableOnlineBooking bool `protobuf:"varint,14,opt,name=enable_online_booking,json=enableOnlineBooking,proto3" json:"enable_online_booking,omitempty"`
	// Expiration days for the package
	// Use 99999999 to indicate never expire
	ExpirationDays int32 `protobuf:"varint,15,opt,name=expiration_days,json=expirationDays,proto3" json:"expiration_days,omitempty"`
	// Source of the package
	Source int32 `protobuf:"varint,16,opt,name=source,proto3" json:"source,omitempty"`
	// Items included in the package
	Items []*Item `protobuf:"bytes,17,rep,name=items,proto3" json:"items,omitempty"`
	// Name of the revenue category assigned to this package
	// Empty if no revenue category is assigned
	RevenueCategoryName string `protobuf:"bytes,18,opt,name=revenue_category_name,json=revenueCategoryName,proto3" json:"revenue_category_name,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *Package) Reset() {
	*x = Package{}
	mi := &file_moego_business_retail_v1_package_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Package) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Package) ProtoMessage() {}

func (x *Package) ProtoReflect() protoreflect.Message {
	mi := &file_moego_business_retail_v1_package_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Package.ProtoReflect.Descriptor instead.
func (*Package) Descriptor() ([]byte, []int) {
	return file_moego_business_retail_v1_package_proto_rawDescGZIP(), []int{0}
}

func (x *Package) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Package) GetCompanyId() string {
	if x != nil {
		return x.CompanyId
	}
	return ""
}

func (x *Package) GetBusinessId() string {
	if x != nil {
		return x.BusinessId
	}
	return ""
}

func (x *Package) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Package) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Package) GetPrice() *money.Money {
	if x != nil {
		return x.Price
	}
	return nil
}

func (x *Package) GetTotalValue() *money.Money {
	if x != nil {
		return x.TotalValue
	}
	return nil
}

func (x *Package) GetTaxId() string {
	if x != nil {
		return x.TaxId
	}
	return ""
}

func (x *Package) GetTaxRate() float64 {
	if x != nil {
		return x.TaxRate
	}
	return 0
}

func (x *Package) GetSoldQuantity() int32 {
	if x != nil {
		return x.SoldQuantity
	}
	return 0
}

func (x *Package) GetCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

func (x *Package) GetUpdateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdateTime
	}
	return nil
}

func (x *Package) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *Package) GetEnableOnlineBooking() bool {
	if x != nil {
		return x.EnableOnlineBooking
	}
	return false
}

func (x *Package) GetExpirationDays() int32 {
	if x != nil {
		return x.ExpirationDays
	}
	return 0
}

func (x *Package) GetSource() int32 {
	if x != nil {
		return x.Source
	}
	return 0
}

func (x *Package) GetItems() []*Item {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *Package) GetRevenueCategoryName() string {
	if x != nil {
		return x.RevenueCategoryName
	}
	return ""
}

// Item represents an item in a package
type Item struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Quantity of this item
	Quantity int32 `protobuf:"varint,1,opt,name=quantity,proto3" json:"quantity,omitempty"`
	// Services included in this item
	Services      []*Service `protobuf:"bytes,2,rep,name=services,proto3" json:"services,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Item) Reset() {
	*x = Item{}
	mi := &file_moego_business_retail_v1_package_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Item) ProtoMessage() {}

func (x *Item) ProtoReflect() protoreflect.Message {
	mi := &file_moego_business_retail_v1_package_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Item.ProtoReflect.Descriptor instead.
func (*Item) Descriptor() ([]byte, []int) {
	return file_moego_business_retail_v1_package_proto_rawDescGZIP(), []int{1}
}

func (x *Item) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *Item) GetServices() []*Service {
	if x != nil {
		return x.Services
	}
	return nil
}

// Service represents a service included in a package item
type Service struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID of the service
	ServiceId string `protobuf:"bytes,1,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	// Unit price of the service
	UnitPrice *money.Money `protobuf:"bytes,2,opt,name=unit_price,json=unitPrice,proto3" json:"unit_price,omitempty"`
	// Name of the service
	Name          string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Service) Reset() {
	*x = Service{}
	mi := &file_moego_business_retail_v1_package_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Service) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Service) ProtoMessage() {}

func (x *Service) ProtoReflect() protoreflect.Message {
	mi := &file_moego_business_retail_v1_package_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Service.ProtoReflect.Descriptor instead.
func (*Service) Descriptor() ([]byte, []int) {
	return file_moego_business_retail_v1_package_proto_rawDescGZIP(), []int{2}
}

func (x *Service) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *Service) GetUnitPrice() *money.Money {
	if x != nil {
		return x.UnitPrice
	}
	return nil
}

func (x *Service) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_moego_business_retail_v1_package_proto protoreflect.FileDescriptor

const file_moego_business_retail_v1_package_proto_rawDesc = "" +
	"\n" +
	"&moego/business/retail/v1/package.proto\x12\x18moego.business.retail.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x17google/type/money.proto\"\xbb\x05\n" +
	"\aPackage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"company_id\x18\x02 \x01(\tR\tcompanyId\x12\x1f\n" +
	"\vbusiness_id\x18\x03 \x01(\tR\n" +
	"businessId\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12(\n" +
	"\x05price\x18\x06 \x01(\v2\x12.google.type.MoneyR\x05price\x123\n" +
	"\vtotal_value\x18\a \x01(\v2\x12.google.type.MoneyR\n" +
	"totalValue\x12\x15\n" +
	"\x06tax_id\x18\b \x01(\tR\x05taxId\x12\x19\n" +
	"\btax_rate\x18\t \x01(\x01R\ataxRate\x12#\n" +
	"\rsold_quantity\x18\n" +
	" \x01(\x05R\fsoldQuantity\x12;\n" +
	"\vcreate_time\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"createTime\x12;\n" +
	"\vupdate_time\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"updateTime\x12\x1b\n" +
	"\tis_active\x18\r \x01(\bR\bisActive\x122\n" +
	"\x15enable_online_booking\x18\x0e \x01(\bR\x13enableOnlineBooking\x12'\n" +
	"\x0fexpiration_days\x18\x0f \x01(\x05R\x0eexpirationDays\x12\x16\n" +
	"\x06source\x18\x10 \x01(\x05R\x06source\x124\n" +
	"\x05items\x18\x11 \x03(\v2\x1e.moego.business.retail.v1.ItemR\x05items\x122\n" +
	"\x15revenue_category_name\x18\x12 \x01(\tR\x13revenueCategoryName\"a\n" +
	"\x04Item\x12\x1a\n" +
	"\bquantity\x18\x01 \x01(\x05R\bquantity\x12=\n" +
	"\bservices\x18\x02 \x03(\v2!.moego.business.retail.v1.ServiceR\bservices\"o\n" +
	"\aService\x12\x1d\n" +
	"\n" +
	"service_id\x18\x01 \x01(\tR\tserviceId\x121\n" +
	"\n" +
	"unit_price\x18\x02 \x01(\v2\x12.google.type.MoneyR\tunitPrice\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04nameB\x86\x01\n" +
	" com.moego.api.business.retail.v1B\fPackageProtoP\x01ZRgithub.com/MoeGolibrary/moegoapis/genproto/go/business/retail/v1/retailpb;retailpbb\x06proto3"

var (
	file_moego_business_retail_v1_package_proto_rawDescOnce sync.Once
	file_moego_business_retail_v1_package_proto_rawDescData []byte
)

func file_moego_business_retail_v1_package_proto_rawDescGZIP() []byte {
	file_moego_business_retail_v1_package_proto_rawDescOnce.Do(func() {
		file_moego_business_retail_v1_package_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_moego_business_retail_v1_package_proto_rawDesc), len(file_moego_business_retail_v1_package_proto_rawDesc)))
	})
	return file_moego_business_retail_v1_package_proto_rawDescData
}

var file_moego_business_retail_v1_package_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_moego_business_retail_v1_package_proto_goTypes = []any{
	(*Package)(nil),               // 0: moego.business.retail.v1.Package
	(*Item)(nil),                  // 1: moego.business.retail.v1.Item
	(*Service)(nil),               // 2: moego.business.retail.v1.Service
	(*money.Money)(nil),           // 3: google.type.Money
	(*timestamppb.Timestamp)(nil), // 4: google.protobuf.Timestamp
}
var file_moego_business_retail_v1_package_proto_depIdxs = []int32{
	3, // 0: moego.business.retail.v1.Package.price:type_name -> google.type.Money
	3, // 1: moego.business.retail.v1.Package.total_value:type_name -> google.type.Money
	4, // 2: moego.business.retail.v1.Package.create_time:type_name -> google.protobuf.Timestamp
	4, // 3: moego.business.retail.v1.Package.update_time:type_name -> google.protobuf.Timestamp
	1, // 4: moego.business.retail.v1.Package.items:type_name -> moego.business.retail.v1.Item
	2, // 5: moego.business.retail.v1.Item.services:type_name -> moego.business.retail.v1.Service
	3, // 6: moego.business.retail.v1.Service.unit_price:type_name -> google.type.Money
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_moego_business_retail_v1_package_proto_init() }
func file_moego_business_retail_v1_package_proto_init() {
	if File_moego_business_retail_v1_package_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_moego_business_retail_v1_package_proto_rawDesc), len(file_moego_business_retail_v1_package_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_moego_business_retail_v1_package_proto_goTypes,
		DependencyIndexes: file_moego_business_retail_v1_package_proto_depIdxs,
		MessageInfos:      file_moego_business_retail_v1_package_proto_msgTypes,
	}.Build()
	File_moego_business_retail_v1_package_proto = out.File
	file_moego_business_retail_v1_package_proto_goTypes = nil
	file_moego_business_retail_v1_package_proto_depIdxs = nil
}
