// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        (unknown)
// source: moego/business/retail/v1/retail_service.proto

package retailpb

import (
	commonpb "github.com/MoeGolibrary/moegoapis/genproto/go/common/v1/commonpb"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request to list products
type ListProductsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// object(Pagination), Pagination parameters.
	// Use page_size to specify results per page (max 500).
	// Use page_token from previous response for next page.
	Pagination *commonpb.Pagination `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
	// string, The company identifier for multi-location businesses.
	// Required for company-wide appointment listing.
	CompanyId string `protobuf:"bytes,2,opt,name=company_id,json=companyId,proto3" json:"company_id,omitempty"`
	// array(string), List of business location IDs to include.
	BusinessIds   []string `protobuf:"bytes,3,rep,name=business_ids,json=businessIds,proto3" json:"business_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProductsRequest) Reset() {
	*x = ListProductsRequest{}
	mi := &file_moego_business_retail_v1_retail_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProductsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProductsRequest) ProtoMessage() {}

func (x *ListProductsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_moego_business_retail_v1_retail_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProductsRequest.ProtoReflect.Descriptor instead.
func (*ListProductsRequest) Descriptor() ([]byte, []int) {
	return file_moego_business_retail_v1_retail_service_proto_rawDescGZIP(), []int{0}
}

func (x *ListProductsRequest) GetPagination() *commonpb.Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *ListProductsRequest) GetCompanyId() string {
	if x != nil {
		return x.CompanyId
	}
	return ""
}

func (x *ListProductsRequest) GetBusinessIds() []string {
	if x != nil {
		return x.BusinessIds
	}
	return nil
}

// Response to list products
type ListProductsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// string, Token for retrieving the next page of results.
	// Empty if there are no more results.
	NextPageToken string `protobuf:"bytes,1,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	// array(Product), List of products.
	Products      []*Product `protobuf:"bytes,2,rep,name=products,proto3" json:"products,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProductsResponse) Reset() {
	*x = ListProductsResponse{}
	mi := &file_moego_business_retail_v1_retail_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProductsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProductsResponse) ProtoMessage() {}

func (x *ListProductsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_moego_business_retail_v1_retail_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProductsResponse.ProtoReflect.Descriptor instead.
func (*ListProductsResponse) Descriptor() ([]byte, []int) {
	return file_moego_business_retail_v1_retail_service_proto_rawDescGZIP(), []int{1}
}

func (x *ListProductsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

func (x *ListProductsResponse) GetProducts() []*Product {
	if x != nil {
		return x.Products
	}
	return nil
}

var File_moego_business_retail_v1_retail_service_proto protoreflect.FileDescriptor

const file_moego_business_retail_v1_retail_service_proto_rawDesc = "" +
	"\n" +
	"-moego/business/retail/v1/retail_service.proto\x12\x18moego.business.retail.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a&moego/business/retail/v1/product.proto\x1a moego/common/v1/pagination.proto\"\xa3\x01\n" +
	"\x13ListProductsRequest\x12@\n" +
	"\n" +
	"pagination\x18\x01 \x01(\v2\x1b.moego.common.v1.PaginationB\x03\xe0A\x02R\n" +
	"pagination\x12\"\n" +
	"\n" +
	"company_id\x18\x02 \x01(\tB\x03\xe0A\x02R\tcompanyId\x12&\n" +
	"\fbusiness_ids\x18\x03 \x03(\tB\x03\xe0A\x02R\vbusinessIds\"}\n" +
	"\x14ListProductsResponse\x12&\n" +
	"\x0fnext_page_token\x18\x01 \x01(\tR\rnextPageToken\x12=\n" +
	"\bproducts\x18\x02 \x03(\v2!.moego.business.retail.v1.ProductR\bproducts2\xa4\x01\n" +
	"\rRetailService\x12\x92\x01\n" +
	"\fListProducts\x12-.moego.business.retail.v1.ListProductsRequest\x1a..moego.business.retail.v1.ListProductsResponse\"#\x82\xd3\xe4\x93\x02\x1d:\x01*\"\x18/v1/retail/products:listB\x8c\x01\n" +
	" com.moego.api.business.retail.v1B\x12RetailServiceProtoP\x01ZRgithub.com/MoeGolibrary/moegoapis/genproto/go/business/retail/v1/retailpb;retailpbb\x06proto3"

var (
	file_moego_business_retail_v1_retail_service_proto_rawDescOnce sync.Once
	file_moego_business_retail_v1_retail_service_proto_rawDescData []byte
)

func file_moego_business_retail_v1_retail_service_proto_rawDescGZIP() []byte {
	file_moego_business_retail_v1_retail_service_proto_rawDescOnce.Do(func() {
		file_moego_business_retail_v1_retail_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_moego_business_retail_v1_retail_service_proto_rawDesc), len(file_moego_business_retail_v1_retail_service_proto_rawDesc)))
	})
	return file_moego_business_retail_v1_retail_service_proto_rawDescData
}

var file_moego_business_retail_v1_retail_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_moego_business_retail_v1_retail_service_proto_goTypes = []any{
	(*ListProductsRequest)(nil),  // 0: moego.business.retail.v1.ListProductsRequest
	(*ListProductsResponse)(nil), // 1: moego.business.retail.v1.ListProductsResponse
	(*commonpb.Pagination)(nil),  // 2: moego.common.v1.Pagination
	(*Product)(nil),              // 3: moego.business.retail.v1.Product
}
var file_moego_business_retail_v1_retail_service_proto_depIdxs = []int32{
	2, // 0: moego.business.retail.v1.ListProductsRequest.pagination:type_name -> moego.common.v1.Pagination
	3, // 1: moego.business.retail.v1.ListProductsResponse.products:type_name -> moego.business.retail.v1.Product
	0, // 2: moego.business.retail.v1.RetailService.ListProducts:input_type -> moego.business.retail.v1.ListProductsRequest
	1, // 3: moego.business.retail.v1.RetailService.ListProducts:output_type -> moego.business.retail.v1.ListProductsResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_moego_business_retail_v1_retail_service_proto_init() }
func file_moego_business_retail_v1_retail_service_proto_init() {
	if File_moego_business_retail_v1_retail_service_proto != nil {
		return
	}
	file_moego_business_retail_v1_product_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_moego_business_retail_v1_retail_service_proto_rawDesc), len(file_moego_business_retail_v1_retail_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_moego_business_retail_v1_retail_service_proto_goTypes,
		DependencyIndexes: file_moego_business_retail_v1_retail_service_proto_depIdxs,
		MessageInfos:      file_moego_business_retail_v1_retail_service_proto_msgTypes,
	}.Build()
	File_moego_business_retail_v1_retail_service_proto = out.File
	file_moego_business_retail_v1_retail_service_proto_goTypes = nil
	file_moego_business_retail_v1_retail_service_proto_depIdxs = nil
}
