// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        (unknown)
// source: moego/business/staff/v1/staff.proto

package staffpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Permission represents a specific action that can be performed in the system.
// Permissions are grouped into roles and assigned to staff members.
type Permission int32

const (
	// Unknown or invalid permission
	// Should not be used when assigning permissions
	Permission_PERMISSION_UNSPECIFIED Permission = 0
)

// Enum value maps for Permission.
var (
	Permission_name = map[int32]string{
		0: "PERMISSION_UNSPECIFIED",
	}
	Permission_value = map[string]int32{
		"PERMISSION_UNSPECIFIED": 0,
	}
)

func (x Permission) Enum() *Permission {
	p := new(Permission)
	*p = x
	return p
}

func (x Permission) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Permission) Descriptor() protoreflect.EnumDescriptor {
	return file_moego_business_staff_v1_staff_proto_enumTypes[0].Descriptor()
}

func (Permission) Type() protoreflect.EnumType {
	return &file_moego_business_staff_v1_staff_proto_enumTypes[0]
}

func (x Permission) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Permission.Descriptor instead.
func (Permission) EnumDescriptor() ([]byte, []int) {
	return file_moego_business_staff_v1_staff_proto_rawDescGZIP(), []int{0}
}

// Staff represents an employee or contractor who provides services in your business.
// Staff members can be assigned to appointments, manage customer relationships,
// and perform various administrative tasks based on their role and permissions.
type Staff struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique identifier for the staff member
	// Format: "stf_" followed by random characters
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Staff member's first name
	FirstName string `protobuf:"bytes,2,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	// Staff member's last name
	LastName string `protobuf:"bytes,3,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	// URL to the staff member's profile picture
	// Optional. Must be a valid HTTPS URL
	Avatar string `protobuf:"bytes,4,opt,name=avatar,proto3" json:"avatar,omitempty"`
	// Staff member's phone number
	// Format: E.164 format (e.g., +12125551234)
	Phone string `protobuf:"bytes,5,opt,name=phone,proto3" json:"phone,omitempty"`
	// Staff member's email address
	// Format: Must be a valid email address
	Email string `protobuf:"bytes,6,opt,name=email,proto3" json:"email,omitempty"`
	// Staff member's role and associated permissions
	// Determines what actions they can perform in the system
	Role *Role `protobuf:"bytes,7,opt,name=role,proto3" json:"role,omitempty"`
	// When this staff member was hired
	// Used for reporting and service history
	HiredTime *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=hired_time,json=hiredTime,proto3" json:"hired_time,omitempty"`
	// IDs of business locations where this staff member works
	// Staff can only be assigned to appointments at these locations
	WorkingBusinessIds []string `protobuf:"bytes,9,rep,name=working_business_ids,json=workingBusinessIds,proto3" json:"working_business_ids,omitempty"`
	// ID of the mobile van assigned to this staff member
	// Only applicable for mobile service providers
	MobileVanId string `protobuf:"bytes,10,opt,name=mobile_van_id,json=mobileVanId,proto3" json:"mobile_van_id,omitempty"`
	// ID of the company this staff member belongs to
	// Used for access control and data segregation
	CompanyId     string `protobuf:"bytes,11,opt,name=company_id,json=companyId,proto3" json:"company_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Staff) Reset() {
	*x = Staff{}
	mi := &file_moego_business_staff_v1_staff_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Staff) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Staff) ProtoMessage() {}

func (x *Staff) ProtoReflect() protoreflect.Message {
	mi := &file_moego_business_staff_v1_staff_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Staff.ProtoReflect.Descriptor instead.
func (*Staff) Descriptor() ([]byte, []int) {
	return file_moego_business_staff_v1_staff_proto_rawDescGZIP(), []int{0}
}

func (x *Staff) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Staff) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *Staff) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *Staff) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *Staff) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *Staff) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Staff) GetRole() *Role {
	if x != nil {
		return x.Role
	}
	return nil
}

func (x *Staff) GetHiredTime() *timestamppb.Timestamp {
	if x != nil {
		return x.HiredTime
	}
	return nil
}

func (x *Staff) GetWorkingBusinessIds() []string {
	if x != nil {
		return x.WorkingBusinessIds
	}
	return nil
}

func (x *Staff) GetMobileVanId() string {
	if x != nil {
		return x.MobileVanId
	}
	return ""
}

func (x *Staff) GetCompanyId() string {
	if x != nil {
		return x.CompanyId
	}
	return ""
}

// Role defines a set of permissions and capabilities assigned to staff members.
// Roles help manage access control and determine what actions staff can perform.
type Role struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique identifier for the role
	// Format: "rol_" followed by random characters
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Display name of the role
	// Example: "Administrator", "Groomer", "Receptionist"
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// List of permissions granted to this role
	// Determines what actions can be performed
	Permissions   []Permission `protobuf:"varint,3,rep,packed,name=permissions,proto3,enum=moego.business.staff.v1.Permission" json:"permissions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Role) Reset() {
	*x = Role{}
	mi := &file_moego_business_staff_v1_staff_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Role) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Role) ProtoMessage() {}

func (x *Role) ProtoReflect() protoreflect.Message {
	mi := &file_moego_business_staff_v1_staff_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Role.ProtoReflect.Descriptor instead.
func (*Role) Descriptor() ([]byte, []int) {
	return file_moego_business_staff_v1_staff_proto_rawDescGZIP(), []int{1}
}

func (x *Role) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Role) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Role) GetPermissions() []Permission {
	if x != nil {
		return x.Permissions
	}
	return nil
}

var File_moego_business_staff_v1_staff_proto protoreflect.FileDescriptor

const file_moego_business_staff_v1_staff_proto_rawDesc = "" +
	"\n" +
	"#moego/business/staff/v1/staff.proto\x12\x17moego.business.staff.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xfa\x02\n" +
	"\x05Staff\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"first_name\x18\x02 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x03 \x01(\tR\blastName\x12\x16\n" +
	"\x06avatar\x18\x04 \x01(\tR\x06avatar\x12\x14\n" +
	"\x05phone\x18\x05 \x01(\tR\x05phone\x12\x14\n" +
	"\x05email\x18\x06 \x01(\tR\x05email\x121\n" +
	"\x04role\x18\a \x01(\v2\x1d.moego.business.staff.v1.RoleR\x04role\x129\n" +
	"\n" +
	"hired_time\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\thiredTime\x120\n" +
	"\x14working_business_ids\x18\t \x03(\tR\x12workingBusinessIds\x12\"\n" +
	"\rmobile_van_id\x18\n" +
	" \x01(\tR\vmobileVanId\x12\x1d\n" +
	"\n" +
	"company_id\x18\v \x01(\tR\tcompanyId\"q\n" +
	"\x04Role\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12E\n" +
	"\vpermissions\x18\x03 \x03(\x0e2#.moego.business.staff.v1.PermissionR\vpermissions*(\n" +
	"\n" +
	"Permission\x12\x1a\n" +
	"\x16PERMISSION_UNSPECIFIED\x10\x00B\x80\x01\n" +
	"\x1fcom.moego.api.business.staff.v1B\n" +
	"StaffProtoP\x01ZOgithub.com/MoeGolibrary/moegoapis/genproto/go/business/staff/v1/staffpb;staffpbb\x06proto3"

var (
	file_moego_business_staff_v1_staff_proto_rawDescOnce sync.Once
	file_moego_business_staff_v1_staff_proto_rawDescData []byte
)

func file_moego_business_staff_v1_staff_proto_rawDescGZIP() []byte {
	file_moego_business_staff_v1_staff_proto_rawDescOnce.Do(func() {
		file_moego_business_staff_v1_staff_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_moego_business_staff_v1_staff_proto_rawDesc), len(file_moego_business_staff_v1_staff_proto_rawDesc)))
	})
	return file_moego_business_staff_v1_staff_proto_rawDescData
}

var file_moego_business_staff_v1_staff_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_moego_business_staff_v1_staff_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_moego_business_staff_v1_staff_proto_goTypes = []any{
	(Permission)(0),               // 0: moego.business.staff.v1.Permission
	(*Staff)(nil),                 // 1: moego.business.staff.v1.Staff
	(*Role)(nil),                  // 2: moego.business.staff.v1.Role
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
}
var file_moego_business_staff_v1_staff_proto_depIdxs = []int32{
	2, // 0: moego.business.staff.v1.Staff.role:type_name -> moego.business.staff.v1.Role
	3, // 1: moego.business.staff.v1.Staff.hired_time:type_name -> google.protobuf.Timestamp
	0, // 2: moego.business.staff.v1.Role.permissions:type_name -> moego.business.staff.v1.Permission
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_moego_business_staff_v1_staff_proto_init() }
func file_moego_business_staff_v1_staff_proto_init() {
	if File_moego_business_staff_v1_staff_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_moego_business_staff_v1_staff_proto_rawDesc), len(file_moego_business_staff_v1_staff_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_moego_business_staff_v1_staff_proto_goTypes,
		DependencyIndexes: file_moego_business_staff_v1_staff_proto_depIdxs,
		EnumInfos:         file_moego_business_staff_v1_staff_proto_enumTypes,
		MessageInfos:      file_moego_business_staff_v1_staff_proto_msgTypes,
	}.Build()
	File_moego_business_staff_v1_staff_proto = out.File
	file_moego_business_staff_v1_staff_proto_goTypes = nil
	file_moego_business_staff_v1_staff_proto_depIdxs = nil
}
